## Potential Model
- Prophet
- ARIMA, ARIMAX, SARIMA
- MA 
- Vector (never used)
- Regression 
- LSTM

In [32]:
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
import os
import pandas as pd

# Path ke folder yang berisi file-file DataFrame
folder_path = '../comodity-price-prediction-penyisihan-arkavidia-9/Harga Bahan Pangan/train'

# Dictionary untuk menyimpan semua DataFrame dengan nama file sebagai key
df_dict = {}

# Loop melalui semua file dalam folder
for file_name in os.listdir(folder_path):
    # Pastikan file yang dibaca adalah file yang diinginkan (misalnya, CSV)
    if file_name.endswith('.csv'):
        # Buat path lengkap ke file
        file_path = os.path.join(folder_path, file_name)
        
        # Baca file dan simpan ke dictionary dengan nama file sebagai key
        df = pd.read_csv(file_path)
        df_dict[file_name] = df  # Gunakan nama file sebagai key

In [34]:
df_bawang_merah = df_dict['Bawang Merah.csv']
df_bawang_putih = df_dict['Bawang Putih Bonggol.csv']
df_beras_medium = df_dict['Beras Medium.csv']
df_beras_premium = df_dict['Beras Premium.csv']
df_cabai_merah_keriting = df_dict['Cabai Merah Keriting.csv']
df_cabai_rawit_merah = df_dict['Cabai Rawit Merah.csv']
df_daging_ayam = df_dict['Daging Ayam Ras.csv']
df_daging_sapi = df_dict['Daging Sapi Murni.csv']
df_gula = df_dict['Gula Konsumsi.csv']
df_minyak_goreng_curah = df_dict['Minyak Goreng Curah.csv']
df_minyak_goreng_kemasan = df_dict['Minyak Goreng Kemasan Sederhana.csv']
df_telur_ayam = df_dict['Telur Ayam Ras.csv']
df_tepung_terigu = df_dict['Tepung Terigu (Curah).csv']

In [35]:
df_bawang_merah

,Date,Aceh,Bali,Banten,Bengkulu,DI Yogyakarta,DKI Jakarta,Gorontalo,Jambi,Jawa Barat,...,Papua,Riau,Sulawesi Barat,Sulawesi Selatan,Sulawesi Tengah,Sulawesi Tenggara,Sulawesi Utara,Sumatera Barat,Sumatera Selatan,Sumatera Utara
0,2022-01-01,28970.0,20870.0,26890.0,26650.0,25240.0,35510.0,31740.0,23390.0,25800.0,...,48610.0,29240.0,25160.0,24910.0,28030.0,30380.0,35750.0,23360.0,26670.0,28710.0
1,2022-01-02,29900.0,20710.0,25600.0,26950.0,25240.0,31850.0,30020.0,23550.0,26010.0,...,50160.0,28750.0,24770.0,24360.0,27200.0,30260.0,35630.0,23790.0,25690.0,28460.0
2,2022-01-03,28970.0,20510.0,26390.0,27290.0,24620.0,34880.0,31250.0,23730.0,25910.0,...,49510.0,27870.0,24140.0,24740.0,26750.0,30080.0,34980.0,22620.0,26270.0,28050.0
3,2022-01-04,29600.0,20180.0,26630.0,27450.0,24370.0,35260.0,31640.0,23300.0,25950.0,...,49670.0,28330.0,24450.0,24710.0,28800.0,29950.0,34920.0,23010.0,26800.0,27800.0
4,2022-01-05,29540.0,19960.0,26610.0,27710.0,24210.0,35260.0,34010.0,23640.0,25700.0,...,46590.0,28240.0,24640.0,24780.0,28990.0,30240.0,34000.0,23330.0,25360.0,27670.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,2024-09-26,28110.0,24060.0,26340.0,26610.0,21990.0,28750.0,34000.0,24460.0,24760.0,...,48080.0,29080.0,31680.0,26510.0,34390.0,30340.0,35310.0,27490.0,25210.0,26020.0
1000,2024-09-27,27890.0,23900.0,26360.0,27130.0,22430.0,30430.0,33710.0,25100.0,25160.0,...,48080.0,29060.0,31120.0,26800.0,33970.0,30090.0,35720.0,26780.0,25500.0,26460.0
1001,2024-09-28,28150.0,23830.0,26460.0,26990.0,22490.0,28120.0,32850.0,25100.0,25070.0,...,47450.0,28730.0,31490.0,26630.0,34460.0,30290.0,35710.0,27260.0,25860.0,26910.0
1002,2024-09-29,28430.0,24140.0,26940.0,27140.0,23750.0,27590.0,31590.0,24950.0,25170.0,...,47490.0,28370.0,30370.0,26690.0,33490.0,30320.0,34850.0,26950.0,26300.0,26930.0
1003,2024-09-30,28960.0,24230.0,27940.0,27390.0,24450.0,30370.0,32730.0,25900.0,25530.0,...,47610.0,28760.0,26240.0,26350.0,33820.0,30260.0,34350.0,27630.0,26100.0,27150.0

In [36]:
df_beras_premium.isnull().sum()

Date                          0
Aceh                         37
Bali                         36
Banten                       37
Bengkulu                     37
DI Yogyakarta                36
DKI Jakarta                  37
Gorontalo                    35
Jambi                        38
Jawa Barat                   37
Jawa Tengah                  34
Jawa Timur                   35
Kalimantan Barat             36
Kalimantan Selatan           37
Kalimantan Tengah            36
Kalimantan Timur             39
Kalimantan Utara             39
Kepulauan Bangka Belitung    38
Kepulauan Riau               39
Lampung                      37
Maluku Utara                 36
Maluku                       37
Nusa Tenggara Barat          37
Nusa Tenggara Timur          34
Papua Barat                  39
Papua                        37
Riau                         35
Sulawesi Barat               39
Sulawesi Selatan             34
Sulawesi Tengah              34
Sulawesi Tenggara            36
Sulawesi Utara               34
Sumatera Barat               35
Sumatera Selatan             38
Sumatera Utara               36
dtype: int64

Imputasi

In [37]:
import pandas as pd

# List semua dataframe
df_list = [
    df_bawang_merah, df_bawang_putih, df_beras_medium, df_beras_premium, df_cabai_merah_keriting,
    df_cabai_rawit_merah, df_daging_ayam, df_daging_sapi, df_gula, df_minyak_goreng_curah,
    df_minyak_goreng_kemasan, df_telur_ayam, df_tepung_terigu
]

# Loop setiap dataframe dan lakukan interpolasi
for i in range(len(df_list)):
    df = df_list[i]  # Ambil dataframe

    # Pisahkan kolom tanggal (asumsi ada kolom 'date' atau 'tanggal')
    date_cols = df.select_dtypes(include=['datetime64', 'object'])  # Deteksi kolom tanggal
    num_cols = df.select_dtypes(include=['number'])  # Ambil hanya kolom numerik

    # Interpolasi hanya untuk kolom numerik
    df_num_imputed = num_cols.interpolate(method='linear', limit_direction='both')

    # Gabungkan kembali kolom tanggal dengan hasil interpolasi
    df_list[i] = pd.concat([date_cols.reset_index(drop=True), df_num_imputed.reset_index(drop=True)], axis=1)

In [38]:
df_dict = {
    'Bawang Merah': df_list[0],
    'Bawang Putih Bonggol': df_list[1],
    'Beras Medium': df_list[2],
    'Beras Premium': df_list[3],
    'Cabai Merah Keriting': df_list[4],
    'Cabai Rawit Merah': df_list[5],
    'Daging Ayam Ras': df_list[6],
    'Daging Sapi Murni': df_list[7],
    'Gula Konsumsi': df_list[8],
    'Minyak Goreng Curah': df_list[9],
    'Minyak Goreng Kemasan Sederhana': df_list[10],
    'Telur Ayam Ras': df_list[11],
    'Tepung Terigu (Curah)': df_list[12]
}

In [26]:
# from prophet import Prophet
# import pandas as pd
# import matplotlib.pyplot as plt

# # Dictionary untuk menyimpan hasil prediksi
# all_predictions = {}

# # Rentang waktu prediksi
# predict_start = '2024-10-01'
# predict_end = '2024-12-31'
# predict_periods = (pd.to_datetime(predict_end) - pd.to_datetime(predict_start)).days

# # Loop untuk setiap dataset (komoditas)
# for komoditas, df in df_dict.items():
#     print(f"\n=== Memproses {komoditas} ===")

#     # Pastikan tanggal dalam format datetime
#     df['Date'] = pd.to_datetime(df['Date'])

#     # Dictionary untuk menyimpan prediksi tiap provinsi dalam satu dataset
#     predictions = {}

#     # Loop untuk setiap provinsi (kecuali kolom tanggal)
#     for provinsi in df.columns[1:]:
#         print(f"  → Prediksi untuk {provinsi}...")

#         # Siapkan DataFrame Prophet
#         df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})

#         # Inisialisasi dan latih model Prophet
#         model = Prophet()
#         model.fit(df_prov)

#         # Buat prediksi sampai tanggal yang diinginkan
#         future = model.make_future_dataframe(periods=predict_periods, freq='D')
#         forecast = model.predict(future)

#         # Simpan hasil prediksi
#         predictions[provinsi] = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

#         # Plot hasil prediksi
#         fig = model.plot(forecast)
#         plt.title(f'Prediksi {komoditas} - {provinsi}')
#         plt.xlabel('Tanggal')
#         plt.ylabel('Harga')
#         plt.show()

#     # Simpan semua prediksi dalam dataset ini
#     all_predictions[komoditas] = predictions

# print("\nSemua prediksi selesai!")

In [28]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler

# Set seed untuk reproducibility
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Dictionary untuk menyimpan hasil prediksi
all_predictions = []

# Rentang waktu prediksi
predict_start = '2024-10-01'
predict_end = '2024-12-31'
predict_periods = (pd.to_datetime(predict_end) - pd.to_datetime(predict_start)).days + 1

# Parameter LSTM
seq_length = 30
epochs = 50
batch_size = 16
learning_rate = 0.001

class LSTMPredictor(nn.Module):
    def __init__(self, input_size=1, hidden_size=50, num_layers=2, output_size=1):
        super(LSTMPredictor, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        return self.fc(lstm_out[:, -1, :])

for komoditas, df in df_dict.items():
    print(f"\n=== Memproses {komoditas} ===")
    
    df['Date'] = pd.to_datetime(df['Date'])
    
    for provinsi in df.columns[1:]:
        print(f"  → Prediksi untuk {provinsi}...")
        
        df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})
        
        # Normalisasi data
        scaler = MinMaxScaler()
        df_prov['y'] = scaler.fit_transform(df_prov[['y']])
        
        # Buat data sekuens
        X, y = [], []
        for i in range(len(df_prov) - seq_length):
            X.append(df_prov['y'].iloc[i:i+seq_length].values)
            y.append(df_prov['y'].iloc[i+seq_length])
        
        X, y = np.array(X), np.array(y)
        X = torch.tensor(X, dtype=torch.float32).unsqueeze(-1).to(device)
        y = torch.tensor(y, dtype=torch.float32).unsqueeze(-1).to(device)
        
        # Pisahkan training & testing
        train_size = int(len(X) * 0.8)
        X_train, X_test = X[:train_size], X[train_size:]
        y_train, y_test = y[:train_size], y[train_size:]
        
        # Bangun model LSTM
        model = LSTMPredictor().to(device)
        criterion = nn.MSELoss()
        optimizer = optim.Adam(model.parameters(), lr=learning_rate)
        
        # Train model
        for epoch in range(epochs):
            model.train()
            optimizer.zero_grad()
            output = model(X_train)
            loss = criterion(output, y_train)
            loss.backward()
            optimizer.step()
        
        # Prediksi masa depan
        model.eval()
        last_sequence = X[-1].unsqueeze(0)  # Data terakhir sebagai input
        future_preds = []
        
        for _ in range(predict_periods):
            with torch.no_grad():
                next_pred = model(last_sequence).item()
            future_preds.append(next_pred)
            
            last_sequence = torch.cat([last_sequence[:, 1:, :], torch.tensor([[[next_pred]]], dtype=torch.float32).to(device)], dim=1)
        
        # Konversi kembali ke skala asli
        future_preds = scaler.inverse_transform(np.array(future_preds).reshape(-1, 1)).flatten()
        
        # Simpan hasil prediksi
        for i, pred in enumerate(future_preds):
            date = pd.to_datetime(predict_start) + pd.Timedelta(days=i)
            all_predictions.append({
                'id': f"{komoditas}/{provinsi}/{date.strftime('%Y-%m-%d')}",
                'price': pred
            })

# Simpan hasil prediksi ke CSV
submission_df = pd.DataFrame(all_predictions)
submission_df.to_csv('submission_lstm_pytorch.csv', index=False)

print("\nSemua prediksi selesai dan disimpan di submission_lstm_pytorch.csv!")

=== Memproses Bawang Merah ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Bawang Putih Bonggol ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Beras Medium ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Beras Premium ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Cabai Merah Keriting ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Cabai Rawit Merah ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Daging Ayam Ras ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Daging Sapi Murni ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Gula Konsumsi ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Minyak Goreng Curah ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Minyak Goreng Kemasan Sederhana ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Telur Ayam Ras ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Tepung Terigu (Curah) ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

Semua prediksi selesai dan disimpan di submission_lstm_pytorch.csv!

In [29]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler

# Set seed untuk reproducibility
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Dictionary untuk menyimpan hasil prediksi
all_predictions = []

# Rentang waktu prediksi
predict_start = '2024-10-01'
predict_end = '2024-12-31'
predict_periods = (pd.to_datetime(predict_end) - pd.to_datetime(predict_start)).days + 1

# Parameter LSTM
seq_length = 30
epochs = 100
batch_size = 16
learning_rate = 0.001

class LSTMPredictor(nn.Module):
    def __init__(self, input_size=1, hidden_size=64, num_layers=3, output_size=1):
        super(LSTMPredictor, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=0.2)
        self.fc = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        return self.fc(lstm_out[:, -1, :])

for komoditas, df in df_dict.items():
    print(f"\n=== Memproses {komoditas} ===")
    
    df['Date'] = pd.to_datetime(df['Date'])
    
    for provinsi in df.columns[1:]:
        print(f"  → Prediksi untuk {provinsi}...")
        
        df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})
        
        # Normalisasi data
        scaler = MinMaxScaler()
        df_prov['y'] = scaler.fit_transform(df_prov[['y']])
        
        # Buat data sekuens
        X, y = [], []
        for i in range(len(df_prov) - seq_length):
            X.append(df_prov['y'].iloc[i:i+seq_length].values)
            y.append(df_prov['y'].iloc[i+seq_length])
        
        X, y = np.array(X), np.array(y)
        X = torch.tensor(X, dtype=torch.float32).unsqueeze(-1).to(device)
        y = torch.tensor(y, dtype=torch.float32).unsqueeze(-1).to(device)
        
        # Pisahkan training & testing
        train_size = int(len(X) * 0.8)
        X_train, X_test = X[:train_size], X[train_size:]
        y_train, y_test = y[:train_size], y[train_size:]
        
        # Bangun model LSTM
        model = LSTMPredictor().to(device)
        criterion = nn.MSELoss()
        optimizer = optim.Adam(model.parameters(), lr=learning_rate)
        
        # Train model
        for epoch in range(epochs):
            model.train()
            optimizer.zero_grad()
            output = model(X_train)
            loss = criterion(output, y_train)
            loss.backward()
            optimizer.step()
            
            if (epoch + 1) % 10 == 0:
                test_output = model(X_test)
                test_loss = criterion(test_output, y_test).item()
                print(f"Epoch {epoch+1}/{epochs}, Training Loss: {loss.item():.6f}, Testing Loss: {test_loss:.6f}")
        
        # Prediksi masa depan
        model.eval()
        last_sequence = X[-1].unsqueeze(0)  # Data terakhir sebagai input
        future_preds = []
        
        for _ in range(predict_periods):
            with torch.no_grad():
                next_pred = model(last_sequence).item()
            future_preds.append(next_pred)
            
            last_sequence = torch.cat([last_sequence[:, 1:, :], torch.tensor([[[next_pred]]], dtype=torch.float32).to(device)], dim=1)
        
        # Konversi kembali ke skala asli
        future_preds = scaler.inverse_transform(np.array(future_preds).reshape(-1, 1)).flatten()
        
        # Simpan hasil prediksi
        for i, pred in enumerate(future_preds):
            date = pd.to_datetime(predict_start) + pd.Timedelta(days=i)
            all_predictions.append({
                'id': f"{komoditas}/{provinsi}/{date.strftime('%Y-%m-%d')}",
                'price': pred
            })

# Simpan hasil prediksi ke CSV
submission_df = pd.DataFrame(all_predictions)
submission_df.to_csv('submission_lstm_pytorch_morelayer.csv', index=False)

print("\nSemua prediksi selesai dan disimpan di submission_lstm_pytorch.csv!")

=== Memproses Bawang Merah ===
  → Prediksi untuk Aceh...
Epoch 10/100, Training Loss: 0.033245, Testing Loss: 0.103639
Epoch 20/100, Training Loss: 0.028414, Testing Loss: 0.126228
Epoch 30/100, Training Loss: 0.025007, Testing Loss: 0.096738
Epoch 40/100, Training Loss: 0.011750, Testing Loss: 0.026025
Epoch 50/100, Training Loss: 0.006872, Testing Loss: 0.020693
Epoch 60/100, Training Loss: 0.004491, Testing Loss: 0.012341
Epoch 70/100, Training Loss: 0.003370, Testing Loss: 0.011066
Epoch 80/100, Training Loss: 0.002739, Testing Loss: 0.007609
Epoch 90/100, Training Loss: 0.002178, Testing Loss: 0.006133
Epoch 100/100, Training Loss: 0.001885, Testing Loss: 0.005629
  → Prediksi untuk Bali...
Epoch 10/100, Training Loss: 0.025386, Testing Loss: 0.045989
Epoch 20/100, Training Loss: 0.025872, Testing Loss: 0.056848
Epoch 30/100, Training Loss: 0.024604, Testing Loss: 0.049149
Epoch 40/100, Training Loss: 0.021748, Testing Loss: 0.038204
Epoch 50/100, Training Loss: 0.012388, Testing Loss: 0.016707
Epoch 60/100, Training Loss: 0.008078, Testing Loss: 0.012541
Epoch 70/100, Training Loss: 0.005935, Testing Loss: 0.009251
Epoch 80/100, Training Loss: 0.004464, Testing Loss: 0.006647
Epoch 90/100, Training Loss: 0.003604, Testing Loss: 0.004693
Epoch 100/100, Training Loss: 0.002667, Testing Loss: 0.003853
  → Prediksi untuk Banten...
Epoch 10/100, Training Loss: 0.031353, Testing Loss: 0.056777
Epoch 20/100, Training Loss: 0.029962, Testing Loss: 0.059394
Epoch 30/100, Training Loss: 0.029578, Testing Loss: 0.055992
Epoch 40/100, Training Loss: 0.026512, Testing Loss: 0.046884
Epoch 50/100, Training Loss: 0.014191, Testing Loss: 0.022889
Epoch 60/100, Training Loss: 0.008780, Testing Loss: 0.022055
Epoch 70/100, Training Loss: 0.006436, Testing Loss: 0.013376
Epoch 80/100, Training Loss: 0.005484, Testing Loss: 0.011117
Epoch 90/100, Training Loss: 0.003868, Testing Loss: 0.008497
Epoch 100/100, Training Loss: 0.003168, Testing Loss: 0.006127
  → Prediksi untuk Bengkulu...
Epoch 10/100, Training Loss: 0.026614, Testing Loss: 0.077927
Epoch 20/100, Training Loss: 0.027475, Testing Loss: 0.093820
Epoch 30/100, Training Loss: 0.026144, Testing Loss: 0.083734
Epoch 40/100, Training Loss: 0.025033, Testing Loss: 0.073640
Epoch 50/100, Training Loss: 0.021602, Testing Loss: 0.064977
Epoch 60/100, Training Loss: 0.009127, Testing Loss: 0.020876
Epoch 70/100, Training Loss: 0.006716, Testing Loss: 0.018783
Epoch 80/100, Training Loss: 0.004904, Testing Loss: 0.013427
Epoch 90/100, Training Loss: 0.003954, Testing Loss: 0.010027
Epoch 100/100, Training Loss: 0.002959, Testing Loss: 0.006436
  → Prediksi untuk DI Yogyakarta...
Epoch 10/100, Training Loss: 0.041904, Testing Loss: 0.072161
Epoch 20/100, Training Loss: 0.029278, Testing Loss: 0.067331
Epoch 30/100, Training Loss: 0.029295, Testing Loss: 0.064729
Epoch 40/100, Training Loss: 0.026656, Testing Loss: 0.054116
Epoch 50/100, Training Loss: 0.018551, Testing Loss: 0.036463
Epoch 60/100, Training Loss: 0.010740, Testing Loss: 0.021016
Epoch 70/100, Training Loss: 0.007885, Testing Loss: 0.016823
Epoch 80/100, Training Loss: 0.006093, Testing Loss: 0.012663
Epoch 90/100, Training Loss: 0.004805, Testing Loss: 0.009386
Epoch 100/100, Training Loss: 0.003749, Testing Loss: 0.006741
  → Prediksi untuk DKI Jakarta...
Epoch 10/100, Training Loss: 0.029747, Testing Loss: 0.073186
Epoch 20/100, Training Loss: 0.024858, Testing Loss: 0.083493
Epoch 30/100, Training Loss: 0.022856, Testing Loss: 0.072397
Epoch 40/100, Training Loss: 0.015712, Testing Loss: 0.038826
Epoch 50/100, Training Loss: 0.005857, Testing Loss: 0.021724
Epoch 60/100, Training Loss: 0.004715, Testing Loss: 0.016336
Epoch 70/100, Training Loss: 0.003438, Testing Loss: 0.013245
Epoch 80/100, Training Loss: 0.002821, Testing Loss: 0.010207
Epoch 90/100, Training Loss: 0.002348, Testing Loss: 0.008712
Epoch 100/100, Training Loss: 0.001997, Testing Loss: 0.007222
  → Prediksi untuk Gorontalo...
Epoch 10/100, Training Loss: 0.050903, Testing Loss: 0.043073
Epoch 20/100, Training Loss: 0.027855, Testing Loss: 0.030678
Epoch 30/100, Training Loss: 0.028947, Testing Loss: 0.031186
Epoch 40/100, Training Loss: 0.026592, Testing Loss: 0.028376
Epoch 50/100, Training Loss: 0.023489, Testing Loss: 0.025939
Epoch 60/100, Training Loss: 0.015372, Testing Loss: 0.017214
Epoch 70/100, Training Loss: 0.010231, Testing Loss: 0.015690
Epoch 80/100, Training Loss: 0.008052, Testing Loss: 0.010256
Epoch 90/100, Training Loss: 0.006074, Testing Loss: 0.009386
Epoch 100/100, Training Loss: 0.004554, Testing Loss: 0.007735
  → Prediksi untuk Jambi...
Epoch 10/100, Training Loss: 0.037748, Testing Loss: 0.082781
Epoch 20/100, Training Loss: 0.035288, Testing Loss: 0.090375
Epoch 30/100, Training Loss: 0.029608, Testing Loss: 0.064493
Epoch 40/100, Training Loss: 0.011950, Testing Loss: 0.020279
Epoch 50/100, Training Loss: 0.008956, Testing Loss: 0.014558
Epoch 60/100, Training Loss: 0.006622, Testing Loss: 0.009901
Epoch 70/100, Training Loss: 0.004970, Testing Loss: 0.007523
Epoch 80/100, Training Loss: 0.003773, Testing Loss: 0.006533
Epoch 90/100, Training Loss: 0.002958, Testing Loss: 0.004822
Epoch 100/100, Training Loss: 0.002423, Testing Loss: 0.004444
  → Prediksi untuk Jawa Barat...
Epoch 10/100, Training Loss: 0.026919, Testing Loss: 0.055167
Epoch 20/100, Training Loss: 0.026964, Testing Loss: 0.059582
Epoch 30/100, Training Loss: 0.024134, Testing Loss: 0.050417
Epoch 40/100, Training Loss: 0.020251, Testing Loss: 0.039580
Epoch 50/100, Training Loss: 0.009639, Testing Loss: 0.020477
Epoch 60/100, Training Loss: 0.008265, Testing Loss: 0.018928
Epoch 70/100, Training Loss: 0.006572, Testing Loss: 0.014315
Epoch 80/100, Training Loss: 0.005068, Testing Loss: 0.011849
Epoch 90/100, Training Loss: 0.003865, Testing Loss: 0.009237
Epoch 100/100, Training Loss: 0.003070, Testing Loss: 0.006837
  → Prediksi untuk Jawa Tengah...
Epoch 10/100, Training Loss: 0.032645, Testing Loss: 0.061380
Epoch 20/100, Training Loss: 0.030184, Testing Loss: 0.060437
Epoch 30/100, Training Loss: 0.027545, Testing Loss: 0.053629
Epoch 40/100, Training Loss: 0.022611, Testing Loss: 0.040782
Epoch 50/100, Training Loss: 0.011090, Testing Loss: 0.024500
Epoch 60/100, Training Loss: 0.008861, Testing Loss: 0.015799
Epoch 70/100, Training Loss: 0.005306, Testing Loss: 0.010257
Epoch 80/100, Training Loss: 0.002881, Testing Loss: 0.005769
Epoch 90/100, Training Loss: 0.001818, Testing Loss: 0.003826
Epoch 100/100, Training Loss: 0.001529, Testing Loss: 0.004945
  → Prediksi untuk Jawa Timur...
Epoch 10/100, Training Loss: 0.030812, Testing Loss: 0.055432
Epoch 20/100, Training Loss: 0.028760, Testing Loss: 0.052020
Epoch 30/100, Training Loss: 0.027266, Testing Loss: 0.048462
Epoch 40/100, Training Loss: 0.022137, Testing Loss: 0.036744
Epoch 50/100, Training Loss: 0.010216, Testing Loss: 0.012529
Epoch 60/100, Training Loss: 0.005342, Testing Loss: 0.007386
Epoch 70/100, Training Loss: 0.003826, Testing Loss: 0.005478
Epoch 80/100, Training Loss: 0.003030, Testing Loss: 0.004484
Epoch 90/100, Training Loss: 0.002150, Testing Loss: 0.003086
Epoch 100/100, Training Loss: 0.001753, Testing Loss: 0.002380
  → Prediksi untuk Kalimantan Barat...
Epoch 10/100, Training Loss: 0.034889, Testing Loss: 0.029149
Epoch 20/100, Training Loss: 0.031668, Testing Loss: 0.019234
Epoch 30/100, Training Loss: 0.026561, Testing Loss: 0.018414
Epoch 40/100, Training Loss: 0.011655, Testing Loss: 0.008643
Epoch 50/100, Training Loss: 0.007798, Testing Loss: 0.005260
Epoch 60/100, Training Loss: 0.004471, Testing Loss: 0.003042
Epoch 70/100, Training Loss: 0.002751, Testing Loss: 0.001895
Epoch 80/100, Training Loss: 0.001447, Testing Loss: 0.001223
Epoch 90/100, Training Loss: 0.001486, Testing Loss: 0.000896
Epoch 100/100, Training Loss: 0.001257, Testing Loss: 0.000889
  → Prediksi untuk Kalimantan Selatan...
Epoch 10/100, Training Loss: 0.024952, Testing Loss: 0.029653
Epoch 20/100, Training Loss: 0.023426, Testing Loss: 0.028853
Epoch 30/100, Training Loss: 0.023280, Testing Loss: 0.028081
Epoch 40/100, Training Loss: 0.021510, Testing Loss: 0.026290
Epoch 50/100, Training Loss: 0.014246, Testing Loss: 0.017046
Epoch 60/100, Training Loss: 0.007919, Testing Loss: 0.011337
Epoch 70/100, Training Loss: 0.005379, Testing Loss: 0.007030
Epoch 80/100, Training Loss: 0.004240, Testing Loss: 0.005707
Epoch 90/100, Training Loss: 0.003580, Testing Loss: 0.004904
Epoch 100/100, Training Loss: 0.002716, Testing Loss: 0.003946
  → Prediksi untuk Kalimantan Tengah...
Epoch 10/100, Training Loss: 0.030182, Testing Loss: 0.037016
Epoch 20/100, Training Loss: 0.026999, Testing Loss: 0.030404
Epoch 30/100, Training Loss: 0.025747, Testing Loss: 0.028720
Epoch 40/100, Training Loss: 0.019302, Testing Loss: 0.021882
Epoch 50/100, Training Loss: 0.007971, Testing Loss: 0.010292
Epoch 60/100, Training Loss: 0.004569, Testing Loss: 0.004838
Epoch 70/100, Training Loss: 0.002809, Testing Loss: 0.003403
Epoch 80/100, Training Loss: 0.002042, Testing Loss: 0.002485
Epoch 90/100, Training Loss: 0.001314, Testing Loss: 0.001770
Epoch 100/100, Training Loss: 0.001126, Testing Loss: 0.001643
  → Prediksi untuk Kalimantan Timur...
Epoch 10/100, Training Loss: 0.023686, Testing Loss: 0.023007
Epoch 20/100, Training Loss: 0.021987, Testing Loss: 0.020219
Epoch 30/100, Training Loss: 0.020631, Testing Loss: 0.017840
Epoch 40/100, Training Loss: 0.018050, Testing Loss: 0.015469
Epoch 50/100, Training Loss: 0.009346, Testing Loss: 0.007782
Epoch 60/100, Training Loss: 0.006556, Testing Loss: 0.005812
Epoch 70/100, Training Loss: 0.004657, Testing Loss: 0.004565
Epoch 80/100, Training Loss: 0.002235, Testing Loss: 0.002460
Epoch 90/100, Training Loss: 0.001572, Testing Loss: 0.001740
Epoch 100/100, Training Loss: 0.001536, Testing Loss: 0.001481
  → Prediksi untuk Kalimantan Utara...
Epoch 10/100, Training Loss: 0.027973, Testing Loss: 0.030100
Epoch 20/100, Training Loss: 0.028314, Testing Loss: 0.033559
Epoch 30/100, Training Loss: 0.025483, Testing Loss: 0.027532
Epoch 40/100, Training Loss: 0.022134, Testing Loss: 0.023111
Epoch 50/100, Training Loss: 0.010982, Testing Loss: 0.011888
Epoch 60/100, Training Loss: 0.007680, Testing Loss: 0.010084
Epoch 70/100, Training Loss: 0.005889, Testing Loss: 0.007460
Epoch 80/100, Training Loss: 0.004397, Testing Loss: 0.006096
Epoch 90/100, Training Loss: 0.002985, Testing Loss: 0.004813
Epoch 100/100, Training Loss: 0.001974, Testing Loss: 0.003951
  → Prediksi untuk Kepulauan Bangka Belitung...
Epoch 10/100, Training Loss: 0.028094, Testing Loss: 0.071002
Epoch 20/100, Training Loss: 0.028062, Testing Loss: 0.074585
Epoch 30/100, Training Loss: 0.026520, Testing Loss: 0.066821
Epoch 40/100, Training Loss: 0.023093, Testing Loss: 0.055278
Epoch 50/100, Training Loss: 0.010033, Testing Loss: 0.027608
Epoch 60/100, Training Loss: 0.006204, Testing Loss: 0.018910
Epoch 70/100, Training Loss: 0.004199, Testing Loss: 0.012837
Epoch 80/100, Training Loss: 0.003400, Testing Loss: 0.009862
Epoch 90/100, Training Loss: 0.003197, Testing Loss: 0.009295
Epoch 100/100, Training Loss: 0.002659, Testing Loss: 0.008497
  → Prediksi untuk Kepulauan Riau...
Epoch 10/100, Training Loss: 0.046649, Testing Loss: 0.036294
Epoch 20/100, Training Loss: 0.037751, Testing Loss: 0.041950
Epoch 30/100, Training Loss: 0.036513, Testing Loss: 0.031298
Epoch 40/100, Training Loss: 0.034402, Testing Loss: 0.024877
Epoch 50/100, Training Loss: 0.027007, Testing Loss: 0.017641
Epoch 60/100, Training Loss: 0.014471, Testing Loss: 0.017999
Epoch 70/100, Training Loss: 0.012584, Testing Loss: 0.013463
Epoch 80/100, Training Loss: 0.011478, Testing Loss: 0.010712
Epoch 90/100, Training Loss: 0.010234, Testing Loss: 0.011233
Epoch 100/100, Training Loss: 0.009083, Testing Loss: 0.008566
  → Prediksi untuk Lampung...
Epoch 10/100, Training Loss: 0.032886, Testing Loss: 0.077918
Epoch 20/100, Training Loss: 0.032478, Testing Loss: 0.085084
Epoch 30/100, Training Loss: 0.031433, Testing Loss: 0.078705
Epoch 40/100, Training Loss: 0.028841, Testing Loss: 0.067041
Epoch 50/100, Training Loss: 0.020858, Testing Loss: 0.045713
Epoch 60/100, Training Loss: 0.009831, Testing Loss: 0.026373
Epoch 70/100, Training Loss: 0.007934, Testing Loss: 0.020534
Epoch 80/100, Training Loss: 0.006546, Testing Loss: 0.017372
Epoch 90/100, Training Loss: 0.005454, Testing Loss: 0.013200
Epoch 100/100, Training Loss: 0.004109, Testing Loss: 0.010744
  → Prediksi untuk Maluku Utara...
Epoch 10/100, Training Loss: 0.030682, Testing Loss: 0.020548
Epoch 20/100, Training Loss: 0.029525, Testing Loss: 0.026434
Epoch 30/100, Training Loss: 0.028056, Testing Loss: 0.022801
Epoch 40/100, Training Loss: 0.019492, Testing Loss: 0.010428
Epoch 50/100, Training Loss: 0.010525, Testing Loss: 0.008415
Epoch 60/100, Training Loss: 0.006828, Testing Loss: 0.005104
Epoch 70/100, Training Loss: 0.004702, Testing Loss: 0.005561
Epoch 80/100, Training Loss: 0.003510, Testing Loss: 0.004193
Epoch 90/100, Training Loss: 0.002792, Testing Loss: 0.004033
Epoch 100/100, Training Loss: 0.002194, Testing Loss: 0.003457
  → Prediksi untuk Maluku...
Epoch 10/100, Training Loss: 0.034870, Testing Loss: 0.036781
Epoch 20/100, Training Loss: 0.031196, Testing Loss: 0.036198
Epoch 30/100, Training Loss: 0.028014, Testing Loss: 0.031765
Epoch 40/100, Training Loss: 0.021448, Testing Loss: 0.025153
Epoch 50/100, Training Loss: 0.009369, Testing Loss: 0.011478
Epoch 60/100, Training Loss: 0.007294, Testing Loss: 0.009264
Epoch 70/100, Training Loss: 0.005826, Testing Loss: 0.007524
Epoch 80/100, Training Loss: 0.004489, Testing Loss: 0.005984
Epoch 90/100, Training Loss: 0.003413, Testing Loss: 0.005217
Epoch 100/100, Training Loss: 0.002670, Testing Loss: 0.003805
  → Prediksi untuk Nusa Tenggara Barat...
Epoch 10/100, Training Loss: 0.034689, Testing Loss: 0.060147
Epoch 20/100, Training Loss: 0.034296, Testing Loss: 0.054280
Epoch 30/100, Training Loss: 0.031991, Testing Loss: 0.050146
Epoch 40/100, Training Loss: 0.026734, Testing Loss: 0.042045
Epoch 50/100, Training Loss: 0.012638, Testing Loss: 0.016419
Epoch 60/100, Training Loss: 0.007324, Testing Loss: 0.012472
Epoch 70/100, Training Loss: 0.005919, Testing Loss: 0.009018
Epoch 80/100, Training Loss: 0.004498, Testing Loss: 0.007408
Epoch 90/100, Training Loss: 0.003592, Testing Loss: 0.006438
Epoch 100/100, Training Loss: 0.002945, Testing Loss: 0.005930
  → Prediksi untuk Nusa Tenggara Timur...
Epoch 10/100, Training Loss: 0.119399, Testing Loss: 0.145097
Epoch 20/100, Training Loss: 0.048310, Testing Loss: 0.097915
Epoch 30/100, Training Loss: 0.049507, Testing Loss: 0.094517
Epoch 40/100, Training Loss: 0.040690, Testing Loss: 0.075932
Epoch 50/100, Training Loss: 0.019247, Testing Loss: 0.039335
Epoch 60/100, Training Loss: 0.011483, Testing Loss: 0.019781
Epoch 70/100, Training Loss: 0.007930, Testing Loss: 0.018397
Epoch 80/100, Training Loss: 0.006839, Testing Loss: 0.016338
Epoch 90/100, Training Loss: 0.005687, Testing Loss: 0.011114
Epoch 100/100, Training Loss: 0.004250, Testing Loss: 0.009898
  → Prediksi untuk Papua Barat...
Epoch 10/100, Training Loss: 0.021693, Testing Loss: 0.024820
Epoch 20/100, Training Loss: 0.024041, Testing Loss: 0.008987
Epoch 30/100, Training Loss: 0.020205, Testing Loss: 0.006197
Epoch 40/100, Training Loss: 0.020197, Testing Loss: 0.006806
Epoch 50/100, Training Loss: 0.019219, Testing Loss: 0.005634
Epoch 60/100, Training Loss: 0.017335, Testing Loss: 0.006188
Epoch 70/100, Training Loss: 0.011759, Testing Loss: 0.005988
Epoch 80/100, Training Loss: 0.006917, Testing Loss: 0.004399
Epoch 90/100, Training Loss: 0.004909, Testing Loss: 0.003997
Epoch 100/100, Training Loss: 0.004341, Testing Loss: 0.003831
  → Prediksi untuk Papua...
Epoch 10/100, Training Loss: 0.044422, Testing Loss: 0.034468
Epoch 20/100, Training Loss: 0.035229, Testing Loss: 0.032944
Epoch 30/100, Training Loss: 0.034619, Testing Loss: 0.031607
Epoch 40/100, Training Loss: 0.031211, Testing Loss: 0.030884
Epoch 50/100, Training Loss: 0.018843, Testing Loss: 0.019954
Epoch 60/100, Training Loss: 0.010202, Testing Loss: 0.014048
Epoch 70/100, Training Loss: 0.007904, Testing Loss: 0.009966
Epoch 80/100, Training Loss: 0.005900, Testing Loss: 0.007660
Epoch 90/100, Training Loss: 0.004697, Testing Loss: 0.007224
Epoch 100/100, Training Loss: 0.004024, Testing Loss: 0.005733
  → Prediksi untuk Riau...
Epoch 10/100, Training Loss: 0.039808, Testing Loss: 0.099006
Epoch 20/100, Training Loss: 0.039585, Testing Loss: 0.121808
Epoch 30/100, Training Loss: 0.034808, Testing Loss: 0.095714
Epoch 40/100, Training Loss: 0.026419, Testing Loss: 0.062963
Epoch 50/100, Training Loss: 0.013086, Testing Loss: 0.027953
Epoch 60/100, Training Loss: 0.009802, Testing Loss: 0.025436
Epoch 70/100, Training Loss: 0.007788, Testing Loss: 0.017646
Epoch 80/100, Training Loss: 0.006155, Testing Loss: 0.013416
Epoch 90/100, Training Loss: 0.004762, Testing Loss: 0.009772
Epoch 100/100, Training Loss: 0.004079, Testing Loss: 0.008176
  → Prediksi untuk Sulawesi Barat...
Epoch 10/100, Training Loss: 0.032132, Testing Loss: 0.031157
Epoch 20/100, Training Loss: 0.027099, Testing Loss: 0.026109
Epoch 30/100, Training Loss: 0.023695, Testing Loss: 0.023442
Epoch 40/100, Training Loss: 0.011072, Testing Loss: 0.011485
Epoch 50/100, Training Loss: 0.006653, Testing Loss: 0.007787
Epoch 60/100, Training Loss: 0.004714, Testing Loss: 0.006631
Epoch 70/100, Training Loss: 0.003380, Testing Loss: 0.004460
Epoch 80/100, Training Loss: 0.002429, Testing Loss: 0.003831
Epoch 90/100, Training Loss: 0.001876, Testing Loss: 0.002950
Epoch 100/100, Training Loss: 0.001651, Testing Loss: 0.002164
  → Prediksi untuk Sulawesi Selatan...
Epoch 10/100, Training Loss: 0.031067, Testing Loss: 0.045786
Epoch 20/100, Training Loss: 0.028299, Testing Loss: 0.035448
Epoch 30/100, Training Loss: 0.026315, Testing Loss: 0.033808
Epoch 40/100, Training Loss: 0.020183, Testing Loss: 0.026976
Epoch 50/100, Training Loss: 0.010485, Testing Loss: 0.024714
Epoch 60/100, Training Loss: 0.008371, Testing Loss: 0.013463
Epoch 70/100, Training Loss: 0.005991, Testing Loss: 0.009091
Epoch 80/100, Training Loss: 0.004000, Testing Loss: 0.007421
Epoch 90/100, Training Loss: 0.002672, Testing Loss: 0.005032
Epoch 100/100, Training Loss: 0.001878, Testing Loss: 0.003722
  → Prediksi untuk Sulawesi Tengah...
Epoch 10/100, Training Loss: 0.028327, Testing Loss: 0.029231
Epoch 20/100, Training Loss: 0.025901, Testing Loss: 0.031008
Epoch 30/100, Training Loss: 0.025784, Testing Loss: 0.028712
Epoch 40/100, Training Loss: 0.023750, Testing Loss: 0.025676
Epoch 50/100, Training Loss: 0.018292, Testing Loss: 0.020538
Epoch 60/100, Training Loss: 0.009367, Testing Loss: 0.011731
Epoch 70/100, Training Loss: 0.006587, Testing Loss: 0.009033
Epoch 80/100, Training Loss: 0.005357, Testing Loss: 0.007903
Epoch 90/100, Training Loss: 0.004572, Testing Loss: 0.006150
Epoch 100/100, Training Loss: 0.003507, Testing Loss: 0.004862
  → Prediksi untuk Sulawesi Tenggara...
Epoch 10/100, Training Loss: 0.037356, Testing Loss: 0.051151
Epoch 20/100, Training Loss: 0.030561, Testing Loss: 0.041319
Epoch 30/100, Training Loss: 0.027057, Testing Loss: 0.037597
Epoch 40/100, Training Loss: 0.020212, Testing Loss: 0.027526
Epoch 50/100, Training Loss: 0.009963, Testing Loss: 0.010634
Epoch 60/100, Training Loss: 0.005973, Testing Loss: 0.008952
Epoch 70/100, Training Loss: 0.004679, Testing Loss: 0.007859
Epoch 80/100, Training Loss: 0.003658, Testing Loss: 0.005623
Epoch 90/100, Training Loss: 0.002875, Testing Loss: 0.005472
Epoch 100/100, Training Loss: 0.002718, Testing Loss: 0.004707
  → Prediksi untuk Sulawesi Utara...
Epoch 10/100, Training Loss: 0.028263, Testing Loss: 0.035109
Epoch 20/100, Training Loss: 0.027014, Testing Loss: 0.034315
Epoch 30/100, Training Loss: 0.024752, Testing Loss: 0.030107
Epoch 40/100, Training Loss: 0.013240, Testing Loss: 0.016384

In [55]:
import pandas as pd
from prophet import Prophet

# Dictionary untuk menyimpan hasil prediksi
all_predictions = []

# Rentang waktu prediksi
predict_start = '2024-10-01'
predict_end = '2024-12-31'
predict_periods = (pd.to_datetime(predict_end) - pd.to_datetime(predict_start)).days + 1

# Pastikan format tanggal sudah sesuai
# df_usd_idr['Date'] = pd.to_datetime(df_usd_idr['Date'])
# df_usd_idr = df_usd_idr.rename(columns={'Date': 'ds'})  # Prophet butuh format kolom 'ds'

# Loop untuk setiap dataset (komoditas)
for komoditas, df in df_dict.items():
    print(f"\n=== Memproses {komoditas} ===")

    # Pastikan tanggal dalam format datetime
    df['Date'] = pd.to_datetime(df['Date'])

    # Loop untuk setiap provinsi (kecuali kolom tanggal)
    for provinsi in df.columns[1:]:
        print(f"  → Prediksi untuk {provinsi}...")

        # Siapkan DataFrame Prophet
        df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})

        # Gabungkan dengan data USD/IDR berdasarkan tanggal
        df_merged = df_prov.merge(df_usd_idr, on='ds', how='left')

        # Inisialisasi dan latih model Prophet dengan regressor
        model = Prophet()
        model.add_regressor('Adj Close')  # Pastikan kolom ini ada di df_usd_idr

        model.fit(df_merged)

        # Buat prediksi sampai tanggal yang diinginkan
        future = model.make_future_dataframe(periods=predict_periods, freq='D')

        # Tambahkan nilai USD/IDR untuk masa depan
        future = future.merge(df_usd_idr, on='ds', how='left')

        # Prediksi dengan Prophet
        forecast = model.predict(future)

        # Simpan hasil prediksi dalam format yang sesuai
        for _, row in forecast.iterrows():
            if row['ds'].strftime('%Y-%m-%d') >= predict_start:
                all_predictions.append({
                    'id': f"{komoditas}/{provinsi}/{row['ds'].strftime('%Y-%m-%d')}",
                    'price': row['yhat']
                })

# Simpan hasil prediksi ke file CSV
submission_df = pd.DataFrame(all_predictions)
submission_df.to_csv('submission_prophet_usd_idr.csv', index=False)

print("\nSemua prediksi selesai dan disimpan di submission_prophet_usd_idr.csv!")

23:23:15 - cmdstanpy - INFO - Chain [1] start processing

=== Memproses Bawang Merah ===
  → Prediksi untuk Aceh...

23:23:15 - cmdstanpy - INFO - Chain [1] done processing

ValueError: Found NaN in column 'Adj Close'

In [56]:
future

,ds,Adj Close,Close,High,Low,Open,Volume
0,2022-01-01,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0.0
1,2022-01-02,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0.0
2,2022-01-03,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0.0
3,2022-01-04,14283.599609,14283.599609,14383.299805,14259.000000,14303.700195,0.0
4,2022-01-05,14385.500000,14385.500000,14398.500000,14336.700195,14346.400391,0.0
...,...,...,...,...,...,...,...
1091,2024-12-27,NaN,NaN,NaN,NaN,NaN,NaN
1092,2024-12-28,NaN,NaN,NaN,NaN,NaN,NaN
1093,2024-12-29,NaN,NaN,NaN,NaN,NaN,NaN
1094,2024-12-30,NaN,NaN,NaN,NaN,NaN,NaN
1095,2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
from prophet import Prophet
import pandas as pd
import numpy as np
from itertools import product

# Fungsi MAPE
def mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# Daftar hyperparameter untuk tuning
param_grid = {
    'changepoint_prior_scale': [0.01, 0.05, 0.1, 0.5],
    'seasonality_prior_scale': [0.1, 1.0, 10.0],
    'holidays_prior_scale': [0.1, 1.0, 10.0],
    'seasonality_mode': ['additive', 'multiplicative']
}
param_combinations = list(product(*param_grid.values()))

# Data
df = df_dict['Bawang Merah']
provinsi_list = df.columns[1:]  # Semua kolom kecuali 'Date'

# Variabel untuk menyimpan hasil terbaik
best_avg_mape = float('inf')
best_params = None

# Grid Search
for params in param_combinations:
    mape_list = []  # Simpan MAPE untuk setiap provinsi

    for provinsi in provinsi_list:
        # Ubah format tanggal
        df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})

        # Ambil 2 bulan terakhir sebagai validasi
        valid_size = 60  # Asumsi sekitar 30 hari per bulan
        train = df_prov.iloc[:-valid_size]  # Semua kecuali 2 bulan terakhir
        valid = df_prov.iloc[-valid_size:]  # 2 bulan terakhir

        # Pastikan validasi tidak kosong
        if valid.empty:
            continue

        try:
            # Train model
            model = Prophet(
                changepoint_prior_scale=params[0],
                seasonality_prior_scale=params[1],
                holidays_prior_scale=params[2],
                seasonality_mode=params[3]
            )
            model.fit(train)

            # Prediksi
            future = model.make_future_dataframe(periods=valid_size, freq='D')
            forecast = model.predict(future)
            predicted = forecast['yhat'].iloc[-valid_size:].values  

            # Pastikan jumlah prediksi sesuai
            if len(predicted) != len(valid):
                continue

            # Hitung MAPE
            error = mape(valid['y'].values, predicted)
            mape_list.append(error)

        except Exception:
            continue

    # Hitung rata-rata MAPE untuk kombinasi parameter ini
    if mape_list:
        avg_mape = np.mean(mape_list)

        # Simpan parameter terbaik jika rata-rata MAPE lebih kecil
        if avg_mape < best_avg_mape:
            best_avg_mape = avg_mape
            best_params = params

# Output hasil terbaik
if best_params:
    print(f"✅ **Parameter terbaik:** {best_params}")
    print(f"📊 **Rata-rata MAPE terbaik:** {best_avg_mape:.4f}")
else:
    print("⚠️ Tidak ada parameter yang menghasilkan model valid!")

17:52:36 - cmdstanpy - INFO - Chain [1] start processing
17:52:36 - cmdstanpy - INFO - Chain [1] done processing
17:52:36 - cmdstanpy - INFO - Chain [1] start processing
17:52:36 - cmdstanpy - INFO - Chain [1] done processing
17:52:36 - cmdstanpy - INFO - Chain [1] start processing
17:52:36 - cmdstanpy - INFO - Chain [1] done processing
17:52:37 - cmdstanpy - INFO - Chain [1] start processing
17:52:37 - cmdstanpy - INFO - Chain [1] done processing
17:52:37 - cmdstanpy - INFO - Chain [1] start processing
17:52:37 - cmdstanpy - INFO - Chain [1] done processing
17:52:37 - cmdstanpy - INFO - Chain [1] start processing
17:52:37 - cmdstanpy - INFO - Chain [1] done processing
17:52:37 - cmdstanpy - INFO - Chain [1] start processing
17:52:37 - cmdstanpy - INFO - Chain [1] done processing
17:52:38 - cmdstanpy - INFO - Chain [1] start processing
17:52:38 - cmdstanpy - INFO - Chain [1] done processing
17:52:38 - cmdstanpy - INFO - Chain [1] start processing
17:52:38 - cmdstanpy - INFO - Chain [1] done processing
17:52:38 - cmdstanpy - INFO - Chain [1] start processing
17:52:38 - cmdstanpy - INFO - Chain [1] done processing
17:52:38 - cmdstanpy - INFO - Chain [1] start processing
17:52:38 - cmdstanpy - INFO - Chain [1] done processing
17:52:39 - cmdstanpy - INFO - Chain [1] start processing
17:52:39 - cmdstanpy - INFO - Chain [1] done processing
17:52:39 - cmdstanpy - INFO - Chain [1] start processing
17:52:39 - cmdstanpy - INFO - Chain [1] done processing
17:52:39 - cmdstanpy - INFO - Chain [1] start processing
17:52:39 - cmdstanpy - INFO - Chain [1] done processing
17:52:39 - cmdstanpy - INFO - Chain [1] start processing
17:52:39 - cmdstanpy - INFO - Chain [1] done processing
17:52:40 - cmdstanpy - INFO - Chain [1] start processing
17:52:40 - cmdstanpy - INFO - Chain [1] done processing
17:52:40 - cmdstanpy - INFO - Chain [1] start processing
17:52:40 - cmdstanpy - INFO - Chain [1] done processing
17:52:40 - cmdstanpy - INFO - Chain [1] start processing
17:52:40 - cmdstanpy - INFO - Chain [1] done processing
17:52:40 - cmdstanpy - INFO - Chain [1] start processing
17:52:40 - cmdstanpy - INFO - Chain [1] done processing
17:52:40 - cmdstanpy - INFO - Chain [1] start processing
17:52:41 - cmdstanpy - INFO - Chain [1] done processing
17:52:41 - cmdstanpy - INFO - Chain [1] start processing
17:52:41 - cmdstanpy - INFO - Chain [1] done processing
17:52:41 - cmdstanpy - INFO - Chain [1] start processing
17:52:41 - cmdstanpy - INFO - Chain [1] done processing
17:52:41 - cmdstanpy - INFO - Chain [1] start processing
17:52:41 - cmdstanpy - INFO - Chain [1] done processing
17:52:41 - cmdstanpy - INFO - Chain [1] start processing
17:52:41 - cmdstanpy - INFO - Chain [1] done processing
17:52:42 - cmdstanpy - INFO - Chain [1] start processing
17:52:42 - cmdstanpy - INFO - Chain [1] done processing
17:52:42 - cmdstanpy - INFO - Chain [1] start processing
17:52:42 - cmdstanpy - INFO - Chain [1] done processing
17:52:42 - cmdstanpy - INFO - Chain [1] start processing
17:52:42 - cmdstanpy - INFO - Chain [1] done processing
17:52:42 - cmdstanpy - INFO - Chain [1] start processing
17:52:42 - cmdstanpy - INFO - Chain [1] done processing
17:52:43 - cmdstanpy - INFO - Chain [1] start processing
17:52:43 - cmdstanpy - INFO - Chain [1] done processing
17:52:43 - cmdstanpy - INFO - Chain [1] start processing
17:52:43 - cmdstanpy - INFO - Chain [1] done processing
17:52:43 - cmdstanpy - INFO - Chain [1] start processing
17:52:43 - cmdstanpy - INFO - Chain [1] done processing
17:52:43 - cmdstanpy - INFO - Chain [1] start processing
17:52:43 - cmdstanpy - INFO - Chain [1] done processing
17:52:44 - cmdstanpy - INFO - Chain [1] start processing
17:52:44 - cmdstanpy - INFO - Chain [1] done processing
17:52:44 - cmdstanpy - INFO - Chain [1] start processing
17:52:44 - cmdstanpy - INFO - Chain [1] done processing
17:52:44 - cmdstanpy - INFO - Chain [1] start processing
17:52:44 - cmdstanpy - INFO - Chain [1] done processing
17:52:44 - cmdstanpy - INFO - Chain [1] start processing
17:52:44 - cmdstanpy - INFO - Chain [1] done processing
17:52:44 - cmdstanpy - INFO - Chain [1] start processing
17:52:44 - cmdstanpy - INFO - Chain [1] done processing
17:52:45 - cmdstanpy - INFO - Chain [1] start processing
17:52:45 - cmdstanpy - INFO - Chain [1] done processing
17:52:45 - cmdstanpy - INFO - Chain [1] start processing
17:52:45 - cmdstanpy - INFO - Chain [1] done processing
17:52:45 - cmdstanpy - INFO - Chain [1] start processing
17:52:45 - cmdstanpy - INFO - Chain [1] done processing
17:52:45 - cmdstanpy - INFO - Chain [1] start processing
17:52:45 - cmdstanpy - INFO - Chain [1] done processing
17:52:46 - cmdstanpy - INFO - Chain [1] start processing
17:52:46 - cmdstanpy - INFO - Chain [1] done processing
17:52:46 - cmdstanpy - INFO - Chain [1] start processing
17:52:46 - cmdstanpy - INFO - Chain [1] done processing
17:52:46 - cmdstanpy - INFO - Chain [1] start processing
17:52:46 - cmdstanpy - INFO - Chain [1] done processing
17:52:46 - cmdstanpy - INFO - Chain [1] start processing
17:52:46 - cmdstanpy - INFO - Chain [1] done processing
17:52:47 - cmdstanpy - INFO - Chain [1] start processing
17:52:47 - cmdstanpy - INFO - Chain [1] done processing
17:52:47 - cmdstanpy - INFO - Chain [1] start processing
17:52:47 - cmdstanpy - INFO - Chain [1] done processing
17:52:47 - cmdstanpy - INFO - Chain [1] start processing
17:52:47 - cmdstanpy - INFO - Chain [1] done processing
17:52:47 - cmdstanpy - INFO - Chain [1] start processing
17:52:47 - cmdstanpy - INFO - Chain [1] done processing
17:52:47 - cmdstanpy - INFO - Chain [1] start processing
17:52:48 - cmdstanpy - INFO - Chain [1] done processing
17:52:48 - cmdstanpy - INFO - Chain [1] start processing
17:52:48 - cmdstanpy - INFO - Chain [1] done processing
17:52:48 - cmdstanpy - INFO - Chain [1] start processing
17:52:48 - cmdstanpy - INFO - Chain [1] done processing
17:52:48 - cmdstanpy - INFO - Chain [1] start processing
17:52:48 - cmdstanpy - INFO - Chain [1] done processing
17:52:48 - cmdstanpy - INFO - Chain [1] start processing
17:52:48 - cmdstanpy - INFO - Chain [1] done processing
17:52:49 - cmdstanpy - INFO - Chain [1] start processing
17:52:49 - cmdstanpy - INFO - Chain [1] done processing
17:52:49 - cmdstanpy - INFO - Chain [1] start processing
17:52:49 - cmdstanpy - INFO - Chain [1] done processing
17:52:49 - cmdstanpy - INFO - Chain [1] start processing
17:52:49 - cmdstanpy - INFO - Chain [1] done processing
17:52:49 - cmdstanpy - INFO - Chain [1] start processing
17:52:49 - cmdstanpy - INFO - Chain [1] done processing
17:52:50 - cmdstanpy - INFO - Chain [1] start processing
17:52:50 - cmdstanpy - INFO - Chain [1] done processing
17:52:50 - cmdstanpy - INFO - Chain [1] start processing
17:52:50 - cmdstanpy - INFO - Chain [1] done processing
17:52:50 - cmdstanpy - INFO - Chain [1] start processing
17:52:50 - cmdstanpy - INFO - Chain [1] done processing
17:52:50 - cmdstanpy - INFO - Chain [1] start processing
17:52:50 - cmdstanpy - INFO - Chain [1] done processing
17:52:51 - cmdstanpy - INFO - Chain [1] start processing
17:52:51 - cmdstanpy - INFO - Chain [1] done processing
17:52:51 - cmdstanpy - INFO - Chain [1] start processing
17:52:51 - cmdstanpy - INFO - Chain [1] done processing
17:52:51 - cmdstanpy - INFO - Chain [1] start processing
17:52:51 - cmdstanpy - INFO - Chain [1] done processing
17:52:51 - cmdstanpy - INFO - Chain [1] start processing
17:52:51 - cmdstanpy - INFO - Chain [1] done processing
17:52:52 - cmdstanpy - INFO - Chain [1] start processing
17:52:52 - cmdstanpy - INFO - Chain [1] done processing
17:52:52 - cmdstanpy - INFO - Chain [1] start processing
17:52:52 - cmdstanpy - INFO - Chain [1] done processing
17:52:52 - cmdstanpy - INFO - Chain [1] start processing
17:52:52 - cmdstanpy - INFO - Chain [1] done processing
17:52:52 - cmdstanpy - INFO - Chain [1] start processing
17:52:52 - cmdstanpy - INFO - Chain [1] done processing
17:52:52 - cmdstanpy - INFO - Chain [1] start processing
17:52:53 - cmdstanpy - INFO - Chain [1] done processing
17:52:53 - cmdstanpy - INFO - Chain [1] start processing
17:52:53 - cmdstanpy - INFO - Chain [1] done processing
17:52:53 - cmdstanpy - INFO - Chain [1] start processing
17:52:53 - cmdstanpy - INFO - Chain [1] done processing
17:52:53 - cmdstanpy - INFO - Chain [1] start processing
17:52:53 - cmdstanpy - INFO - Chain [1] done processing
17:52:53 - cmdstanpy - INFO - Chain [1] start processing
17:52:54 - cmdstanpy - INFO - Chain [1] done processing
17:52:54 - cmdstanpy - INFO - Chain [1] start processing
17:52:54 - cmdstanpy - INFO - Chain [1] done processing
17:52:54 - cmdstanpy - INFO - Chain [1] start processing
17:52:54 - cmdstanpy - INFO - Chain [1] done processing
17:52:54 - cmdstanpy - INFO - Chain [1] start processing
17:52:54 - cmdstanpy - INFO - Chain [1] done processing
17:52:54 - cmdstanpy - INFO - Chain [1] start processing
17:52:55 - cmdstanpy - INFO - Chain [1] done processing
17:52:55 - cmdstanpy - INFO - Chain [1] start processing
17:52:55 - cmdstanpy - INFO - Chain [1] done processing
17:52:55 - cmdstanpy - INFO - Chain [1] start processing
17:52:55 - cmdstanpy - INFO - Chain [1] done processing
17:52:55 - cmdstanpy - INFO - Chain [1] start processing
17:52:55 - cmdstanpy - INFO - Chain [1] done processing
17:52:55 - cmdstanpy - INFO - Chain [1] start processing
17:52:55 - cmdstanpy - INFO - Chain [1] done processing
17:52:56 - cmdstanpy - INFO - Chain [1] start processing
17:52:56 - cmdstanpy - INFO - Chain [1] done processing
17:52:56 - cmdstanpy - INFO - Chain [1] start processing
17:52:56 - cmdstanpy - INFO - Chain [1] done processing
17:52:56 - cmdstanpy - INFO - Chain [1] start processing
17:52:56 - cmdstanpy - INFO - Chain [1] done processing
17:52:56 - cmdstanpy - INFO - Chain [1] start processing
17:52:56 - cmdstanpy - INFO - Chain [1] done processing
17:52:57 - cmdstanpy - INFO - Chain [1] start processing
17:52:57 - cmdstanpy - INFO - Chain [1] done processing
17:52:57 - cmdstanpy - INFO - Chain [1] start processing
17:52:57 - cmdstanpy - INFO - Chain [1] done processing
17:52:57 - cmdstanpy - INFO - Chain [1] start processing
17:52:57 - cmdstanpy - INFO - Chain [1] done processing
17:52:57 - cmdstanpy - INFO - Chain [1] start processing
17:52:57 - cmdstanpy - INFO - Chain [1] done processing
17:52:58 - cmdstanpy - INFO - Chain [1] start processing
17:52:58 - cmdstanpy - INFO - Chain [1] done processing
17:52:58 - cmdstanpy - INFO - Chain [1] start processing
17:52:58 - cmdstanpy - INFO - Chain [1] done processing
17:52:58 - cmdstanpy - INFO - Chain [1] start processing
17:52:58 - cmdstanpy - INFO - Chain [1] done processing
17:52:58 - cmdstanpy - INFO - Chain [1] start processing
17:52:58 - cmdstanpy - INFO - Chain [1] done processing
17:52:59 - cmdstanpy - INFO - Chain [1] start processing
17:52:59 - cmdstanpy - INFO - Chain [1] done processing
17:52:59 - cmdstanpy - INFO - Chain [1] start processing
17:52:59 - cmdstanpy - INFO - Chain [1] done processing
17:52:59 - cmdstanpy - INFO - Chain [1] start processing
17:52:59 - cmdstanpy - INFO - Chain [1] done processing
17:52:59 - cmdstanpy - INFO - Chain [1] start processing
17:52:59 - cmdstanpy - INFO - Chain [1] done processing
17:52:59 - cmdstanpy - INFO - Chain [1] start processing
17:53:00 - cmdstanpy - INFO - Chain [1] done processing
17:53:00 - cmdstanpy - INFO - Chain [1] start processing
17:53:00 - cmdstanpy - INFO - Chain [1] done processing
17:53:00 - cmdstanpy - INFO - Chain [1] start processing
17:53:00 - cmdstanpy - INFO - Chain [1] done processing
17:53:00 - cmdstanpy - INFO - Chain [1] start processing
17:53:00 - cmdstanpy - INFO - Chain [1] done processing
17:53:00 - cmdstanpy - INFO - Chain [1] start processing
17:53:00 - cmdstanpy - INFO - Chain [1] done processing
17:53:01 - cmdstanpy - INFO - Chain [1] start processing
17:53:01 - cmdstanpy - INFO - Chain [1] done processing
17:53:01 - cmdstanpy - INFO - Chain [1] start processing
17:53:01 - cmdstanpy - INFO - Chain [1] done processing
17:53:01 - cmdstanpy - INFO - Chain [1] start processing
17:53:01 - cmdstanpy - INFO - Chain [1] done processing
17:53:01 - cmdstanpy - INFO - Chain [1] start processing
17:53:01 - cmdstanpy - INFO - Chain [1] done processing
17:53:02 - cmdstanpy - INFO - Chain [1] start processing
17:53:02 - cmdstanpy - INFO - Chain [1] done processing
17:53:02 - cmdstanpy - INFO - Chain [1] start processing
17:53:02 - cmdstanpy - INFO - Chain [1] done processing
17:53:02 - cmdstanpy - INFO - Chain [1] start processing
17:53:02 - cmdstanpy - INFO - Chain [1] done processing
17:53:02 - cmdstanpy - INFO - Chain [1] start processing
17:53:02 - cmdstanpy - INFO - Chain [1] done processing
17:53:02 - cmdstanpy - INFO - Chain [1] start processing
17:53:03 - cmdstanpy - INFO - Chain [1] done processing
17:53:03 - cmdstanpy - INFO - Chain [1] start processing
17:53:03 - cmdstanpy - INFO - Chain [1] done processing
17:53:03 - cmdstanpy - INFO - Chain [1] start processing
17:53:03 - cmdstanpy - INFO - Chain [1] done processing
17:53:03 - cmdstanpy - INFO - Chain [1] start processing
17:53:03 - cmdstanpy - INFO - Chain [1] done processing
17:53:03 - cmdstanpy - INFO - Chain [1] start processing
17:53:03 - cmdstanpy - INFO - Chain [1] done processing
17:53:04 - cmdstanpy - INFO - Chain [1] start processing
17:53:04 - cmdstanpy - INFO - Chain [1] done processing
17:53:04 - cmdstanpy - INFO - Chain [1] start processing
17:53:04 - cmdstanpy - INFO - Chain [1] done processing
17:53:04 - cmdstanpy - INFO - Chain [1] start processing
17:53:04 - cmdstanpy - INFO - Chain [1] done processing
17:53:04 - cmdstanpy - INFO - Chain [1] start processing
17:53:04 - cmdstanpy - INFO - Chain [1] done processing
17:53:05 - cmdstanpy - INFO - Chain [1] start processing
17:53:05 - cmdstanpy - INFO - Chain [1] done processing
17:53:05 - cmdstanpy - INFO - Chain [1] start processing
17:53:05 - cmdstanpy - INFO - Chain [1] done processing
17:53:05 - cmdstanpy - INFO - Chain [1] start processing
17:53:05 - cmdstanpy - INFO - Chain [1] done processing
17:53:05 - cmdstanpy - INFO - Chain [1] start processing
17:53:05 - cmdstanpy - INFO - Chain [1] done processing
17:53:05 - cmdstanpy - INFO - Chain [1] start processing
17:53:06 - cmdstanpy - INFO - Chain [1] done processing
17:53:06 - cmdstanpy - INFO - Chain [1] start processing
17:53:06 - cmdstanpy - INFO - Chain [1] done processing
17:53:06 - cmdstanpy - INFO - Chain [1] start processing
17:53:06 - cmdstanpy - INFO - Chain [1] done processing
17:53:06 - cmdstanpy - INFO - Chain [1] start processing
17:53:06 - cmdstanpy - INFO - Chain [1] done processing
17:53:06 - cmdstanpy - INFO - Chain [1] start processing
17:53:06 - cmdstanpy - INFO - Chain [1] done processing
17:53:07 - cmdstanpy - INFO - Chain [1] start processing
17:53:07 - cmdstanpy - INFO - Chain [1] done processing
17:53:07 - cmdstanpy - INFO - Chain [1] start processing
17:53:07 - cmdstanpy - INFO - Chain [1] done processing
17:53:07 - cmdstanpy - INFO - Chain [1] start processing
17:53:07 - cmdstanpy - INFO - Chain [1] done processing
17:53:07 - cmdstanpy - INFO - Chain [1] start processing
17:53:07 - cmdstanpy - INFO - Chain [1] done processing
17:53:08 - cmdstanpy - INFO - Chain [1] start processing
17:53:08 - cmdstanpy - INFO - Chain [1] done processing
17:53:08 - cmdstanpy - INFO - Chain [1] start processing
17:53:08 - cmdstanpy - INFO - Chain [1] done processing
17:53:08 - cmdstanpy - INFO - Chain [1] start processing
17:53:08 - cmdstanpy - INFO - Chain [1] done processing
17:53:08 - cmdstanpy - INFO - Chain [1] start processing
17:53:08 - cmdstanpy - INFO - Chain [1] done processing
17:53:09 - cmdstanpy - INFO - Chain [1] start processing
17:53:09 - cmdstanpy - INFO - Chain [1] done processing
17:53:09 - cmdstanpy - INFO - Chain [1] start processing
17:53:09 - cmdstanpy - INFO - Chain [1] done processing
17:53:09 - cmdstanpy - INFO - Chain [1] start processing
17:53:09 - cmdstanpy - INFO - Chain [1] done processing
17:53:09 - cmdstanpy - INFO - Chain [1] start processing
17:53:09 - cmdstanpy - INFO - Chain [1] done processing
17:53:10 - cmdstanpy - INFO - Chain [1] start processing
17:53:10 - cmdstanpy - INFO - Chain [1] done processing
17:53:10 - cmdstanpy - INFO - Chain [1] start processing
17:53:10 - cmdstanpy - INFO - Chain [1] done processing
17:53:10 - cmdstanpy - INFO - Chain [1] start processing
17:53:10 - cmdstanpy - INFO - Chain [1] done processing
17:53:10 - cmdstanpy - INFO - Chain [1] start processing
17:53:10 - cmdstanpy - INFO - Chain [1] done processing
17:53:10 - cmdstanpy - INFO - Chain [1] start processing
17:53:10 - cmdstanpy - INFO - Chain [1] done processing
17:53:11 - cmdstanpy - INFO - Chain [1] start processing
17:53:11 - cmdstanpy - INFO - Chain [1] done processing
17:53:11 - cmdstanpy - INFO - Chain [1] start processing
17:53:11 - cmdstanpy - INFO - Chain [1] done processing
17:53:11 - cmdstanpy - INFO - Chain [1] start processing
17:53:11 - cmdstanpy - INFO - Chain [1] done processing
17:53:11 - cmdstanpy - INFO - Chain [1] start processing
17:53:11 - cmdstanpy - INFO - Chain [1] done processing
17:53:12 - cmdstanpy - INFO - Chain [1] start processing
17:53:12 - cmdstanpy - INFO - Chain [1] done processing
17:53:12 - cmdstanpy - INFO - Chain [1] start processing
17:53:12 - cmdstanpy - INFO - Chain [1] done processing
17:53:12 - cmdstanpy - INFO - Chain [1] start processing
17:53:12 - cmdstanpy - INFO - Chain [1] done processing
17:53:12 - cmdstanpy - INFO - Chain [1] start processing
17:53:12 - cmdstanpy - INFO - Chain [1] done processing
17:53:12 - cmdstanpy - INFO - Chain [1] start processing
17:53:12 - cmdstanpy - INFO - Chain [1] done processing
17:53:13 - cmdstanpy - INFO - Chain [1] start processing
17:53:13 - cmdstanpy - INFO - Chain [1] done processing
17:53:13 - cmdstanpy - INFO - Chain [1] start processing
17:53:13 - cmdstanpy - INFO - Chain [1] done processing
17:53:13 - cmdstanpy - INFO - Chain [1] start processing
17:53:13 - cmdstanpy - INFO - Chain [1] done processing
17:53:13 - cmdstanpy - INFO - Chain [1] start processing
17:53:13 - cmdstanpy - INFO - Chain [1] done processing
17:53:14 - cmdstanpy - INFO - Chain [1] start processing
17:53:14 - cmdstanpy - INFO - Chain [1] done processing
17:53:14 - cmdstanpy - INFO - Chain [1] start processing
17:53:14 - cmdstanpy - INFO - Chain [1] done processing
17:53:14 - cmdstanpy - INFO - Chain [1] start processing
17:53:14 - cmdstanpy - INFO - Chain [1] done processing
17:53:14 - cmdstanpy - INFO - Chain [1] start processing
17:53:14 - cmdstanpy - INFO - Chain [1] done processing
17:53:15 - cmdstanpy - INFO - Chain [1] start processing
17:53:15 - cmdstanpy - INFO - Chain [1] done processing
17:53:15 - cmdstanpy - INFO - Chain [1] start processing
17:53:15 - cmdstanpy - INFO - Chain [1] done processing
17:53:15 - cmdstanpy - INFO - Chain [1] start processing
17:53:15 - cmdstanpy - INFO - Chain [1] done processing
17:53:15 - cmdstanpy - INFO - Chain [1] start processing
17:53:15 - cmdstanpy - INFO - Chain [1] done processing
17:53:15 - cmdstanpy - INFO - Chain [1] start processing
17:53:15 - cmdstanpy - INFO - Chain [1] done processing
17:53:16 - cmdstanpy - INFO - Chain [1] start processing
17:53:16 - cmdstanpy - INFO - Chain [1] done processing
17:53:16 - cmdstanpy - INFO - Chain [1] start processing
17:53:16 - cmdstanpy - INFO - Chain [1] done processing
17:53:16 - cmdstanpy - INFO - Chain [1] start processing
17:53:16 - cmdstanpy - INFO - Chain [1] done processing
17:53:16 - cmdstanpy - INFO - Chain [1] start processing
17:53:16 - cmdstanpy - INFO - Chain [1] done processing
17:53:16 - cmdstanpy - INFO - Chain [1] start processing
17:53:17 - cmdstanpy - INFO - Chain [1] done processing
17:53:17 - cmdstanpy - INFO - Chain [1] start processing
17:53:17 - cmdstanpy - INFO - Chain [1] done processing
17:53:17 - cmdstanpy - INFO - Chain [1] start processing
17:53:17 - cmdstanpy - INFO - Chain [1] done processing
17:53:17 - cmdstanpy - INFO - Chain [1] start processing

✅ **Parameter terbaik:** (0.05, 10.0, 0.1, 'additive')
📊 **Rata-rata MAPE terbaik:** 16.4144

In [14]:
from prophet import Prophet
import pandas as pd
import numpy as np
from itertools import product

# Fungsi MAPE
def mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# Daftar hyperparameter untuk tuning
param_grid = {
    'changepoint_prior_scale': [0.01, 0.05, 0.1, 0.5],
    'seasonality_prior_scale': [0.1, 1.0, 10.0],
    'holidays_prior_scale': [0.1, 1.0, 10.0],
    'seasonality_mode': ['additive', 'multiplicative']
}
param_combinations = list(product(*param_grid.values()))

# Data
df = df_dict['Beras Medium']
provinsi_list = df.columns[1:]  # Semua kolom kecuali 'Date'

# Variabel untuk menyimpan hasil terbaik
best_avg_mape = float('inf')
best_params = None

# Grid Search
for params in param_combinations:
    mape_list = []  # Simpan MAPE untuk setiap provinsi

    for provinsi in provinsi_list:
        # Ubah format tanggal
        df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})

        # Ambil 2 bulan terakhir sebagai validasi
        valid_size = 60  # Asumsi sekitar 30 hari per bulan
        train = df_prov.iloc[:-valid_size]  # Semua kecuali 2 bulan terakhir
        valid = df_prov.iloc[-valid_size:]  # 2 bulan terakhir

        # Pastikan validasi tidak kosong
        if valid.empty:
            continue

        try:
            # Train model
            model = Prophet(
                changepoint_prior_scale=params[0],
                seasonality_prior_scale=params[1],
                holidays_prior_scale=params[2],
                seasonality_mode=params[3]
            )
            model.fit(train)

            # Prediksi
            future = model.make_future_dataframe(periods=valid_size, freq='D')
            forecast = model.predict(future)
            predicted = forecast['yhat'].iloc[-valid_size:].values  

            # Pastikan jumlah prediksi sesuai
            if len(predicted) != len(valid):
                continue

            # Hitung MAPE
            error = mape(valid['y'].values, predicted)
            mape_list.append(error)

        except Exception:
            continue

    # Hitung rata-rata MAPE untuk kombinasi parameter ini
    if mape_list:
        avg_mape = np.mean(mape_list)

        # Simpan parameter terbaik jika rata-rata MAPE lebih kecil
        if avg_mape < best_avg_mape:
            best_avg_mape = avg_mape
            best_params = params

# Output hasil terbaik
if best_params:
    print(f"✅ **Parameter terbaik:** {best_params}")
    print(f"📊 **Rata-rata MAPE terbaik:** {best_avg_mape:.4f}")
else:
    print("⚠️ Tidak ada parameter yang menghasilkan model valid!")

18:09:18 - cmdstanpy - INFO - Chain [1] start processing
18:09:18 - cmdstanpy - INFO - Chain [1] done processing
18:09:18 - cmdstanpy - INFO - Chain [1] start processing
18:09:18 - cmdstanpy - INFO - Chain [1] done processing
18:09:19 - cmdstanpy - INFO - Chain [1] start processing
18:09:19 - cmdstanpy - INFO - Chain [1] done processing
18:09:19 - cmdstanpy - INFO - Chain [1] start processing
18:09:19 - cmdstanpy - INFO - Chain [1] done processing
18:09:19 - cmdstanpy - INFO - Chain [1] start processing
18:09:19 - cmdstanpy - INFO - Chain [1] done processing
18:09:19 - cmdstanpy - INFO - Chain [1] start processing
18:09:20 - cmdstanpy - INFO - Chain [1] done processing
18:09:20 - cmdstanpy - INFO - Chain [1] start processing
18:09:20 - cmdstanpy - INFO - Chain [1] done processing
18:09:20 - cmdstanpy - INFO - Chain [1] start processing
18:09:20 - cmdstanpy - INFO - Chain [1] done processing
18:09:20 - cmdstanpy - INFO - Chain [1] start processing
18:09:20 - cmdstanpy - INFO - Chain [1] done processing
18:09:21 - cmdstanpy - INFO - Chain [1] start processing
18:09:21 - cmdstanpy - INFO - Chain [1] done processing
18:09:21 - cmdstanpy - INFO - Chain [1] start processing
18:09:21 - cmdstanpy - INFO - Chain [1] done processing
18:09:21 - cmdstanpy - INFO - Chain [1] start processing
18:09:21 - cmdstanpy - INFO - Chain [1] done processing
18:09:21 - cmdstanpy - INFO - Chain [1] start processing
18:09:22 - cmdstanpy - INFO - Chain [1] done processing
18:09:22 - cmdstanpy - INFO - Chain [1] start processing
18:09:22 - cmdstanpy - INFO - Chain [1] done processing
18:09:22 - cmdstanpy - INFO - Chain [1] start processing
18:09:22 - cmdstanpy - INFO - Chain [1] done processing
18:09:22 - cmdstanpy - INFO - Chain [1] start processing
18:09:22 - cmdstanpy - INFO - Chain [1] done processing
18:09:23 - cmdstanpy - INFO - Chain [1] start processing
18:09:23 - cmdstanpy - INFO - Chain [1] done processing
18:09:23 - cmdstanpy - INFO - Chain [1] start processing
18:09:23 - cmdstanpy - INFO - Chain [1] done processing
18:09:23 - cmdstanpy - INFO - Chain [1] start processing
18:09:23 - cmdstanpy - INFO - Chain [1] done processing
18:09:23 - cmdstanpy - INFO - Chain [1] start processing
18:09:24 - cmdstanpy - INFO - Chain [1] done processing
18:09:24 - cmdstanpy - INFO - Chain [1] start processing
18:09:24 - cmdstanpy - INFO - Chain [1] done processing
18:09:24 - cmdstanpy - INFO - Chain [1] start processing
18:09:24 - cmdstanpy - INFO - Chain [1] done processing
18:09:24 - cmdstanpy - INFO - Chain [1] start processing
18:09:24 - cmdstanpy - INFO - Chain [1] done processing
18:09:25 - cmdstanpy - INFO - Chain [1] start processing
18:09:25 - cmdstanpy - INFO - Chain [1] done processing
18:09:25 - cmdstanpy - INFO - Chain [1] start processing
18:09:25 - cmdstanpy - INFO - Chain [1] done processing
18:09:25 - cmdstanpy - INFO - Chain [1] start processing
18:09:25 - cmdstanpy - INFO - Chain [1] done processing
18:09:25 - cmdstanpy - INFO - Chain [1] start processing
18:09:25 - cmdstanpy - INFO - Chain [1] done processing
18:09:26 - cmdstanpy - INFO - Chain [1] start processing
18:09:26 - cmdstanpy - INFO - Chain [1] done processing
18:09:26 - cmdstanpy - INFO - Chain [1] start processing
18:09:26 - cmdstanpy - INFO - Chain [1] done processing
18:09:26 - cmdstanpy - INFO - Chain [1] start processing
18:09:26 - cmdstanpy - INFO - Chain [1] done processing
18:09:26 - cmdstanpy - INFO - Chain [1] start processing
18:09:26 - cmdstanpy - INFO - Chain [1] done processing
18:09:26 - cmdstanpy - INFO - Chain [1] start processing
18:09:27 - cmdstanpy - INFO - Chain [1] done processing
18:09:27 - cmdstanpy - INFO - Chain [1] start processing
18:09:27 - cmdstanpy - INFO - Chain [1] done processing
18:09:27 - cmdstanpy - INFO - Chain [1] start processing
18:09:27 - cmdstanpy - INFO - Chain [1] done processing
18:09:27 - cmdstanpy - INFO - Chain [1] start processing
18:09:28 - cmdstanpy - INFO - Chain [1] done processing
18:09:28 - cmdstanpy - INFO - Chain [1] start processing
18:09:28 - cmdstanpy - INFO - Chain [1] done processing
18:09:28 - cmdstanpy - INFO - Chain [1] start processing
18:09:28 - cmdstanpy - INFO - Chain [1] done processing
18:09:28 - cmdstanpy - INFO - Chain [1] start processing
18:09:28 - cmdstanpy - INFO - Chain [1] done processing
18:09:28 - cmdstanpy - INFO - Chain [1] start processing
18:09:28 - cmdstanpy - INFO - Chain [1] done processing
18:09:29 - cmdstanpy - INFO - Chain [1] start processing
18:09:29 - cmdstanpy - INFO - Chain [1] done processing
18:09:29 - cmdstanpy - INFO - Chain [1] start processing
18:09:29 - cmdstanpy - INFO - Chain [1] done processing
18:09:29 - cmdstanpy - INFO - Chain [1] start processing
18:09:29 - cmdstanpy - INFO - Chain [1] done processing
18:09:29 - cmdstanpy - INFO - Chain [1] start processing
18:09:30 - cmdstanpy - INFO - Chain [1] done processing
18:09:30 - cmdstanpy - INFO - Chain [1] start processing
18:09:30 - cmdstanpy - INFO - Chain [1] done processing
18:09:30 - cmdstanpy - INFO - Chain [1] start processing
18:09:30 - cmdstanpy - INFO - Chain [1] done processing
18:09:30 - cmdstanpy - INFO - Chain [1] start processing
18:09:30 - cmdstanpy - INFO - Chain [1] done processing
18:09:31 - cmdstanpy - INFO - Chain [1] start processing
18:09:31 - cmdstanpy - INFO - Chain [1] done processing
18:09:31 - cmdstanpy - INFO - Chain [1] start processing
18:09:31 - cmdstanpy - INFO - Chain [1] done processing
18:09:31 - cmdstanpy - INFO - Chain [1] start processing
18:09:31 - cmdstanpy - INFO - Chain [1] done processing
18:09:31 - cmdstanpy - INFO - Chain [1] start processing
18:09:31 - cmdstanpy - INFO - Chain [1] done processing
18:09:32 - cmdstanpy - INFO - Chain [1] start processing
18:09:32 - cmdstanpy - INFO - Chain [1] done processing
18:09:32 - cmdstanpy - INFO - Chain [1] start processing
18:09:32 - cmdstanpy - INFO - Chain [1] done processing
18:09:32 - cmdstanpy - INFO - Chain [1] start processing
18:09:32 - cmdstanpy - INFO - Chain [1] done processing
18:09:32 - cmdstanpy - INFO - Chain [1] start processing
18:09:33 - cmdstanpy - INFO - Chain [1] done processing
18:09:33 - cmdstanpy - INFO - Chain [1] start processing
18:09:33 - cmdstanpy - INFO - Chain [1] done processing
18:09:33 - cmdstanpy - INFO - Chain [1] start processing
18:09:33 - cmdstanpy - INFO - Chain [1] done processing
18:09:33 - cmdstanpy - INFO - Chain [1] start processing
18:09:34 - cmdstanpy - INFO - Chain [1] done processing
18:09:34 - cmdstanpy - INFO - Chain [1] start processing
18:09:34 - cmdstanpy - INFO - Chain [1] done processing
18:09:34 - cmdstanpy - INFO - Chain [1] start processing
18:09:34 - cmdstanpy - INFO - Chain [1] done processing
18:09:34 - cmdstanpy - INFO - Chain [1] start processing
18:09:34 - cmdstanpy - INFO - Chain [1] done processing
18:09:35 - cmdstanpy - INFO - Chain [1] start processing
18:09:35 - cmdstanpy - INFO - Chain [1] done processing
18:09:35 - cmdstanpy - INFO - Chain [1] start processing
18:09:35 - cmdstanpy - INFO - Chain [1] done processing
18:09:35 - cmdstanpy - INFO - Chain [1] start processing
18:09:35 - cmdstanpy - INFO - Chain [1] done processing
18:09:35 - cmdstanpy - INFO - Chain [1] start processing
18:09:35 - cmdstanpy - INFO - Chain [1] done processing
18:09:36 - cmdstanpy - INFO - Chain [1] start processing
18:09:36 - cmdstanpy - INFO - Chain [1] done processing
18:09:36 - cmdstanpy - INFO - Chain [1] start processing
18:09:36 - cmdstanpy - INFO - Chain [1] done processing
18:09:36 - cmdstanpy - INFO - Chain [1] start processing
18:09:36 - cmdstanpy - INFO - Chain [1] done processing
18:09:36 - cmdstanpy - INFO - Chain [1] start processing
18:09:37 - cmdstanpy - INFO - Chain [1] done processing
18:09:37 - cmdstanpy - INFO - Chain [1] start processing
18:09:37 - cmdstanpy - INFO - Chain [1] done processing
18:09:37 - cmdstanpy - INFO - Chain [1] start processing
18:09:37 - cmdstanpy - INFO - Chain [1] done processing
18:09:37 - cmdstanpy - INFO - Chain [1] start processing
18:09:38 - cmdstanpy - INFO - Chain [1] done processing
18:09:38 - cmdstanpy - INFO - Chain [1] start processing
18:09:38 - cmdstanpy - INFO - Chain [1] done processing
18:09:38 - cmdstanpy - INFO - Chain [1] start processing
18:09:38 - cmdstanpy - INFO - Chain [1] done processing
18:09:38 - cmdstanpy - INFO - Chain [1] start processing
18:09:38 - cmdstanpy - INFO - Chain [1] done processing
18:09:39 - cmdstanpy - INFO - Chain [1] start processing
18:09:39 - cmdstanpy - INFO - Chain [1] done processing
18:09:39 - cmdstanpy - INFO - Chain [1] start processing
18:09:39 - cmdstanpy - INFO - Chain [1] done processing
18:09:39 - cmdstanpy - INFO - Chain [1] start processing
18:09:39 - cmdstanpy - INFO - Chain [1] done processing
18:09:39 - cmdstanpy - INFO - Chain [1] start processing
18:09:39 - cmdstanpy - INFO - Chain [1] done processing
18:09:40 - cmdstanpy - INFO - Chain [1] start processing
18:09:40 - cmdstanpy - INFO - Chain [1] done processing
18:09:40 - cmdstanpy - INFO - Chain [1] start processing
18:09:40 - cmdstanpy - INFO - Chain [1] done processing
18:09:40 - cmdstanpy - INFO - Chain [1] start processing
18:09:40 - cmdstanpy - INFO - Chain [1] done processing
18:09:40 - cmdstanpy - INFO - Chain [1] start processing
18:09:41 - cmdstanpy - INFO - Chain [1] done processing
18:09:41 - cmdstanpy - INFO - Chain [1] start processing
18:09:41 - cmdstanpy - INFO - Chain [1] done processing
18:09:41 - cmdstanpy - INFO - Chain [1] start processing
18:09:41 - cmdstanpy - INFO - Chain [1] done processing
18:09:41 - cmdstanpy - INFO - Chain [1] start processing
18:09:41 - cmdstanpy - INFO - Chain [1] done processing
18:09:42 - cmdstanpy - INFO - Chain [1] start processing
18:09:42 - cmdstanpy - INFO - Chain [1] done processing
18:09:42 - cmdstanpy - INFO - Chain [1] start processing
18:09:42 - cmdstanpy - INFO - Chain [1] done processing
18:09:42 - cmdstanpy - INFO - Chain [1] start processing
18:09:42 - cmdstanpy - INFO - Chain [1] done processing
18:09:42 - cmdstanpy - INFO - Chain [1] start processing
18:09:42 - cmdstanpy - INFO - Chain [1] done processing
18:09:43 - cmdstanpy - INFO - Chain [1] start processing
18:09:43 - cmdstanpy - INFO - Chain [1] done processing
18:09:43 - cmdstanpy - INFO - Chain [1] start processing
18:09:43 - cmdstanpy - INFO - Chain [1] done processing
18:09:43 - cmdstanpy - INFO - Chain [1] start processing
18:09:43 - cmdstanpy - INFO - Chain [1] done processing
18:09:43 - cmdstanpy - INFO - Chain [1] start processing
18:09:43 - cmdstanpy - INFO - Chain [1] done processing
18:09:44 - cmdstanpy - INFO - Chain [1] start processing
18:09:44 - cmdstanpy - INFO - Chain [1] done processing
18:09:44 - cmdstanpy - INFO - Chain [1] start processing
18:09:44 - cmdstanpy - INFO - Chain [1] done processing
18:09:44 - cmdstanpy - INFO - Chain [1] start processing
18:09:44 - cmdstanpy - INFO - Chain [1] done processing
18:09:44 - cmdstanpy - INFO - Chain [1] start processing
18:09:44 - cmdstanpy - INFO - Chain [1] done processing
18:09:45 - cmdstanpy - INFO - Chain [1] start processing
18:09:45 - cmdstanpy - INFO - Chain [1] done processing
18:09:45 - cmdstanpy - INFO - Chain [1] start processing
18:09:45 - cmdstanpy - INFO - Chain [1] done processing
18:09:45 - cmdstanpy - INFO - Chain [1] start processing
18:09:45 - cmdstanpy - INFO - Chain [1] done processing
18:09:45 - cmdstanpy - INFO - Chain [1] start processing
18:09:45 - cmdstanpy - INFO - Chain [1] done processing
18:09:46 - cmdstanpy - INFO - Chain [1] start processing
18:09:46 - cmdstanpy - INFO - Chain [1] done processing
18:09:46 - cmdstanpy - INFO - Chain [1] start processing
18:09:46 - cmdstanpy - INFO - Chain [1] done processing
18:09:46 - cmdstanpy - INFO - Chain [1] start processing
18:09:46 - cmdstanpy - INFO - Chain [1] done processing
18:09:47 - cmdstanpy - INFO - Chain [1] start processing
18:09:47 - cmdstanpy - INFO - Chain [1] done processing
18:09:47 - cmdstanpy - INFO - Chain [1] start processing
18:09:47 - cmdstanpy - INFO - Chain [1] done processing
18:09:47 - cmdstanpy - INFO - Chain [1] start processing
18:09:47 - cmdstanpy - INFO - Chain [1] done processing
18:09:47 - cmdstanpy - INFO - Chain [1] start processing
18:09:47 - cmdstanpy - INFO - Chain [1] done processing
18:09:48 - cmdstanpy - INFO - Chain [1] start processing
18:09:48 - cmdstanpy - INFO - Chain [1] done processing
18:09:48 - cmdstanpy - INFO - Chain [1] start processing
18:09:48 - cmdstanpy - INFO - Chain [1] done processing
18:09:48 - cmdstanpy - INFO - Chain [1] start processing
18:09:48 - cmdstanpy - INFO - Chain [1] done processing
18:09:48 - cmdstanpy - INFO - Chain [1] start processing
18:09:48 - cmdstanpy - INFO - Chain [1] done processing
18:09:49 - cmdstanpy - INFO - Chain [1] start processing
18:09:49 - cmdstanpy - INFO - Chain [1] done processing
18:09:49 - cmdstanpy - INFO - Chain [1] start processing
18:09:49 - cmdstanpy - INFO - Chain [1] done processing
18:09:49 - cmdstanpy - INFO - Chain [1] start processing
18:09:49 - cmdstanpy - INFO - Chain [1] done processing
18:09:49 - cmdstanpy - INFO - Chain [1] start processing
18:09:50 - cmdstanpy - INFO - Chain [1] done processing
18:09:50 - cmdstanpy - INFO - Chain [1] start processing
18:09:50 - cmdstanpy - INFO - Chain [1] done processing
18:09:50 - cmdstanpy - INFO - Chain [1] start processing
18:09:50 - cmdstanpy - INFO - Chain [1] done processing
18:09:50 - cmdstanpy - INFO - Chain [1] start processing
18:09:50 - cmdstanpy - INFO - Chain [1] done processing
18:09:51 - cmdstanpy - INFO - Chain [1] start processing
18:09:51 - cmdstanpy - INFO - Chain [1] done processing
18:09:51 - cmdstanpy - INFO - Chain [1] start processing
18:09:51 - cmdstanpy - INFO - Chain [1] done processing
18:09:51 - cmdstanpy - INFO - Chain [1] start processing
18:09:51 - cmdstanpy - INFO - Chain [1] done processing
18:09:51 - cmdstanpy - INFO - Chain [1] start processing
18:09:51 - cmdstanpy - INFO - Chain [1] done processing
18:09:52 - cmdstanpy - INFO - Chain [1] start processing
18:09:52 - cmdstanpy - INFO - Chain [1] done processing
18:09:52 - cmdstanpy - INFO - Chain [1] start processing
18:09:52 - cmdstanpy - INFO - Chain [1] done processing
18:09:52 - cmdstanpy - INFO - Chain [1] start processing
18:09:52 - cmdstanpy - INFO - Chain [1] done processing
18:09:52 - cmdstanpy - INFO - Chain [1] start processing
18:09:53 - cmdstanpy - INFO - Chain [1] done processing
18:09:53 - cmdstanpy - INFO - Chain [1] start processing
18:09:53 - cmdstanpy - INFO - Chain [1] done processing
18:09:53 - cmdstanpy - INFO - Chain [1] start processing
18:09:53 - cmdstanpy - INFO - Chain [1] done processing
18:09:53 - cmdstanpy - INFO - Chain [1] start processing
18:09:53 - cmdstanpy - INFO - Chain [1] done processing
18:09:53 - cmdstanpy - INFO - Chain [1] start processing
18:09:54 - cmdstanpy - INFO - Chain [1] done processing
18:09:54 - cmdstanpy - INFO - Chain [1] start processing
18:09:54 - cmdstanpy - INFO - Chain [1] done processing
18:09:54 - cmdstanpy - INFO - Chain [1] start processing
18:09:54 - cmdstanpy - INFO - Chain [1] done processing
18:09:54 - cmdstanpy - INFO - Chain [1] start processing
18:09:54 - cmdstanpy - INFO - Chain [1] done processing
18:09:55 - cmdstanpy - INFO - Chain [1] start processing
18:09:55 - cmdstanpy - INFO - Chain [1] done processing
18:09:55 - cmdstanpy - INFO - Chain [1] start processing
18:09:55 - cmdstanpy - INFO - Chain [1] done processing
18:09:55 - cmdstanpy - INFO - Chain [1] start processing
18:09:55 - cmdstanpy - INFO - Chain [1] done processing
18:09:56 - cmdstanpy - INFO - Chain [1] start processing
18:09:56 - cmdstanpy - INFO - Chain [1] done processing
18:09:56 - cmdstanpy - INFO - Chain [1] start processing
18:09:56 - cmdstanpy - INFO - Chain [1] done processing
18:09:56 - cmdstanpy - INFO - Chain [1] start processing
18:09:56 - cmdstanpy - INFO - Chain [1] done processing
18:09:56 - cmdstanpy - INFO - Chain [1] start processing
18:09:56 - cmdstanpy - INFO - Chain [1] done processing
18:09:57 - cmdstanpy - INFO - Chain [1] start processing
18:09:57 - cmdstanpy - INFO - Chain [1] done processing
18:09:57 - cmdstanpy - INFO - Chain [1] start processing
18:09:57 - cmdstanpy - INFO - Chain [1] done processing
18:09:57 - cmdstanpy - INFO - Chain [1] start processing
18:09:57 - cmdstanpy - INFO - Chain [1] done processing
18:09:57 - cmdstanpy - INFO - Chain [1] start processing
18:09:57 - cmdstanpy - INFO - Chain [1] done processing
18:09:58 - cmdstanpy - INFO - Chain [1] start processing
18:09:58 - cmdstanpy - INFO - Chain [1] done processing
18:09:58 - cmdstanpy - INFO - Chain [1] start processing
18:09:58 - cmdstanpy - INFO - Chain [1] done processing
18:09:58 - cmdstanpy - INFO - Chain [1] start processing
18:09:58 - cmdstanpy - INFO - Chain [1] done processing
18:09:58 - cmdstanpy - INFO - Chain [1] start processing
18:09:58 - cmdstanpy - INFO - Chain [1] done processing
18:09:59 - cmdstanpy - INFO - Chain [1] start processing
18:09:59 - cmdstanpy - INFO - Chain [1] done processing
18:09:59 - cmdstanpy - INFO - Chain [1] start processing
18:09:59 - cmdstanpy - INFO - Chain [1] done processing
18:09:59 - cmdstanpy - INFO - Chain [1] start processing
18:09:59 - cmdstanpy - INFO - Chain [1] done processing
18:10:00 - cmdstanpy - INFO - Chain [1] start processing
18:10:00 - cmdstanpy - INFO - Chain [1] done processing
18:10:00 - cmdstanpy - INFO - Chain [1] start processing
18:10:00 - cmdstanpy - INFO - Chain [1] done processing
18:10:00 - cmdstanpy - INFO - Chain [1] start processing
18:10:00 - cmdstanpy - INFO - Chain [1] done processing
18:10:00 - cmdstanpy - INFO - Chain [1] start processing
18:10:00 - cmdstanpy - INFO - Chain [1] done processing
18:10:01 - cmdstanpy - INFO - Chain [1] start processing
18:10:01 - cmdstanpy - INFO - Chain [1] done processing
18:10:01 - cmdstanpy - INFO - Chain [1] start processing
18:10:01 - cmdstanpy - INFO - Chain [1] done processing
18:10:01 - cmdstanpy - INFO - Chain [1] start processing
18:10:01 - cmdstanpy - INFO - Chain [1] done processing
18:10:01 - cmdstanpy - INFO - Chain [1] start processing
18:10:01 - cmdstanpy - INFO - Chain [1] done processing
18:10:02 - cmdstanpy - INFO - Chain [1] start processing
18:10:02 - cmdstanpy - INFO - Chain [1] done processing
18:10:02 - cmdstanpy - INFO - Chain [1] start processing
18:10:02 - cmdstanpy - INFO - Chain [1] done processing
18:10:02 - cmdstanpy - INFO - Chain [1] start processing
18:10:02 - cmdstanpy - INFO - Chain [1] done processing
18:10:02 - cmdstanpy - INFO - Chain [1] start processing
18:10:02 - cmdstanpy - INFO - Chain [1] done processing
18:10:03 - cmdstanpy - INFO - Chain [1] start processing
18:10:03 - cmdstanpy - INFO - Chain [1] done processing
18:10:03 - cmdstanpy - INFO - Chain [1] start processing
18:10:03 - cmdstanpy - INFO - Chain [1] done processing
18:10:03 - cmdstanpy - INFO - Chain [1] start processing
18:10:03 - cmdstanpy - INFO - Chain [1] done processing
18:10:03 - cmdstanpy - INFO - Chain [1] start processing
18:10:03 - cmdstanpy - INFO - Chain [1] done processing
18:10:04 - cmdstanpy - INFO - Chain [1] start processing
18:10:04 - cmdstanpy - INFO - Chain [1] done processing
18:10:04 - cmdstanpy - INFO - Chain [1] start processing
18:10:04 - cmdstanpy - INFO - Chain [1] done processing
18:10:04 - cmdstanpy - INFO - Chain [1] start processing
18:10:04 - cmdstanpy - INFO - Chain [1] done processing
18:10:04 - cmdstanpy - INFO - Chain [1] start processing
18:10:04 - cmdstanpy - INFO - Chain [1] done processing
18:10:05 - cmdstanpy - INFO - Chain [1] start processing
18:10:05 - cmdstanpy - INFO - Chain [1] done processing
18:10:05 - cmdstanpy - INFO - Chain [1] start processing
18:10:05 - cmdstanpy - INFO - Chain [1] done processing
18:10:05 - cmdstanpy - INFO - Chain [1] start processing
18:10:05 - cmdstanpy - INFO - Chain [1] done processing
18:10:05 - cmdstanpy - INFO - Chain [1] start processing
18:10:05 - cmdstanpy - INFO - Chain [1] done processing
18:10:06 - cmdstanpy - INFO - Chain [1] start processing

✅ **Parameter terbaik:** (0.01, 0.1, 0.1, 'additive')
📊 **Rata-rata MAPE terbaik:** 2.7487

In [17]:
from prophet import Prophet
import pandas as pd
import numpy as np
from itertools import product

# Fungsi MAPE
def mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# Daftar hyperparameter untuk tuning (dengan opsi seasonality on/off)
param_grid = {
    'changepoint_prior_scale': [0.01, 0.05, 0.1, 0.5],
    'seasonality_prior_scale': [0.1, 1.0, 10.0],
    'holidays_prior_scale': [0.1, 1.0, 10.0],
    'seasonality_mode': ['additive', 'multiplicative'],
    'weekly_seasonality': [True, False],
    'daily_seasonality': [True, False],
    'yearly_seasonality': [True, False]
}
param_combinations = list(product(*param_grid.values()))

# Data
df = df_dict['Bawang Merah']
provinsi_list = df.columns[1:]  # Semua kolom kecuali 'Date'

# Variabel untuk menyimpan hasil terbaik dan baseline
best_avg_mape = float('inf')
best_params = None
baseline_mape_list = []

# Grid Search
for params in param_combinations:
    mape_list = []  # Simpan MAPE untuk setiap provinsi

    for provinsi in provinsi_list:
        # Ubah format tanggal
        df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})

        # Ambil 2 bulan terakhir sebagai validasi
        valid_size = 60  # Asumsi sekitar 30 hari per bulan
        train = df_prov.iloc[:-valid_size]  # Semua kecuali 2 bulan terakhir
        valid = df_prov.iloc[-valid_size:]  # 2 bulan terakhir

        # Pastikan validasi tidak kosong
        if valid.empty:
            continue

        try:
            # Train model dengan parameter tuning
            model = Prophet(
                changepoint_prior_scale=params[0],
                seasonality_prior_scale=params[1],
                holidays_prior_scale=params[2],
                seasonality_mode=params[3],
                weekly_seasonality=params[4],
                daily_seasonality=params[5],
                yearly_seasonality=params[6]
            )
            model.fit(train)

            # Prediksi
            future = model.make_future_dataframe(periods=valid_size, freq='D')
            forecast = model.predict(future)
            predicted = forecast['yhat'].iloc[-valid_size:].values  

            # Pastikan jumlah prediksi sesuai
            if len(predicted) != len(valid):
                continue

            # Hitung MAPE
            error = mape(valid['y'].values, predicted)
            mape_list.append(error)

        except Exception:
            continue

    # Hitung rata-rata MAPE untuk kombinasi parameter ini
    if mape_list:
        avg_mape = np.mean(mape_list)

        # Simpan parameter terbaik jika rata-rata MAPE lebih kecil
        if avg_mape < best_avg_mape:
            best_avg_mape = avg_mape
            best_params = params

# Baseline: Prophet Default
for provinsi in provinsi_list:
    df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})

    valid_size = 60
    train = df_prov.iloc[:-valid_size]
    valid = df_prov.iloc[-valid_size:]

    if valid.empty:
        continue

    try:
        # Model Prophet Default
        default_model = Prophet()
        default_model.fit(train)

        # Prediksi
        future = default_model.make_future_dataframe(periods=valid_size, freq='D')
        forecast = default_model.predict(future)
        predicted = forecast['yhat'].iloc[-valid_size:].values  

        if len(predicted) != len(valid):
            continue

        # Hitung MAPE
        error = mape(valid['y'].values, predicted)
        baseline_mape_list.append(error)

    except Exception:
        continue

# Hasil perbandingan
if best_params and baseline_mape_list:
    avg_baseline_mape = np.mean(baseline_mape_list)
    
    print(f"✅ **Parameter terbaik:** {best_params}")
    print(f"📊 **Rata-rata MAPE terbaik:** {best_avg_mape:.4f}")
    print(f"🔹 **Rata-rata MAPE Prophet Default:** {avg_baseline_mape:.4f}")
    
    improvement = ((avg_baseline_mape - best_avg_mape) / avg_baseline_mape) * 100
    print(f"📈 **Peningkatan akurasi dibanding default:** {improvement:.2f}%")
else:
    print("⚠️ Tidak ada parameter yang menghasilkan model valid!")

18:34:22 - cmdstanpy - INFO - Chain [1] start processing
18:34:22 - cmdstanpy - INFO - Chain [1] done processing
18:34:22 - cmdstanpy - INFO - Chain [1] start processing
18:34:22 - cmdstanpy - INFO - Chain [1] done processing
18:34:22 - cmdstanpy - INFO - Chain [1] start processing
18:34:22 - cmdstanpy - INFO - Chain [1] done processing
18:34:22 - cmdstanpy - INFO - Chain [1] start processing
18:34:22 - cmdstanpy - INFO - Chain [1] done processing
18:34:23 - cmdstanpy - INFO - Chain [1] start processing
18:34:23 - cmdstanpy - INFO - Chain [1] done processing
18:34:23 - cmdstanpy - INFO - Chain [1] start processing
18:34:23 - cmdstanpy - INFO - Chain [1] done processing
18:34:23 - cmdstanpy - INFO - Chain [1] start processing
18:34:23 - cmdstanpy - INFO - Chain [1] done processing
18:34:23 - cmdstanpy - INFO - Chain [1] start processing
18:34:23 - cmdstanpy - INFO - Chain [1] done processing
18:34:24 - cmdstanpy - INFO - Chain [1] start processing
18:34:24 - cmdstanpy - INFO - Chain [1] done processing
18:34:24 - cmdstanpy - INFO - Chain [1] start processing
18:34:24 - cmdstanpy - INFO - Chain [1] done processing
18:34:24 - cmdstanpy - INFO - Chain [1] start processing
18:34:24 - cmdstanpy - INFO - Chain [1] done processing
18:34:24 - cmdstanpy - INFO - Chain [1] start processing
18:34:24 - cmdstanpy - INFO - Chain [1] done processing
18:34:25 - cmdstanpy - INFO - Chain [1] start processing
18:34:25 - cmdstanpy - INFO - Chain [1] done processing
18:34:25 - cmdstanpy - INFO - Chain [1] start processing
18:34:25 - cmdstanpy - INFO - Chain [1] done processing
18:34:25 - cmdstanpy - INFO - Chain [1] start processing
18:34:25 - cmdstanpy - INFO - Chain [1] done processing
18:34:25 - cmdstanpy - INFO - Chain [1] start processing
18:34:26 - cmdstanpy - INFO - Chain [1] done processing
18:34:26 - cmdstanpy - INFO - Chain [1] start processing
18:34:26 - cmdstanpy - INFO - Chain [1] done processing
18:34:26 - cmdstanpy - INFO - Chain [1] start processing
18:34:26 - cmdstanpy - INFO - Chain [1] done processing
18:34:26 - cmdstanpy - INFO - Chain [1] start processing
18:34:26 - cmdstanpy - INFO - Chain [1] done processing
18:34:26 - cmdstanpy - INFO - Chain [1] start processing
18:34:27 - cmdstanpy - INFO - Chain [1] done processing
18:34:27 - cmdstanpy - INFO - Chain [1] start processing
18:34:27 - cmdstanpy - INFO - Chain [1] done processing
18:34:27 - cmdstanpy - INFO - Chain [1] start processing
18:34:27 - cmdstanpy - INFO - Chain [1] done processing
18:34:27 - cmdstanpy - INFO - Chain [1] start processing
18:34:27 - cmdstanpy - INFO - Chain [1] done processing
18:34:27 - cmdstanpy - INFO - Chain [1] start processing
18:34:28 - cmdstanpy - INFO - Chain [1] done processing
18:34:28 - cmdstanpy - INFO - Chain [1] start processing
18:34:28 - cmdstanpy - INFO - Chain [1] done processing
18:34:28 - cmdstanpy - INFO - Chain [1] start processing
18:34:28 - cmdstanpy - INFO - Chain [1] done processing
18:34:28 - cmdstanpy - INFO - Chain [1] start processing
18:34:28 - cmdstanpy - INFO - Chain [1] done processing
18:34:29 - cmdstanpy - INFO - Chain [1] start processing
18:34:29 - cmdstanpy - INFO - Chain [1] done processing
18:34:29 - cmdstanpy - INFO - Chain [1] start processing
18:34:29 - cmdstanpy - INFO - Chain [1] done processing
18:34:29 - cmdstanpy - INFO - Chain [1] start processing
18:34:29 - cmdstanpy - INFO - Chain [1] done processing
18:34:29 - cmdstanpy - INFO - Chain [1] start processing
18:34:29 - cmdstanpy - INFO - Chain [1] done processing
18:34:30 - cmdstanpy - INFO - Chain [1] start processing
18:34:30 - cmdstanpy - INFO - Chain [1] done processing
18:34:30 - cmdstanpy - INFO - Chain [1] start processing
18:34:30 - cmdstanpy - INFO - Chain [1] done processing
18:34:30 - cmdstanpy - INFO - Chain [1] start processing
18:34:30 - cmdstanpy - INFO - Chain [1] done processing
18:34:30 - cmdstanpy - INFO - Chain [1] start processing
18:34:30 - cmdstanpy - INFO - Chain [1] done processing
18:34:30 - cmdstanpy - INFO - Chain [1] start processing
18:34:30 - cmdstanpy - INFO - Chain [1] done processing
18:34:31 - cmdstanpy - INFO - Chain [1] start processing
18:34:31 - cmdstanpy - INFO - Chain [1] done processing
18:34:31 - cmdstanpy - INFO - Chain [1] start processing
18:34:31 - cmdstanpy - INFO - Chain [1] done processing
18:34:31 - cmdstanpy - INFO - Chain [1] start processing
18:34:31 - cmdstanpy - INFO - Chain [1] done processing
18:34:31 - cmdstanpy - INFO - Chain [1] start processing
18:34:31 - cmdstanpy - INFO - Chain [1] done processing
18:34:31 - cmdstanpy - INFO - Chain [1] start processing
18:34:31 - cmdstanpy - INFO - Chain [1] done processing
18:34:32 - cmdstanpy - INFO - Chain [1] start processing
18:34:32 - cmdstanpy - INFO - Chain [1] done processing
18:34:32 - cmdstanpy - INFO - Chain [1] start processing
18:34:32 - cmdstanpy - INFO - Chain [1] done processing
18:34:32 - cmdstanpy - INFO - Chain [1] start processing
18:34:32 - cmdstanpy - INFO - Chain [1] done processing
18:34:32 - cmdstanpy - INFO - Chain [1] start processing
18:34:32 - cmdstanpy - INFO - Chain [1] done processing
18:34:32 - cmdstanpy - INFO - Chain [1] start processing
18:34:32 - cmdstanpy - INFO - Chain [1] done processing
18:34:33 - cmdstanpy - INFO - Chain [1] start processing
18:34:33 - cmdstanpy - INFO - Chain [1] done processing
18:34:33 - cmdstanpy - INFO - Chain [1] start processing
18:34:33 - cmdstanpy - INFO - Chain [1] done processing
18:34:33 - cmdstanpy - INFO - Chain [1] start processing
18:34:33 - cmdstanpy - INFO - Chain [1] done processing
18:34:33 - cmdstanpy - INFO - Chain [1] start processing
18:34:33 - cmdstanpy - INFO - Chain [1] done processing
18:34:33 - cmdstanpy - INFO - Chain [1] start processing
18:34:33 - cmdstanpy - INFO - Chain [1] done processing
18:34:34 - cmdstanpy - INFO - Chain [1] start processing
18:34:34 - cmdstanpy - INFO - Chain [1] done processing
18:34:34 - cmdstanpy - INFO - Chain [1] start processing
18:34:34 - cmdstanpy - INFO - Chain [1] done processing
18:34:34 - cmdstanpy - INFO - Chain [1] start processing
18:34:34 - cmdstanpy - INFO - Chain [1] done processing
18:34:34 - cmdstanpy - INFO - Chain [1] start processing
18:34:34 - cmdstanpy - INFO - Chain [1] done processing
18:34:34 - cmdstanpy - INFO - Chain [1] start processing
18:34:34 - cmdstanpy - INFO - Chain [1] done processing
18:34:35 - cmdstanpy - INFO - Chain [1] start processing
18:34:35 - cmdstanpy - INFO - Chain [1] done processing
18:34:35 - cmdstanpy - INFO - Chain [1] start processing
18:34:35 - cmdstanpy - INFO - Chain [1] done processing
18:34:35 - cmdstanpy - INFO - Chain [1] start processing
18:34:35 - cmdstanpy - INFO - Chain [1] done processing
18:34:35 - cmdstanpy - INFO - Chain [1] start processing
18:34:35 - cmdstanpy - INFO - Chain [1] done processing
18:34:35 - cmdstanpy - INFO - Chain [1] start processing
18:34:35 - cmdstanpy - INFO - Chain [1] done processing
18:34:36 - cmdstanpy - INFO - Chain [1] start processing
18:34:36 - cmdstanpy - INFO - Chain [1] done processing
18:34:36 - cmdstanpy - INFO - Chain [1] start processing
18:34:36 - cmdstanpy - INFO - Chain [1] done processing
18:34:36 - cmdstanpy - INFO - Chain [1] start processing
18:34:36 - cmdstanpy - INFO - Chain [1] done processing
18:34:36 - cmdstanpy - INFO - Chain [1] start processing
18:34:36 - cmdstanpy - INFO - Chain [1] done processing
18:34:36 - cmdstanpy - INFO - Chain [1] start processing
18:34:36 - cmdstanpy - INFO - Chain [1] done processing
18:34:37 - cmdstanpy - INFO - Chain [1] start processing
18:34:37 - cmdstanpy - INFO - Chain [1] done processing
18:34:37 - cmdstanpy - INFO - Chain [1] start processing
18:34:37 - cmdstanpy - INFO - Chain [1] done processing
18:34:37 - cmdstanpy - INFO - Chain [1] start processing
18:34:37 - cmdstanpy - INFO - Chain [1] done processing
18:34:37 - cmdstanpy - INFO - Chain [1] start processing
18:34:37 - cmdstanpy - INFO - Chain [1] done processing
18:34:37 - cmdstanpy - INFO - Chain [1] start processing
18:34:37 - cmdstanpy - INFO - Chain [1] done processing
18:34:38 - cmdstanpy - INFO - Chain [1] start processing
18:34:38 - cmdstanpy - INFO - Chain [1] done processing
18:34:38 - cmdstanpy - INFO - Chain [1] start processing
18:34:38 - cmdstanpy - INFO - Chain [1] done processing
18:34:38 - cmdstanpy - INFO - Chain [1] start processing
18:34:38 - cmdstanpy - INFO - Chain [1] done processing
18:34:38 - cmdstanpy - INFO - Chain [1] start processing
18:34:38 - cmdstanpy - INFO - Chain [1] done processing
18:34:39 - cmdstanpy - INFO - Chain [1] start processing
18:34:39 - cmdstanpy - INFO - Chain [1] done processing
18:34:39 - cmdstanpy - INFO - Chain [1] start processing
18:34:39 - cmdstanpy - INFO - Chain [1] done processing
18:34:39 - cmdstanpy - INFO - Chain [1] start processing
18:34:39 - cmdstanpy - INFO - Chain [1] done processing
18:34:39 - cmdstanpy - INFO - Chain [1] start processing
18:34:39 - cmdstanpy - INFO - Chain [1] done processing
18:34:39 - cmdstanpy - INFO - Chain [1] start processing
18:34:39 - cmdstanpy - INFO - Chain [1] done processing
18:34:40 - cmdstanpy - INFO - Chain [1] start processing
18:34:40 - cmdstanpy - INFO - Chain [1] done processing
18:34:40 - cmdstanpy - INFO - Chain [1] start processing
18:34:40 - cmdstanpy - INFO - Chain [1] done processing
18:34:40 - cmdstanpy - INFO - Chain [1] start processing
18:34:40 - cmdstanpy - INFO - Chain [1] done processing
18:34:40 - cmdstanpy - INFO - Chain [1] start processing
18:34:40 - cmdstanpy - INFO - Chain [1] done processing
18:34:41 - cmdstanpy - INFO - Chain [1] start processing
18:34:41 - cmdstanpy - INFO - Chain [1] done processing
18:34:41 - cmdstanpy - INFO - Chain [1] start processing
18:34:41 - cmdstanpy - INFO - Chain [1] done processing
18:34:41 - cmdstanpy - INFO - Chain [1] start processing
18:34:41 - cmdstanpy - INFO - Chain [1] done processing
18:34:41 - cmdstanpy - INFO - Chain [1] start processing
18:34:41 - cmdstanpy - INFO - Chain [1] done processing
18:34:41 - cmdstanpy - INFO - Chain [1] start processing
18:34:41 - cmdstanpy - INFO - Chain [1] done processing
18:34:42 - cmdstanpy - INFO - Chain [1] start processing
18:34:42 - cmdstanpy - INFO - Chain [1] done processing
18:34:42 - cmdstanpy - INFO - Chain [1] start processing
18:34:42 - cmdstanpy - INFO - Chain [1] done processing
18:34:42 - cmdstanpy - INFO - Chain [1] start processing
18:34:42 - cmdstanpy - INFO - Chain [1] done processing
18:34:42 - cmdstanpy - INFO - Chain [1] start processing
18:34:42 - cmdstanpy - INFO - Chain [1] done processing
18:34:43 - cmdstanpy - INFO - Chain [1] start processing
18:34:43 - cmdstanpy - INFO - Chain [1] done processing
18:34:43 - cmdstanpy - INFO - Chain [1] start processing
18:34:43 - cmdstanpy - INFO - Chain [1] done processing
18:34:43 - cmdstanpy - INFO - Chain [1] start processing
18:34:43 - cmdstanpy - INFO - Chain [1] done processing
18:34:43 - cmdstanpy - INFO - Chain [1] start processing
18:34:43 - cmdstanpy - INFO - Chain [1] done processing
18:34:44 - cmdstanpy - INFO - Chain [1] start processing
18:34:44 - cmdstanpy - INFO - Chain [1] done processing
18:34:44 - cmdstanpy - INFO - Chain [1] start processing
18:34:44 - cmdstanpy - INFO - Chain [1] done processing
18:34:44 - cmdstanpy - INFO - Chain [1] start processing
18:34:44 - cmdstanpy - INFO - Chain [1] done processing
18:34:44 - cmdstanpy - INFO - Chain [1] start processing
18:34:44 - cmdstanpy - INFO - Chain [1] done processing
18:34:44 - cmdstanpy - INFO - Chain [1] start processing
18:34:44 - cmdstanpy - INFO - Chain [1] done processing
18:34:45 - cmdstanpy - INFO - Chain [1] start processing
18:34:45 - cmdstanpy - INFO - Chain [1] done processing
18:34:45 - cmdstanpy - INFO - Chain [1] start processing
18:34:45 - cmdstanpy - INFO - Chain [1] done processing
18:34:45 - cmdstanpy - INFO - Chain [1] start processing
18:34:45 - cmdstanpy - INFO - Chain [1] done processing
18:34:45 - cmdstanpy - INFO - Chain [1] start processing
18:34:45 - cmdstanpy - INFO - Chain [1] done processing
18:34:45 - cmdstanpy - INFO - Chain [1] start processing
18:34:45 - cmdstanpy - INFO - Chain [1] done processing
18:34:46 - cmdstanpy - INFO - Chain [1] start processing
18:34:46 - cmdstanpy - INFO - Chain [1] done processing
18:34:46 - cmdstanpy - INFO - Chain [1] start processing
18:34:46 - cmdstanpy - INFO - Chain [1] done processing
18:34:46 - cmdstanpy - INFO - Chain [1] start processing
18:34:46 - cmdstanpy - INFO - Chain [1] done processing
18:34:46 - cmdstanpy - INFO - Chain [1] start processing
18:34:46 - cmdstanpy - INFO - Chain [1] done processing
18:34:46 - cmdstanpy - INFO - Chain [1] start processing
18:34:46 - cmdstanpy - INFO - Chain [1] done processing
18:34:46 - cmdstanpy - INFO - Chain [1] start processing
18:34:46 - cmdstanpy - INFO - Chain [1] done processing
18:34:47 - cmdstanpy - INFO - Chain [1] start processing
18:34:47 - cmdstanpy - INFO - Chain [1] done processing
18:34:47 - cmdstanpy - INFO - Chain [1] start processing
18:34:47 - cmdstanpy - INFO - Chain [1] done processing
18:34:47 - cmdstanpy - INFO - Chain [1] start processing
18:34:47 - cmdstanpy - INFO - Chain [1] done processing
18:34:47 - cmdstanpy - INFO - Chain [1] start processing
18:34:47 - cmdstanpy - INFO - Chain [1] done processing
18:34:47 - cmdstanpy - INFO - Chain [1] start processing
18:34:47 - cmdstanpy - INFO - Chain [1] done processing
18:34:47 - cmdstanpy - INFO - Chain [1] start processing
18:34:47 - cmdstanpy - INFO - Chain [1] done processing
18:34:48 - cmdstanpy - INFO - Chain [1] start processing
18:34:48 - cmdstanpy - INFO - Chain [1] done processing
18:34:48 - cmdstanpy - INFO - Chain [1] start processing
18:34:48 - cmdstanpy - INFO - Chain [1] done processing
18:34:48 - cmdstanpy - INFO - Chain [1] start processing
18:34:48 - cmdstanpy - INFO - Chain [1] done processing
18:34:48 - cmdstanpy - INFO - Chain [1] start processing
18:34:48 - cmdstanpy - INFO - Chain [1] done processing
18:34:48 - cmdstanpy - INFO - Chain [1] start processing
18:34:48 - cmdstanpy - INFO - Chain [1] done processing
18:34:49 - cmdstanpy - INFO - Chain [1] start processing
18:34:49 - cmdstanpy - INFO - Chain [1] done processing
18:34:49 - cmdstanpy - INFO - Chain [1] start processing
18:34:49 - cmdstanpy - INFO - Chain [1] done processing
18:34:49 - cmdstanpy - INFO - Chain [1] start processing
18:34:49 - cmdstanpy - INFO - Chain [1] done processing
18:34:49 - cmdstanpy - INFO - Chain [1] start processing
18:34:49 - cmdstanpy - INFO - Chain [1] done processing
18:34:49 - cmdstanpy - INFO - Chain [1] start processing
18:34:49 - cmdstanpy - INFO - Chain [1] done processing
18:34:49 - cmdstanpy - INFO - Chain [1] start processing
18:34:49 - cmdstanpy - INFO - Chain [1] done processing
18:34:50 - cmdstanpy - INFO - Chain [1] start processing
18:34:50 - cmdstanpy - INFO - Chain [1] done processing
18:34:50 - cmdstanpy - INFO - Chain [1] start processing
18:34:50 - cmdstanpy - INFO - Chain [1] done processing
18:34:50 - cmdstanpy - INFO - Chain [1] start processing
18:34:50 - cmdstanpy - INFO - Chain [1] done processing
18:34:50 - cmdstanpy - INFO - Chain [1] start processing
18:34:50 - cmdstanpy - INFO - Chain [1] done processing
18:34:50 - cmdstanpy - INFO - Chain [1] start processing
18:34:50 - cmdstanpy - INFO - Chain [1] done processing
18:34:50 - cmdstanpy - INFO - Chain [1] start processing
18:34:51 - cmdstanpy - INFO - Chain [1] done processing
18:34:51 - cmdstanpy - INFO - Chain [1] start processing
18:34:51 - cmdstanpy - INFO - Chain [1] done processing
18:34:51 - cmdstanpy - INFO - Chain [1] start processing
18:34:51 - cmdstanpy - INFO - Chain [1] done processing
18:34:51 - cmdstanpy - INFO - Chain [1] start processing
18:34:51 - cmdstanpy - INFO - Chain [1] done processing
18:34:51 - cmdstanpy - INFO - Chain [1] start processing
18:34:51 - cmdstanpy - INFO - Chain [1] done processing
18:34:52 - cmdstanpy - INFO - Chain [1] start processing
18:34:52 - cmdstanpy - INFO - Chain [1] done processing
18:34:52 - cmdstanpy - INFO - Chain [1] start processing
18:34:52 - cmdstanpy - INFO - Chain [1] done processing
18:34:52 - cmdstanpy - INFO - Chain [1] start processing
18:34:52 - cmdstanpy - INFO - Chain [1] done processing
18:34:52 - cmdstanpy - INFO - Chain [1] start processing
18:34:52 - cmdstanpy - INFO - Chain [1] done processing
18:34:52 - cmdstanpy - INFO - Chain [1] start processing
18:34:53 - cmdstanpy - INFO - Chain [1] done processing
18:34:53 - cmdstanpy - INFO - Chain [1] start processing
18:34:53 - cmdstanpy - INFO - Chain [1] done processing
18:34:53 - cmdstanpy - INFO - Chain [1] start processing
18:34:53 - cmdstanpy - INFO - Chain [1] done processing
18:34:53 - cmdstanpy - INFO - Chain [1] start processing
18:34:53 - cmdstanpy - INFO - Chain [1] done processing
18:34:53 - cmdstanpy - INFO - Chain [1] start processing
18:34:53 - cmdstanpy - INFO - Chain [1] done processing
18:34:54 - cmdstanpy - INFO - Chain [1] start processing
18:34:54 - cmdstanpy - INFO - Chain [1] done processing
18:34:54 - cmdstanpy - INFO - Chain [1] start processing
18:34:54 - cmdstanpy - INFO - Chain [1] done processing
18:34:54 - cmdstanpy - INFO - Chain [1] start processing
18:34:54 - cmdstanpy - INFO - Chain [1] done processing
18:34:54 - cmdstanpy - INFO - Chain [1] start processing
18:34:54 - cmdstanpy - INFO - Chain [1] done processing
18:34:55 - cmdstanpy - INFO - Chain [1] start processing
18:34:55 - cmdstanpy - INFO - Chain [1] done processing
18:34:55 - cmdstanpy - INFO - Chain [1] start processing
18:34:55 - cmdstanpy - INFO - Chain [1] done processing
18:34:55 - cmdstanpy - INFO - Chain [1] start processing
18:34:55 - cmdstanpy - INFO - Chain [1] done processing
18:34:55 - cmdstanpy - INFO - Chain [1] start processing
18:34:55 - cmdstanpy - INFO - Chain [1] done processing
18:34:56 - cmdstanpy - INFO - Chain [1] start processing
18:34:56 - cmdstanpy - INFO - Chain [1] done processing
18:34:56 - cmdstanpy - INFO - Chain [1] start processing
18:34:56 - cmdstanpy - INFO - Chain [1] done processing
18:34:56 - cmdstanpy - INFO - Chain [1] start processing
18:34:56 - cmdstanpy - INFO - Chain [1] done processing
18:34:56 - cmdstanpy - INFO - Chain [1] start processing
18:34:56 - cmdstanpy - INFO - Chain [1] done processing
18:34:56 - cmdstanpy - INFO - Chain [1] start processing
18:34:57 - cmdstanpy - INFO - Chain [1] done processing
18:34:57 - cmdstanpy - INFO - Chain [1] start processing
18:34:57 - cmdstanpy - INFO - Chain [1] done processing
18:34:57 - cmdstanpy - INFO - Chain [1] start processing
18:34:57 - cmdstanpy - INFO - Chain [1] done processing
18:34:57 - cmdstanpy - INFO - Chain [1] start processing
18:34:57 - cmdstanpy - INFO - Chain [1] done processing
18:34:57 - cmdstanpy - INFO - Chain [1] start processing
18:34:57 - cmdstanpy - INFO - Chain [1] done processing
18:34:58 - cmdstanpy - INFO - Chain [1] start processing
18:34:58 - cmdstanpy - INFO - Chain [1] done processing
18:34:58 - cmdstanpy - INFO - Chain [1] start processing
18:34:58 - cmdstanpy - INFO - Chain [1] done processing
18:34:58 - cmdstanpy - INFO - Chain [1] start processing
18:34:58 - cmdstanpy - INFO - Chain [1] done processing
18:34:58 - cmdstanpy - INFO - Chain [1] start processing
18:34:58 - cmdstanpy - INFO - Chain [1] done processing
18:34:59 - cmdstanpy - INFO - Chain [1] start processing
18:34:59 - cmdstanpy - INFO - Chain [1] done processing
18:34:59 - cmdstanpy - INFO - Chain [1] start processing
18:34:59 - cmdstanpy - INFO - Chain [1] done processing
18:34:59 - cmdstanpy - INFO - Chain [1] start processing
18:34:59 - cmdstanpy - INFO - Chain [1] done processing
18:34:59 - cmdstanpy - INFO - Chain [1] start processing
18:34:59 - cmdstanpy - INFO - Chain [1] done processing
18:34:59 - cmdstanpy - INFO - Chain [1] start processing
18:34:59 - cmdstanpy - INFO - Chain [1] done processing
18:34:59 - cmdstanpy - INFO - Chain [1] start processing
18:34:59 - cmdstanpy - INFO - Chain [1] done processing
18:35:00 - cmdstanpy - INFO - Chain [1] start processing

✅ **Parameter terbaik:** (0.05, 10.0, 0.1, 'additive', True, False, True)
📊 **Rata-rata MAPE terbaik:** 16.4144
🔹 **Rata-rata MAPE Prophet Default:** 16.4144
📈 **Peningkatan akurasi dibanding default:** 0.00%

In [31]:
df_exchange = pd.read_csv('../USDIDR=X.csv')
df_exchange

,Date,Adj Close,Close,High,Low,Open,Volume
0,2022-01-03,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0
1,2022-01-04,14283.599609,14283.599609,14383.299805,14259.000000,14303.700195,0
2,2022-01-05,14385.500000,14385.500000,14398.500000,14336.700195,14346.400391,0
3,2022-01-06,14446.500000,14446.500000,14445.799805,14351.000000,14445.799805,0
4,2022-01-07,14408.000000,14408.000000,14408.000000,14320.500000,14408.000000,0
...,...,...,...,...,...,...,...
711,2024-09-24,15174.099609,15174.099609,15204.700195,15117.299805,15174.099609,0
712,2024-09-25,15121.099609,15121.099609,15178.099609,15008.299805,15121.099609,0
713,2024-09-26,15201.500000,15201.500000,15204.000000,14975.700195,15201.500000,0
714,2024-09-27,15070.000000,15070.000000,15161.700195,15019.299805,15070.000000,0
715,2024-09-30,15118.000000,15118.000000,15197.299805,14935.900391,15118.000000,0

In [57]:
df_usd= pd.read_csv('usd_idr_clean.csv')

In [61]:
df_usd = df_usd.drop(columns='Volume')

df_usd

,Date,Adj Close,Close,High,Low,Open
0,2022-01-01,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000
1,2022-01-02,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000
2,2022-01-03,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000
3,2022-01-04,14283.599609,14283.599609,14383.299805,14259.000000,14303.700195
4,2022-01-05,14385.500000,14385.500000,14398.500000,14336.700195,14346.400391
...,...,...,...,...,...,...
999,2024-09-26,15201.500000,15201.500000,15204.000000,14975.700195,15201.500000
1000,2024-09-27,15070.000000,15070.000000,15161.700195,15019.299805,15070.000000
1001,2024-09-28,15086.000000,15086.000000,15173.566732,14991.500000,15086.000000
1002,2024-09-29,15102.000000,15102.000000,15185.433268,14963.700195,15102.000000
1003,2024-09-30,15118.000000,15118.000000,15197.299805,14935.900391,15118.000000

In [41]:
df_usd_idr

,Date,Adj Close,Close,High,Low,Open,Volume
0,2022-01-01,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0.0
1,2022-01-02,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0.0
2,2022-01-03,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0.0
3,2022-01-04,14283.599609,14283.599609,14383.299805,14259.000000,14303.700195,0.0
4,2022-01-05,14385.500000,14385.500000,14398.500000,14336.700195,14346.400391,0.0
...,...,...,...,...,...,...,...
999,2024-09-26,15201.500000,15201.500000,15204.000000,14975.700195,15201.500000,0.0
1000,2024-09-27,15070.000000,15070.000000,15161.700195,15019.299805,15070.000000,0.0
1001,2024-09-28,15086.000000,15086.000000,15173.566732,14991.500000,15086.000000,0.0
1002,2024-09-29,15102.000000,15102.000000,15185.433268,14963.700195,15102.000000,0.0
1003,2024-09-30,15118.000000,15118.000000,15197.299805,14935.900391,15118.000000,0.0

In [43]:
df_usd_idr.isna().sum()

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [46]:
df_usd_idr['Adj Close'].isna().sum()

np.int64(0)

In [50]:
# Pastikan format tanggal sudah sesuai
# df_usd_idr['Date'] = pd.to_datetime(df_usd_idr['Date'])
# df_usd_idr = df_usd_idr.rename(columns={'Date': 'ds'})

for komoditas, df in df_dict.items():
    print(f"\n=== Memproses {komoditas} ===")

    df['Date'] = pd.to_datetime(df['Date'])

    for provinsi in df.columns[1:]:
        print(f"  → Prediksi untuk {provinsi}...")

        df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})

        # Gabungkan dengan data USD/IDR berdasarkan tanggal
        df_merged = df_prov.merge(df_usd_idr, on='ds', how='left')

        # Inisialisasi model Prophet dengan regressor
        model = Prophet()
        model.add_regressor('Adj Close')  # Bisa tambahkan fitur lain jika perlu

        # Latih model
        model.fit(df_merged)

        # Buat prediksi
        future = model.make_future_dataframe(periods=predict_periods, freq='D')
        future = future.merge(df_usd_idr, on='ds', how='left')  # Tambahkan data kurs untuk masa depan

        forecast = model.predict(future)

        # Simpan hasil prediksi
        for _, row in forecast.iterrows():
            if row['ds'].strftime('%Y-%m-%d') >= predict_start:
                all_predictions.append({
                    'id': f"{komoditas}/{provinsi}/{row['ds'].strftime('%Y-%m-%d')}",
                    'price': row['yhat']
                })


# Simpan hasil prediksi ke file CSV
submission_df = pd.DataFrame(all_predictions)
submission_df.to_csv('submission_prophet_usd_idr.csv', index=False)

print("\nSemua prediksi selesai dan disimpan di submission.csv!")

23:10:49 - cmdstanpy - INFO - Chain [1] start processing

=== Memproses Bawang Merah ===
  → Prediksi untuk Aceh...

23:10:49 - cmdstanpy - INFO - Chain [1] done processing

ValueError: Found NaN in column 'Adj Close'

In [53]:
future

,ds,Adj Close,Close,High,Low,Open,Volume
0,2022-01-01,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0.0
1,2022-01-02,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0.0
2,2022-01-03,14215.000000,14215.000000,14301.299805,14207.500000,14246.000000,0.0
3,2022-01-04,14283.599609,14283.599609,14383.299805,14259.000000,14303.700195,0.0
4,2022-01-05,14385.500000,14385.500000,14398.500000,14336.700195,14346.400391,0.0
...,...,...,...,...,...,...,...
1091,2024-12-27,NaN,NaN,NaN,NaN,NaN,NaN
1092,2024-12-28,NaN,NaN,NaN,NaN,NaN,NaN
1093,2024-12-29,NaN,NaN,NaN,NaN,NaN,NaN
1094,2024-12-30,NaN,NaN,NaN,NaN,NaN,NaN
1095,2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df_merged['Adj Close']

0       14215.000000
1       14215.000000
2       14215.000000
3       14283.599609
4       14385.500000
            ...
999     15201.500000
1000    15070.000000
1001    15086.000000
1002    15102.000000
1003    15118.000000
Name: Adj Close, Length: 1004, dtype: float64

In [64]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler

# Set seed untuk reproducibility
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Rentang waktu prediksi
predict_start = '2024-10-01'
predict_end = '2024-12-31'
predict_periods = (pd.to_datetime(predict_end) - pd.to_datetime(predict_start)).days + 1

# Parameter LSTM
seq_length = 30
epochs = 100
batch_size = 16
learning_rate = 0.001

class MultivariateLSTM(nn.Module):
    def __init__(self, input_size=5, hidden_size=64, num_layers=3, output_size=1):  
        super(MultivariateLSTM, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=0.2)
        self.fc = nn.Linear(hidden_size, output_size)  # Hanya memprediksi harga komoditas
    
    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        return self.fc(lstm_out[:, -1, :])  # Hanya ambil output terakhir

# Dictionary untuk menyimpan hasil prediksi
all_predictions = []

for komoditas, df_komoditas in df_dict.items():
    print(f"\n=== Memproses {komoditas} ===")
    
    df_komoditas['Date'] = pd.to_datetime(df_komoditas['Date'])
    df_usd['Date'] = pd.to_datetime(df_usd['Date'])  # Data USD/IDR

    # Gabungkan dengan data USD/IDR berdasarkan tanggal
    df_merged = df_komoditas.merge(df_usd, on='Date', how='left')
    
    for provinsi in df_komoditas.columns[1:]:
        print(f"  → Prediksi untuk {provinsi}...")

        df_prov = df_merged[['Date', provinsi, 'Adj Close', 'Close', 'High', 'Low', 'Open']].rename(
            columns={'Date': 'ds', provinsi: 'y'}
        )
        
        # Normalisasi data
        scaler = MinMaxScaler()
        df_scaled = scaler.fit_transform(df_prov[['y', 'Adj Close', 'Close', 'High', 'Low', 'Open']])
        
        # Buat data sekuens
        X, y = [], []
        for i in range(len(df_scaled) - seq_length):
            X.append(df_scaled[i:i+seq_length, 1:])  # Semua fitur kecuali target
            y.append(df_scaled[i+seq_length, 0])  # Target harga komoditas
        
        X, y = np.array(X), np.array(y)
        X = torch.tensor(X, dtype=torch.float32).to(device)
        y = torch.tensor(y, dtype=torch.float32).unsqueeze(-1).to(device)
        
        # Pisahkan training & testing
        train_size = int(len(X) * 0.8)
        X_train, X_test = X[:train_size], X[train_size:]
        y_train, y_test = y[:train_size], y[train_size:]
        
        # Bangun model LSTM
        model = MultivariateLSTM(input_size=5).to(device)  # 5 fitur dari USD/IDR
        criterion = nn.MSELoss()
        optimizer = optim.Adam(model.parameters(), lr=learning_rate)
        
        # Train model
        for epoch in range(epochs):
            model.train()
            optimizer.zero_grad()
            output = model(X_train)
            loss = criterion(output, y_train)
            loss.backward()
            optimizer.step()
            
            if (epoch + 1) % 10 == 0:
                test_output = model(X_test)
                test_loss = criterion(test_output, y_test).item()
                print(f"Epoch {epoch+1}/{epochs}, Training Loss: {loss.item():.6f}, Testing Loss: {test_loss:.6f}")
        
       # Prediksi masa depan
        model.eval()
        last_sequence = X[-1].unsqueeze(0)  # Data terakhir sebagai input
        future_preds = []

        for _ in range(predict_periods):
            with torch.no_grad():
                next_pred = model(last_sequence).item()  # Prediksi harga komoditas saja
            future_preds.append(next_pred)
            
            # Ambil nilai USD/IDR terakhir (5 fitur)
            last_usd_features = last_sequence[:, -1, 1:].cpu().numpy()  # Fitur selain harga komoditas

            # Ubah next_pred menjadi array 2D agar bisa digabungkan dengan last_usd_features
            next_pred = np.array([[next_pred]])  # Sekarang berbentuk (1, 1)

            # Gabungkan harga prediksi + USD/IDR
            next_input = np.concatenate((next_pred, last_usd_features), axis=1)  # Menjadi (1, 6)

            # Konversi ke tensor
            next_input = torch.tensor(next_input, dtype=torch.float32).unsqueeze(0).to(device)  
            last_sequence = torch.cat([last_sequence[:, 1:, :], next_input], dim=1)  # Masukkan ke dalam urutan baru


        # Konversi kembali ke skala asli (hanya untuk harga komoditas)
        future_preds = np.array(future_preds).reshape(-1, 1)
        future_preds = scaler.inverse_transform(np.concatenate((future_preds, np.zeros((len(future_preds), 5))), axis=1))[:, 0]

        # Simpan hasil prediksi
        for i, pred in enumerate(future_preds):
            date = pd.to_datetime(predict_start) + pd.Timedelta(days=i)
            all_predictions.append({
                'id': f"{komoditas}/{provinsi}/{date.strftime('%Y-%m-%d')}",
                'price': pred
            })

# Simpan hasil prediksi ke CSV
submission_df = pd.DataFrame(all_predictions)
submission_df.to_csv('submission_multivariate_lstm.csv', index=False)

print("\nSemua prediksi selesai dan disimpan di submission_multivariate_lstm.csv!")

=== Memproses Bawang Merah ===
  → Prediksi untuk Aceh...
Epoch 10/100, Training Loss: 0.038472, Testing Loss: 0.123108
Epoch 20/100, Training Loss: 0.029080, Testing Loss: 0.128818
Epoch 30/100, Training Loss: 0.029708, Testing Loss: 0.131503
Epoch 40/100, Training Loss: 0.028668, Testing Loss: 0.117631
Epoch 50/100, Training Loss: 0.027506, Testing Loss: 0.138394
Epoch 60/100, Training Loss: 0.026423, Testing Loss: 0.147239
Epoch 70/100, Training Loss: 0.025752, Testing Loss: 0.195026
Epoch 80/100, Training Loss: 0.025598, Testing Loss: 0.193290
Epoch 90/100, Training Loss: 0.025801, Testing Loss: 0.182868
Epoch 100/100, Training Loss: 0.025691, Testing Loss: 0.199551
  → Prediksi untuk Bali...
Epoch 10/100, Training Loss: 0.036067, Testing Loss: 0.045312
Epoch 20/100, Training Loss: 0.030453, Testing Loss: 0.061827
Epoch 30/100, Training Loss: 0.027265, Testing Loss: 0.052840
Epoch 40/100, Training Loss: 0.026934, Testing Loss: 0.052896
Epoch 50/100, Training Loss: 0.026449, Testing Loss: 0.060739
Epoch 60/100, Training Loss: 0.025793, Testing Loss: 0.062978
Epoch 70/100, Training Loss: 0.025528, Testing Loss: 0.078282
Epoch 80/100, Training Loss: 0.025394, Testing Loss: 0.084544
Epoch 90/100, Training Loss: 0.025080, Testing Loss: 0.079478
Epoch 100/100, Training Loss: 0.025050, Testing Loss: 0.082680
  → Prediksi untuk Banten...
Epoch 10/100, Training Loss: 0.034341, Testing Loss: 0.061073
Epoch 20/100, Training Loss: 0.031724, Testing Loss: 0.065112
Epoch 30/100, Training Loss: 0.030222, Testing Loss: 0.061678
Epoch 40/100, Training Loss: 0.028494, Testing Loss: 0.069077
Epoch 50/100, Training Loss: 0.025241, Testing Loss: 0.106379
Epoch 60/100, Training Loss: 0.024591, Testing Loss: 0.127757
Epoch 70/100, Training Loss: 0.024663, Testing Loss: 0.140992
Epoch 80/100, Training Loss: 0.024400, Testing Loss: 0.154673
Epoch 90/100, Training Loss: 0.024372, Testing Loss: 0.137957
Epoch 100/100, Training Loss: 0.024112, Testing Loss: 0.135822
  → Prediksi untuk Bengkulu...
Epoch 10/100, Training Loss: 0.029930, Testing Loss: 0.077123
Epoch 20/100, Training Loss: 0.027867, Testing Loss: 0.095302
Epoch 30/100, Training Loss: 0.027142, Testing Loss: 0.093189
Epoch 40/100, Training Loss: 0.025938, Testing Loss: 0.092119
Epoch 50/100, Training Loss: 0.024231, Testing Loss: 0.118875
Epoch 60/100, Training Loss: 0.022535, Testing Loss: 0.183576
Epoch 70/100, Training Loss: 0.022188, Testing Loss: 0.159771
Epoch 80/100, Training Loss: 0.022057, Testing Loss: 0.165862
Epoch 90/100, Training Loss: 0.022138, Testing Loss: 0.187080
Epoch 100/100, Training Loss: 0.021907, Testing Loss: 0.183575
  → Prediksi untuk DI Yogyakarta...
Epoch 10/100, Training Loss: 0.056233, Testing Loss: 0.074406
Epoch 20/100, Training Loss: 0.033225, Testing Loss: 0.071845
Epoch 30/100, Training Loss: 0.032515, Testing Loss: 0.071214
Epoch 40/100, Training Loss: 0.031379, Testing Loss: 0.071406
Epoch 50/100, Training Loss: 0.029660, Testing Loss: 0.081406
Epoch 60/100, Training Loss: 0.027875, Testing Loss: 0.095518
Epoch 70/100, Training Loss: 0.027379, Testing Loss: 0.122097
Epoch 80/100, Training Loss: 0.026696, Testing Loss: 0.127490
Epoch 90/100, Training Loss: 0.026614, Testing Loss: 0.151012
Epoch 100/100, Training Loss: 0.026801, Testing Loss: 0.172046
  → Prediksi untuk DKI Jakarta...
Epoch 10/100, Training Loss: 0.032151, Testing Loss: 0.075547
Epoch 20/100, Training Loss: 0.026168, Testing Loss: 0.090247
Epoch 30/100, Training Loss: 0.024353, Testing Loss: 0.084911
Epoch 40/100, Training Loss: 0.023070, Testing Loss: 0.094169
Epoch 50/100, Training Loss: 0.020882, Testing Loss: 0.132103
Epoch 60/100, Training Loss: 0.020228, Testing Loss: 0.174629
Epoch 70/100, Training Loss: 0.019745, Testing Loss: 0.206526
Epoch 80/100, Training Loss: 0.019686, Testing Loss: 0.246448
Epoch 90/100, Training Loss: 0.019672, Testing Loss: 0.228065
Epoch 100/100, Training Loss: 0.019692, Testing Loss: 0.224856
  → Prediksi untuk Gorontalo...
Epoch 10/100, Training Loss: 0.033643, Testing Loss: 0.057819
Epoch 20/100, Training Loss: 0.032741, Testing Loss: 0.034683
Epoch 30/100, Training Loss: 0.028754, Testing Loss: 0.031826
Epoch 40/100, Training Loss: 0.028188, Testing Loss: 0.033153
Epoch 50/100, Training Loss: 0.027357, Testing Loss: 0.034912
Epoch 60/100, Training Loss: 0.026538, Testing Loss: 0.044326
Epoch 70/100, Training Loss: 0.026614, Testing Loss: 0.053735
Epoch 80/100, Training Loss: 0.026601, Testing Loss: 0.053686
Epoch 90/100, Training Loss: 0.026525, Testing Loss: 0.060326
Epoch 100/100, Training Loss: 0.026341, Testing Loss: 0.069131
  → Prediksi untuk Jambi...
Epoch 10/100, Training Loss: 0.046947, Testing Loss: 0.077167
Epoch 20/100, Training Loss: 0.044817, Testing Loss: 0.107210
Epoch 30/100, Training Loss: 0.040078, Testing Loss: 0.089853
Epoch 40/100, Training Loss: 0.038971, Testing Loss: 0.096827
Epoch 50/100, Training Loss: 0.037903, Testing Loss: 0.102780
Epoch 60/100, Training Loss: 0.035139, Testing Loss: 0.122058
Epoch 70/100, Training Loss: 0.032162, Testing Loss: 0.187010
Epoch 80/100, Training Loss: 0.031760, Testing Loss: 0.168586
Epoch 90/100, Training Loss: 0.031323, Testing Loss: 0.195644
Epoch 100/100, Training Loss: 0.031709, Testing Loss: 0.208462
  → Prediksi untuk Jawa Barat...
Epoch 10/100, Training Loss: 0.033355, Testing Loss: 0.058666
Epoch 20/100, Training Loss: 0.028454, Testing Loss: 0.065776
Epoch 30/100, Training Loss: 0.026405, Testing Loss: 0.063582
Epoch 40/100, Training Loss: 0.024044, Testing Loss: 0.104914
Epoch 50/100, Training Loss: 0.023102, Testing Loss: 0.146497
Epoch 60/100, Training Loss: 0.022618, Testing Loss: 0.156656
Epoch 70/100, Training Loss: 0.022401, Testing Loss: 0.191396
Epoch 80/100, Training Loss: 0.022323, Testing Loss: 0.176050
Epoch 90/100, Training Loss: 0.022239, Testing Loss: 0.176140
Epoch 100/100, Training Loss: 0.022229, Testing Loss: 0.168346
  → Prediksi untuk Jawa Tengah...
Epoch 10/100, Training Loss: 0.037069, Testing Loss: 0.060682
Epoch 20/100, Training Loss: 0.031288, Testing Loss: 0.067154
Epoch 30/100, Training Loss: 0.028461, Testing Loss: 0.065814
Epoch 40/100, Training Loss: 0.025760, Testing Loss: 0.111926
Epoch 50/100, Training Loss: 0.025235, Testing Loss: 0.135132
Epoch 60/100, Training Loss: 0.024771, Testing Loss: 0.152407
Epoch 70/100, Training Loss: 0.024648, Testing Loss: 0.210484
Epoch 80/100, Training Loss: 0.024583, Testing Loss: 0.192717
Epoch 90/100, Training Loss: 0.024525, Testing Loss: 0.210979
Epoch 100/100, Training Loss: 0.024394, Testing Loss: 0.204317
  → Prediksi untuk Jawa Timur...
Epoch 10/100, Training Loss: 0.034565, Testing Loss: 0.052413
Epoch 20/100, Training Loss: 0.030591, Testing Loss: 0.054364
Epoch 30/100, Training Loss: 0.029951, Testing Loss: 0.054728
Epoch 40/100, Training Loss: 0.029144, Testing Loss: 0.054712
Epoch 50/100, Training Loss: 0.027909, Testing Loss: 0.061517
Epoch 60/100, Training Loss: 0.026338, Testing Loss: 0.076056
Epoch 70/100, Training Loss: 0.025857, Testing Loss: 0.097131
Epoch 80/100, Training Loss: 0.025684, Testing Loss: 0.103020
Epoch 90/100, Training Loss: 0.025384, Testing Loss: 0.137950
Epoch 100/100, Training Loss: 0.025358, Testing Loss: 0.154023
  → Prediksi untuk Kalimantan Barat...
Epoch 10/100, Training Loss: 0.035339, Testing Loss: 0.029606
Epoch 20/100, Training Loss: 0.035097, Testing Loss: 0.019958
Epoch 30/100, Training Loss: 0.033745, Testing Loss: 0.020673
Epoch 40/100, Training Loss: 0.033633, Testing Loss: 0.021840
Epoch 50/100, Training Loss: 0.033111, Testing Loss: 0.022223
Epoch 60/100, Training Loss: 0.032706, Testing Loss: 0.024504
Epoch 70/100, Training Loss: 0.031920, Testing Loss: 0.041995
Epoch 80/100, Training Loss: 0.031763, Testing Loss: 0.072413
Epoch 90/100, Training Loss: 0.030906, Testing Loss: 0.130760
Epoch 100/100, Training Loss: 0.030971, Testing Loss: 0.197241
  → Prediksi untuk Kalimantan Selatan...
Epoch 10/100, Training Loss: 0.027986, Testing Loss: 0.028938
Epoch 20/100, Training Loss: 0.024583, Testing Loss: 0.030145
Epoch 30/100, Training Loss: 0.024887, Testing Loss: 0.030870
Epoch 40/100, Training Loss: 0.023879, Testing Loss: 0.030685
Epoch 50/100, Training Loss: 0.022960, Testing Loss: 0.034699
Epoch 60/100, Training Loss: 0.021803, Testing Loss: 0.046956
Epoch 70/100, Training Loss: 0.021818, Testing Loss: 0.063355
Epoch 80/100, Training Loss: 0.021463, Testing Loss: 0.065904
Epoch 90/100, Training Loss: 0.021404, Testing Loss: 0.099263
Epoch 100/100, Training Loss: 0.021194, Testing Loss: 0.111775
  → Prediksi untuk Kalimantan Tengah...
Epoch 10/100, Training Loss: 0.030407, Testing Loss: 0.038843
Epoch 20/100, Training Loss: 0.027688, Testing Loss: 0.032197
Epoch 30/100, Training Loss: 0.027061, Testing Loss: 0.032111
Epoch 40/100, Training Loss: 0.026578, Testing Loss: 0.033054
Epoch 50/100, Training Loss: 0.025575, Testing Loss: 0.042972
Epoch 60/100, Training Loss: 0.024590, Testing Loss: 0.082391
Epoch 70/100, Training Loss: 0.024070, Testing Loss: 0.092952
Epoch 80/100, Training Loss: 0.023944, Testing Loss: 0.189922
Epoch 90/100, Training Loss: 0.023840, Testing Loss: 0.234535
Epoch 100/100, Training Loss: 0.023777, Testing Loss: 0.289722
  → Prediksi untuk Kalimantan Timur...
Epoch 10/100, Training Loss: 0.023275, Testing Loss: 0.019434
Epoch 20/100, Training Loss: 0.022876, Testing Loss: 0.020447
Epoch 30/100, Training Loss: 0.022511, Testing Loss: 0.019686
Epoch 40/100, Training Loss: 0.022323, Testing Loss: 0.020809
Epoch 50/100, Training Loss: 0.021970, Testing Loss: 0.022061
Epoch 60/100, Training Loss: 0.021447, Testing Loss: 0.038685
Epoch 70/100, Training Loss: 0.021203, Testing Loss: 0.063501
Epoch 80/100, Training Loss: 0.021014, Testing Loss: 0.144120
Epoch 90/100, Training Loss: 0.020950, Testing Loss: 0.215923
Epoch 100/100, Training Loss: 0.020903, Testing Loss: 0.283414
  → Prediksi untuk Kalimantan Utara...
Epoch 10/100, Training Loss: 0.032370, Testing Loss: 0.031395
Epoch 20/100, Training Loss: 0.029494, Testing Loss: 0.033868
Epoch 30/100, Training Loss: 0.028609, Testing Loss: 0.031733
Epoch 40/100, Training Loss: 0.028354, Testing Loss: 0.033322
Epoch 50/100, Training Loss: 0.028041, Testing Loss: 0.038102
Epoch 60/100, Training Loss: 0.027246, Testing Loss: 0.068370
Epoch 70/100, Training Loss: 0.026917, Testing Loss: 0.100764
Epoch 80/100, Training Loss: 0.026696, Testing Loss: 0.171572
Epoch 90/100, Training Loss: 0.026744, Testing Loss: 0.192039
Epoch 100/100, Training Loss: 0.026656, Testing Loss: 0.183845
  → Prediksi untuk Kepulauan Bangka Belitung...
Epoch 10/100, Training Loss: 0.030831, Testing Loss: 0.074861
Epoch 20/100, Training Loss: 0.029560, Testing Loss: 0.079999
Epoch 30/100, Training Loss: 0.028236, Testing Loss: 0.079054
Epoch 40/100, Training Loss: 0.026723, Testing Loss: 0.084493
Epoch 50/100, Training Loss: 0.024067, Testing Loss: 0.120623
Epoch 60/100, Training Loss: 0.023904, Testing Loss: 0.143644
Epoch 70/100, Training Loss: 0.023484, Testing Loss: 0.147664
Epoch 80/100, Training Loss: 0.023459, Testing Loss: 0.175273
Epoch 90/100, Training Loss: 0.023184, Testing Loss: 0.164074
Epoch 100/100, Training Loss: 0.023177, Testing Loss: 0.166715
  → Prediksi untuk Kepulauan Riau...
Epoch 10/100, Training Loss: 0.044953, Testing Loss: 0.025273
Epoch 20/100, Training Loss: 0.037530, Testing Loss: 0.036896
Epoch 30/100, Training Loss: 0.035862, Testing Loss: 0.024658
Epoch 40/100, Training Loss: 0.035317, Testing Loss: 0.021421
Epoch 50/100, Training Loss: 0.033431, Testing Loss: 0.020653
Epoch 60/100, Training Loss: 0.031558, Testing Loss: 0.021779
Epoch 70/100, Training Loss: 0.030821, Testing Loss: 0.024923
Epoch 80/100, Training Loss: 0.029764, Testing Loss: 0.022032
Epoch 90/100, Training Loss: 0.029246, Testing Loss: 0.022138
Epoch 100/100, Training Loss: 0.028813, Testing Loss: 0.022816
  → Prediksi untuk Lampung...
Epoch 10/100, Training Loss: 0.043688, Testing Loss: 0.091117
Epoch 20/100, Training Loss: 0.036379, Testing Loss: 0.093868
Epoch 30/100, Training Loss: 0.032780, Testing Loss: 0.085943
Epoch 40/100, Training Loss: 0.031445, Testing Loss: 0.092510
Epoch 50/100, Training Loss: 0.029033, Testing Loss: 0.114619
Epoch 60/100, Training Loss: 0.027553, Testing Loss: 0.168816
Epoch 70/100, Training Loss: 0.026956, Testing Loss: 0.145610
Epoch 80/100, Training Loss: 0.026543, Testing Loss: 0.170710
Epoch 90/100, Training Loss: 0.026337, Testing Loss: 0.175812
Epoch 100/100, Training Loss: 0.026563, Testing Loss: 0.169291
  → Prediksi untuk Maluku Utara...
Epoch 10/100, Training Loss: 0.033983, Testing Loss: 0.017172
Epoch 20/100, Training Loss: 0.031624, Testing Loss: 0.030079
Epoch 30/100, Training Loss: 0.030813, Testing Loss: 0.026290
Epoch 40/100, Training Loss: 0.030631, Testing Loss: 0.027251
Epoch 50/100, Training Loss: 0.030022, Testing Loss: 0.040656
Epoch 60/100, Training Loss: 0.028985, Testing Loss: 0.096728
Epoch 70/100, Training Loss: 0.028594, Testing Loss: 0.120272
Epoch 80/100, Training Loss: 0.028299, Testing Loss: 0.200548
Epoch 90/100, Training Loss: 0.028348, Testing Loss: 0.281845
Epoch 100/100, Training Loss: 0.028192, Testing Loss: 0.357331
  → Prediksi untuk Maluku...
Epoch 10/100, Training Loss: 0.035729, Testing Loss: 0.045467
Epoch 20/100, Training Loss: 0.035894, Testing Loss: 0.039972
Epoch 30/100, Training Loss: 0.032805, Testing Loss: 0.038107
Epoch 40/100, Training Loss: 0.032894, Testing Loss: 0.038454
Epoch 50/100, Training Loss: 0.032381, Testing Loss: 0.040221
Epoch 60/100, Training Loss: 0.032104, Testing Loss: 0.041054
Epoch 70/100, Training Loss: 0.031595, Testing Loss: 0.048070
Epoch 80/100, Training Loss: 0.030692, Testing Loss: 0.068708
Epoch 90/100, Training Loss: 0.030170, Testing Loss: 0.102106
Epoch 100/100, Training Loss: 0.029938, Testing Loss: 0.136628
  → Prediksi untuk Nusa Tenggara Barat...
Epoch 10/100, Training Loss: 0.042235, Testing Loss: 0.064832
Epoch 20/100, Training Loss: 0.036266, Testing Loss: 0.056866
Epoch 30/100, Training Loss: 0.034846, Testing Loss: 0.056977
Epoch 40/100, Training Loss: 0.034253, Testing Loss: 0.058307
Epoch 50/100, Training Loss: 0.033377, Testing Loss: 0.064322
Epoch 60/100, Training Loss: 0.032951, Testing Loss: 0.088713
Epoch 70/100, Training Loss: 0.032477, Testing Loss: 0.101850
Epoch 80/100, Training Loss: 0.032150, Testing Loss: 0.231448
Epoch 90/100, Training Loss: 0.031696, Testing Loss: 0.316824
Epoch 100/100, Training Loss: 0.031589, Testing Loss: 0.350757
  → Prediksi untuk Nusa Tenggara Timur...
Epoch 10/100, Training Loss: 0.101993, Testing Loss: 0.112866
Epoch 20/100, Training Loss: 0.064122, Testing Loss: 0.115095
Epoch 30/100, Training Loss: 0.060857, Testing Loss: 0.114733
Epoch 40/100, Training Loss: 0.060572, Testing Loss: 0.116866
Epoch 50/100, Training Loss: 0.059657, Testing Loss: 0.119497
Epoch 60/100, Training Loss: 0.058292, Testing Loss: 0.119861
Epoch 70/100, Training Loss: 0.056557, Testing Loss: 0.129970
Epoch 80/100, Training Loss: 0.054748, Testing Loss: 0.159498
Epoch 90/100, Training Loss: 0.053299, Testing Loss: 0.203067
Epoch 100/100, Training Loss: 0.053628, Testing Loss: 0.226970
  → Prediksi untuk Papua Barat...
Epoch 10/100, Training Loss: 0.057329, Testing Loss: 0.008183
Epoch 20/100, Training Loss: 0.024355, Testing Loss: 0.008089
Epoch 30/100, Training Loss: 0.023664, Testing Loss: 0.006179
Epoch 40/100, Training Loss: 0.023264, Testing Loss: 0.008090
Epoch 50/100, Training Loss: 0.022788, Testing Loss: 0.006249
Epoch 60/100, Training Loss: 0.022148, Testing Loss: 0.007198
Epoch 70/100, Training Loss: 0.022050, Testing Loss: 0.006427
Epoch 80/100, Training Loss: 0.021859, Testing Loss: 0.006687
Epoch 90/100, Training Loss: 0.021934, Testing Loss: 0.006716
Epoch 100/100, Training Loss: 0.021844, Testing Loss: 0.006992
  → Prediksi untuk Papua...
Epoch 10/100, Training Loss: 0.041972, Testing Loss: 0.042191
Epoch 20/100, Training Loss: 0.038120, Testing Loss: 0.034963
Epoch 30/100, Training Loss: 0.037227, Testing Loss: 0.035943
Epoch 40/100, Training Loss: 0.037051, Testing Loss: 0.035782
Epoch 50/100, Training Loss: 0.036994, Testing Loss: 0.036076
Epoch 60/100, Training Loss: 0.036494, Testing Loss: 0.038529
Epoch 70/100, Training Loss: 0.035305, Testing Loss: 0.058602
Epoch 80/100, Training Loss: 0.034025, Testing Loss: 0.139828
Epoch 90/100, Training Loss: 0.033846, Testing Loss: 0.211474
Epoch 100/100, Training Loss: 0.033495, Testing Loss: 0.169159
  → Prediksi untuk Riau...
Epoch 10/100, Training Loss: 0.044357, Testing Loss: 0.099119
Epoch 20/100, Training Loss: 0.041610, Testing Loss: 0.132962
Epoch 30/100, Training Loss: 0.037858, Testing Loss: 0.123442
Epoch 40/100, Training Loss: 0.034523, Testing Loss: 0.162683
Epoch 50/100, Training Loss: 0.033814, Testing Loss: 0.214782
Epoch 60/100, Training Loss: 0.033046, Testing Loss: 0.198121
Epoch 70/100, Training Loss: 0.032556, Testing Loss: 0.243031
Epoch 80/100, Training Loss: 0.032555, Testing Loss: 0.263281
Epoch 90/100, Training Loss: 0.032613, Testing Loss: 0.269688
Epoch 100/100, Training Loss: 0.032852, Testing Loss: 0.284734
  → Prediksi untuk Sulawesi Barat...
Epoch 10/100, Training Loss: 0.028552, Testing Loss: 0.036390
Epoch 20/100, Training Loss: 0.028419, Testing Loss: 0.027518
Epoch 30/100, Training Loss: 0.027554, Testing Loss: 0.027046
Epoch 40/100, Training Loss: 0.027604, Testing Loss: 0.027152
Epoch 50/100, Training Loss: 0.027206, Testing Loss: 0.027908
Epoch 60/100, Training Loss: 0.026940, Testing Loss: 0.028169
Epoch 70/100, Training Loss: 0.026575, Testing Loss: 0.033373
Epoch 80/100, Training Loss: 0.026016, Testing Loss: 0.047975
Epoch 90/100, Training Loss: 0.025616, Testing Loss: 0.073119
Epoch 100/100, Training Loss: 0.025395, Testing Loss: 0.140602
  → Prediksi untuk Sulawesi Selatan...
Epoch 10/100, Training Loss: 0.038332, Testing Loss: 0.067396
Epoch 20/100, Training Loss: 0.032467, Testing Loss: 0.038101
Epoch 30/100, Training Loss: 0.029376, Testing Loss: 0.038237
Epoch 40/100, Training Loss: 0.029178, Testing Loss: 0.037282
Epoch 50/100, Training Loss: 0.029141, Testing Loss: 0.037239
Epoch 60/100, Training Loss: 0.028829, Testing Loss: 0.037904
Epoch 70/100, Training Loss: 0.028776, Testing Loss: 0.038396
Epoch 80/100, Training Loss: 0.028654, Testing Loss: 0.039427
Epoch 90/100, Training Loss: 0.028301, Testing Loss: 0.042765
Epoch 100/100, Training Loss: 0.027842, Testing Loss: 0.060497
  → Prediksi untuk Sulawesi Tengah...
Epoch 10/100, Training Loss: 0.036333, Testing Loss: 0.028672
Epoch 20/100, Training Loss: 0.027518, Testing Loss: 0.030096
Epoch 30/100, Training Loss: 0.028100, Testing Loss: 0.030370
Epoch 40/100, Training Loss: 0.027323, Testing Loss: 0.030114
Epoch 50/100, Training Loss: 0.026880, Testing Loss: 0.030647
Epoch 60/100, Training Loss: 0.026854, Testing Loss: 0.030525
Epoch 70/100, Training Loss: 0.026574, Testing Loss: 0.031465
Epoch 80/100, Training Loss: 0.026429, Testing Loss: 0.032995
Epoch 90/100, Training Loss: 0.026005, Testing Loss: 0.037358
Epoch 100/100, Training Loss: 0.025555, Testing Loss: 0.050334
  → Prediksi untuk Sulawesi Tenggara...
Epoch 10/100, Training Loss: 0.031081, Testing Loss: 0.049693
Epoch 20/100, Training Loss: 0.031501, Testing Loss: 0.042085
Epoch 30/100, Training Loss: 0.030649, Testing Loss: 0.041754
Epoch 40/100, Training Loss: 0.030574, Testing Loss: 0.042370
Epoch 50/100, Training Loss: 0.030307, Testing Loss: 0.042759
Epoch 60/100, Training Loss: 0.030068, Testing Loss: 0.043285
Epoch 70/100, Training Loss: 0.029977, Testing Loss: 0.044741
Epoch 80/100, Training Loss: 0.029654, Testing Loss: 0.049257
Epoch 90/100, Training Loss: 0.029233, Testing Loss: 0.065976
Epoch 100/100, Training Loss: 0.028808, Testing Loss: 0.084717
  → Prediksi untuk Sulawesi Utara...
Epoch 10/100, Training Loss: 0.032398, Testing Loss: 0.044832
Epoch 20/100, Training Loss: 0.030289, Testing Loss: 0.038626
Epoch 30/100, Training Loss: 0.029235, Testing Loss: 0.035755
Epoch 40/100, Training Loss: 0.029351, Testing Loss: 0.035524

In [65]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler

# Set seed untuk reproducibility
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Dictionary untuk menyimpan hasil prediksi
all_predictions = []

# Rentang waktu prediksi
predict_start = '2024-10-01'
predict_end = '2024-12-31'
predict_periods = (pd.to_datetime(predict_end) - pd.to_datetime(predict_start)).days + 1

# Parameter LSTM
seq_length = 30
epochs = 50
batch_size = 16
learning_rate = 0.001

import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable

class LSTMPredictor(nn.Module):
    def __init__(self, input_size=1, hidden_size=128, num_layers=4, output_size=1):
        super(LSTMPredictor, self).__init__()
        self.num_layers = num_layers
        self.hidden_size = hidden_size

        # LSTM dengan lebih banyak layer dan dropout
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=0.3)

        # Fully connected layers untuk memproses output LSTM
        self.fc_1 = nn.Linear(hidden_size, 64)  
        self.fc_2 = nn.Linear(64, output_size)  
        self.relu = nn.ReLU()

    def forward(self, x):
        # Inisialisasi hidden state dan cell state
        h_0 = Variable(torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device))
        c_0 = Variable(torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device))

        # Forward pass LSTM
        lstm_out, _ = self.lstm(x, (h_0, c_0))

        # Ambil output terakhir dari LSTM
        out = lstm_out[:, -1, :]
        out = self.relu(self.fc_1(out))  # Fully connected layer pertama
        out = self.fc_2(out)  # Fully connected layer kedua (output harga)

        return out


for komoditas, df in df_dict.items():
    print(f"\n=== Memproses {komoditas} ===")
    
    df['Date'] = pd.to_datetime(df['Date'])
    
    for provinsi in df.columns[1:]:
        print(f"  → Prediksi untuk {provinsi}...")
        
        df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})
        
        # Normalisasi data
        scaler = MinMaxScaler()
        df_prov['y'] = scaler.fit_transform(df_prov[['y']])
        
        # Buat data sekuens
        X, y = [], []
        for i in range(len(df_prov) - seq_length):
            X.append(df_prov['y'].iloc[i:i+seq_length].values)
            y.append(df_prov['y'].iloc[i+seq_length])
        
        X, y = np.array(X), np.array(y)
        X = torch.tensor(X, dtype=torch.float32).unsqueeze(-1).to(device)
        y = torch.tensor(y, dtype=torch.float32).unsqueeze(-1).to(device)
        
        # Pisahkan training & testing
        train_size = int(len(X) * 0.8)
        X_train, X_test = X[:train_size], X[train_size:]
        y_train, y_test = y[:train_size], y[train_size:]
        
        # Bangun model LSTM
        model = LSTMPredictor().to(device)
        criterion = nn.MSELoss()
        optimizer = optim.Adam(model.parameters(), lr=learning_rate)
        
        # Train model
        for epoch in range(epochs):
            model.train()
            optimizer.zero_grad()
            output = model(X_train)
            loss = criterion(output, y_train)
            loss.backward()
            optimizer.step()
        
        # Prediksi masa depan
        model.eval()
        last_sequence = X[-1].unsqueeze(0)  # Data terakhir sebagai input
        future_preds = []
        
        for _ in range(predict_periods):
            with torch.no_grad():
                next_pred = model(last_sequence).item()
            future_preds.append(next_pred)
            
            last_sequence = torch.cat([last_sequence[:, 1:, :], torch.tensor([[[next_pred]]], dtype=torch.float32).to(device)], dim=1)
        
        # Konversi kembali ke skala asli
        future_preds = scaler.inverse_transform(np.array(future_preds).reshape(-1, 1)).flatten()
        
        # Simpan hasil prediksi
        for i, pred in enumerate(future_preds):
            date = pd.to_datetime(predict_start) + pd.Timedelta(days=i)
            all_predictions.append({
                'id': f"{komoditas}/{provinsi}/{date.strftime('%Y-%m-%d')}",
                'price': pred
            })

# Simpan hasil prediksi ke CSV
submission_df = pd.DataFrame(all_predictions)
submission_df.to_csv('submission_lstm_morehidlayer.csv', index=False)

print("\nSemua prediksi selesai dan disimpan di submission_lstm_pytorch.csv!")

=== Memproses Bawang Merah ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Bawang Putih Bonggol ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Beras Medium ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Beras Premium ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Cabai Merah Keriting ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Cabai Rawit Merah ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Daging Ayam Ras ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Daging Sapi Murni ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Gula Konsumsi ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Minyak Goreng Curah ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Minyak Goreng Kemasan Sederhana ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Telur Ayam Ras ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

=== Memproses Tepung Terigu (Curah) ===
  → Prediksi untuk Aceh...
  → Prediksi untuk Bali...
  → Prediksi untuk Banten...
  → Prediksi untuk Bengkulu...
  → Prediksi untuk DI Yogyakarta...
  → Prediksi untuk DKI Jakarta...
  → Prediksi untuk Gorontalo...
  → Prediksi untuk Jambi...
  → Prediksi untuk Jawa Barat...
  → Prediksi untuk Jawa Tengah...
  → Prediksi untuk Jawa Timur...
  → Prediksi untuk Kalimantan Barat...
  → Prediksi untuk Kalimantan Selatan...
  → Prediksi untuk Kalimantan Tengah...
  → Prediksi untuk Kalimantan Timur...
  → Prediksi untuk Kalimantan Utara...
  → Prediksi untuk Kepulauan Bangka Belitung...
  → Prediksi untuk Kepulauan Riau...
  → Prediksi untuk Lampung...
  → Prediksi untuk Maluku Utara...
  → Prediksi untuk Maluku...
  → Prediksi untuk Nusa Tenggara Barat...
  → Prediksi untuk Nusa Tenggara Timur...
  → Prediksi untuk Papua Barat...
  → Prediksi untuk Papua...
  → Prediksi untuk Riau...
  → Prediksi untuk Sulawesi Barat...
  → Prediksi untuk Sulawesi Selatan...
  → Prediksi untuk Sulawesi Tengah...
  → Prediksi untuk Sulawesi Tenggara...
  → Prediksi untuk Sulawesi Utara...
  → Prediksi untuk Sumatera Barat...
  → Prediksi untuk Sumatera Selatan...
  → Prediksi untuk Sumatera Utara...

Semua prediksi selesai dan disimpan di submission_lstm_pytorch.csv!

In [66]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler

# Set seed untuk reproducibility
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Dictionary untuk menyimpan hasil prediksi
all_predictions = []

# Rentang waktu prediksi
predict_start = '2024-10-01'
predict_end = '2024-12-31'
predict_periods = (pd.to_datetime(predict_end) - pd.to_datetime(predict_start)).days + 1

# Parameter LSTM
seq_length = 30
epochs = 100
batch_size = 16
learning_rate = 0.001

class LSTMPredictor(nn.Module):
    def __init__(self, input_size=1, hidden_size=128, num_layers=4, output_size=1):
        super(LSTMPredictor, self).__init__()
        self.num_layers = num_layers
        self.hidden_size = hidden_size

        # LSTM dengan lebih banyak layer dan dropout
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=0.3)

        # Fully connected layers untuk memproses output LSTM
        self.fc_1 = nn.Linear(hidden_size, 64)  
        self.fc_2 = nn.Linear(64, output_size)  
        self.relu = nn.ReLU()

    def forward(self, x):
        # Inisialisasi hidden state dan cell state
        h_0 = Variable(torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device))
        c_0 = Variable(torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device))

        # Forward pass LSTM
        lstm_out, _ = self.lstm(x, (h_0, c_0))

        # Ambil output terakhir dari LSTM
        out = lstm_out[:, -1, :]
        out = self.relu(self.fc_1(out))  # Fully connected layer pertama
        out = self.fc_2(out)  # Fully connected layer kedua (output harga)

        return out

for komoditas, df in df_dict.items():
    print(f"\n=== Memproses {komoditas} ===")
    
    df['Date'] = pd.to_datetime(df['Date'])
    
    for provinsi in df.columns[1:]:
        print(f"  → Prediksi untuk {provinsi}...")
        
        df_prov = df[['Date', provinsi]].rename(columns={'Date': 'ds', provinsi: 'y'})
        
        # Normalisasi data
        scaler = MinMaxScaler()
        df_prov['y'] = scaler.fit_transform(df_prov[['y']])
        
        # Buat data sekuens
        X, y = [], []
        for i in range(len(df_prov) - seq_length):
            X.append(df_prov['y'].iloc[i:i+seq_length].values)
            y.append(df_prov['y'].iloc[i+seq_length])
        
        X, y = np.array(X), np.array(y)
        X = torch.tensor(X, dtype=torch.float32).unsqueeze(-1).to(device)
        y = torch.tensor(y, dtype=torch.float32).unsqueeze(-1).to(device)
        
        # Pisahkan training & testing
        train_size = int(len(X) * 0.8)
        X_train, X_test = X[:train_size], X[train_size:]
        y_train, y_test = y[:train_size], y[train_size:]
        
        # Bangun model LSTM
        model = LSTMPredictor().to(device)
        criterion = nn.MSELoss()
        optimizer = optim.Adam(model.parameters(), lr=learning_rate)
        
        # Train model
        for epoch in range(epochs):
            model.train()
            optimizer.zero_grad()
            output = model(X_train)
            loss = criterion(output, y_train)
            loss.backward()
            optimizer.step()
            
            if (epoch + 1) % 10 == 0:
                test_output = model(X_test)
                test_loss = criterion(test_output, y_test).item()
                print(f"Epoch {epoch+1}/{epochs}, Training Loss: {loss.item():.6f}, Testing Loss: {test_loss:.6f}")
        
        # Prediksi masa depan
        model.eval()
        last_sequence = X[-1].unsqueeze(0)  # Data terakhir sebagai input
        future_preds = []
        
        for _ in range(predict_periods):
            with torch.no_grad():
                next_pred = model(last_sequence).item()
            future_preds.append(next_pred)
            
            last_sequence = torch.cat([last_sequence[:, 1:, :], torch.tensor([[[next_pred]]], dtype=torch.float32).to(device)], dim=1)
        
        # Konversi kembali ke skala asli
        future_preds = scaler.inverse_transform(np.array(future_preds).reshape(-1, 1)).flatten()
        
        # Simpan hasil prediksi
        for i, pred in enumerate(future_preds):
            date = pd.to_datetime(predict_start) + pd.Timedelta(days=i)
            all_predictions.append({
                'id': f"{komoditas}/{provinsi}/{date.strftime('%Y-%m-%d')}",
                'price': pred
            })

# Simpan hasil prediksi ke CSV
submission_df = pd.DataFrame(all_predictions)
submission_df.to_csv('submission_lstm_more_fix_layer.csv', index=False)

print("\nSemua prediksi selesai dan disimpan di submission_lstm_.csv!")

=== Memproses Bawang Merah ===
  → Prediksi untuk Aceh...
Epoch 10/100, Training Loss: 0.029677, Testing Loss: 0.116298
Epoch 20/100, Training Loss: 0.028046, Testing Loss: 0.118330
Epoch 30/100, Training Loss: 0.026790, Testing Loss: 0.111769
Epoch 40/100, Training Loss: 0.014115, Testing Loss: 0.045813
Epoch 50/100, Training Loss: 0.009878, Testing Loss: 0.032480
Epoch 60/100, Training Loss: 0.006497, Testing Loss: 0.017333
Epoch 70/100, Training Loss: 0.003291, Testing Loss: 0.010564
Epoch 80/100, Training Loss: 0.002069, Testing Loss: 0.005325
Epoch 90/100, Training Loss: 0.001448, Testing Loss: 0.004667
Epoch 100/100, Training Loss: 0.001238, Testing Loss: 0.004767
  → Prediksi untuk Bali...
Epoch 10/100, Training Loss: 0.032884, Testing Loss: 0.048997
Epoch 20/100, Training Loss: 0.026995, Testing Loss: 0.054143
Epoch 30/100, Training Loss: 0.025769, Testing Loss: 0.050700
Epoch 40/100, Training Loss: 0.023432, Testing Loss: 0.042391
Epoch 50/100, Training Loss: 0.015252, Testing Loss: 0.021736
Epoch 60/100, Training Loss: 0.010694, Testing Loss: 0.016152
Epoch 70/100, Training Loss: 0.006878, Testing Loss: 0.008760
Epoch 80/100, Training Loss: 0.003709, Testing Loss: 0.005466
Epoch 90/100, Training Loss: 0.002249, Testing Loss: 0.003061
Epoch 100/100, Training Loss: 0.001702, Testing Loss: 0.002996
  → Prediksi untuk Banten...
Epoch 10/100, Training Loss: 0.031399, Testing Loss: 0.058857
Epoch 20/100, Training Loss: 0.030687, Testing Loss: 0.058555
Epoch 30/100, Training Loss: 0.017292, Testing Loss: 0.031145
Epoch 40/100, Training Loss: 0.013691, Testing Loss: 0.025167
Epoch 50/100, Training Loss: 0.007532, Testing Loss: 0.014562
Epoch 60/100, Training Loss: 0.004324, Testing Loss: 0.007330
Epoch 70/100, Training Loss: 0.002420, Testing Loss: 0.003647
Epoch 80/100, Training Loss: 0.002197, Testing Loss: 0.002906
Epoch 90/100, Training Loss: 0.001818, Testing Loss: 0.003604
Epoch 100/100, Training Loss: 0.001907, Testing Loss: 0.002673
  → Prediksi untuk Bengkulu...
Epoch 10/100, Training Loss: 0.032447, Testing Loss: 0.081604
Epoch 20/100, Training Loss: 0.029186, Testing Loss: 0.091363
Epoch 30/100, Training Loss: 0.026078, Testing Loss: 0.084515
Epoch 40/100, Training Loss: 0.023281, Testing Loss: 0.064181
Epoch 50/100, Training Loss: 0.011721, Testing Loss: 0.031394
Epoch 60/100, Training Loss: 0.008269, Testing Loss: 0.023276
Epoch 70/100, Training Loss: 0.005199, Testing Loss: 0.012508
Epoch 80/100, Training Loss: 0.003414, Testing Loss: 0.009414
Epoch 90/100, Training Loss: 0.002477, Testing Loss: 0.006513
Epoch 100/100, Training Loss: 0.001889, Testing Loss: 0.004292
  → Prediksi untuk DI Yogyakarta...
Epoch 10/100, Training Loss: 0.043149, Testing Loss: 0.065643
Epoch 20/100, Training Loss: 0.030368, Testing Loss: 0.065324
Epoch 30/100, Training Loss: 0.029728, Testing Loss: 0.066709
Epoch 40/100, Training Loss: 0.020064, Testing Loss: 0.035074
Epoch 50/100, Training Loss: 0.013269, Testing Loss: 0.025032
Epoch 60/100, Training Loss: 0.008166, Testing Loss: 0.015809
Epoch 70/100, Training Loss: 0.004981, Testing Loss: 0.010056
Epoch 80/100, Training Loss: 0.003199, Testing Loss: 0.005573
Epoch 90/100, Training Loss: 0.002149, Testing Loss: 0.003318
Epoch 100/100, Training Loss: 0.001891, Testing Loss: 0.003160
  → Prediksi untuk DKI Jakarta...
Epoch 10/100, Training Loss: 0.025927, Testing Loss: 0.080487
Epoch 20/100, Training Loss: 0.025055, Testing Loss: 0.081223
Epoch 30/100, Training Loss: 0.024443, Testing Loss: 0.078566
Epoch 40/100, Training Loss: 0.015411, Testing Loss: 0.048889
Epoch 50/100, Training Loss: 0.009441, Testing Loss: 0.032258
Epoch 60/100, Training Loss: 0.005791, Testing Loss: 0.021507
Epoch 70/100, Training Loss: 0.003992, Testing Loss: 0.013890
Epoch 80/100, Training Loss: 0.002980, Testing Loss: 0.010266
Epoch 90/100, Training Loss: 0.002168, Testing Loss: 0.007463
Epoch 100/100, Training Loss: 0.001737, Testing Loss: 0.006103
  → Prediksi untuk Gorontalo...
Epoch 10/100, Training Loss: 0.031819, Testing Loss: 0.030495
Epoch 20/100, Training Loss: 0.027870, Testing Loss: 0.030404
Epoch 30/100, Training Loss: 0.027050, Testing Loss: 0.029475
Epoch 40/100, Training Loss: 0.018773, Testing Loss: 0.020741
Epoch 50/100, Training Loss: 0.012947, Testing Loss: 0.029872
Epoch 60/100, Training Loss: 0.009244, Testing Loss: 0.012058
Epoch 70/100, Training Loss: 0.005874, Testing Loss: 0.009503
Epoch 80/100, Training Loss: 0.003538, Testing Loss: 0.006353
Epoch 90/100, Training Loss: 0.002305, Testing Loss: 0.005336
Epoch 100/100, Training Loss: 0.002002, Testing Loss: 0.004975
  → Prediksi untuk Jambi...
Epoch 10/100, Training Loss: 0.118779, Testing Loss: 0.085174
Epoch 20/100, Training Loss: 0.046432, Testing Loss: 0.106295
Epoch 30/100, Training Loss: 0.037980, Testing Loss: 0.085927
Epoch 40/100, Training Loss: 0.034255, Testing Loss: 0.079039
Epoch 50/100, Training Loss: 0.019363, Testing Loss: 0.037032
Epoch 60/100, Training Loss: 0.013589, Testing Loss: 0.028673
Epoch 70/100, Training Loss: 0.009037, Testing Loss: 0.014403
Epoch 80/100, Training Loss: 0.006077, Testing Loss: 0.010201
Epoch 90/100, Training Loss: 0.004605, Testing Loss: 0.007112
Epoch 100/100, Training Loss: 0.003478, Testing Loss: 0.005346
  → Prediksi untuk Jawa Barat...
Epoch 10/100, Training Loss: 0.053633, Testing Loss: 0.063057
Epoch 20/100, Training Loss: 0.030518, Testing Loss: 0.062886
Epoch 30/100, Training Loss: 0.027785, Testing Loss: 0.056614
Epoch 40/100, Training Loss: 0.026487, Testing Loss: 0.056261
Epoch 50/100, Training Loss: 0.018089, Testing Loss: 0.032362
Epoch 60/100, Training Loss: 0.011763, Testing Loss: 0.030605
Epoch 70/100, Training Loss: 0.008743, Testing Loss: 0.018290
Epoch 80/100, Training Loss: 0.005711, Testing Loss: 0.013017
Epoch 90/100, Training Loss: 0.002792, Testing Loss: 0.006620
Epoch 100/100, Training Loss: 0.001884, Testing Loss: 0.004505
  → Prediksi untuk Jawa Tengah...
Epoch 10/100, Training Loss: 0.035283, Testing Loss: 0.058780
Epoch 20/100, Training Loss: 0.030720, Testing Loss: 0.059888
Epoch 30/100, Training Loss: 0.029712, Testing Loss: 0.057576
Epoch 40/100, Training Loss: 0.017855, Testing Loss: 0.031375
Epoch 50/100, Training Loss: 0.012766, Testing Loss: 0.021679
Epoch 60/100, Training Loss: 0.007793, Testing Loss: 0.015000
Epoch 70/100, Training Loss: 0.004045, Testing Loss: 0.007666
Epoch 80/100, Training Loss: 0.002025, Testing Loss: 0.004681
Epoch 90/100, Training Loss: 0.001364, Testing Loss: 0.004511
Epoch 100/100, Training Loss: 0.001372, Testing Loss: 0.004576
  → Prediksi untuk Jawa Timur...
Epoch 10/100, Training Loss: 0.031779, Testing Loss: 0.052136
Epoch 20/100, Training Loss: 0.028816, Testing Loss: 0.051545
Epoch 30/100, Training Loss: 0.026207, Testing Loss: 0.045783
Epoch 40/100, Training Loss: 0.015781, Testing Loss: 0.024294
Epoch 50/100, Training Loss: 0.010929, Testing Loss: 0.018124
Epoch 60/100, Training Loss: 0.006782, Testing Loss: 0.009632
Epoch 70/100, Training Loss: 0.002858, Testing Loss: 0.003513
Epoch 80/100, Training Loss: 0.001712, Testing Loss: 0.002675
Epoch 90/100, Training Loss: 0.001500, Testing Loss: 0.002204
Epoch 100/100, Training Loss: 0.001131, Testing Loss: 0.002133
  → Prediksi untuk Kalimantan Barat...
Epoch 10/100, Training Loss: 0.042951, Testing Loss: 0.024775
Epoch 20/100, Training Loss: 0.033067, Testing Loss: 0.020592
Epoch 30/100, Training Loss: 0.031459, Testing Loss: 0.019485
Epoch 40/100, Training Loss: 0.021808, Testing Loss: 0.014155
Epoch 50/100, Training Loss: 0.014059, Testing Loss: 0.008600
Epoch 60/100, Training Loss: 0.009615, Testing Loss: 0.006667
Epoch 70/100, Training Loss: 0.006125, Testing Loss: 0.003953
Epoch 80/100, Training Loss: 0.003703, Testing Loss: 0.002487
Epoch 90/100, Training Loss: 0.002465, Testing Loss: 0.001654
Epoch 100/100, Training Loss: 0.001475, Testing Loss: 0.001262
  → Prediksi untuk Kalimantan Selatan...
Epoch 10/100, Training Loss: 0.026613, Testing Loss: 0.029506
Epoch 20/100, Training Loss: 0.024531, Testing Loss: 0.029563
Epoch 30/100, Training Loss: 0.023907, Testing Loss: 0.029199
Epoch 40/100, Training Loss: 0.022620, Testing Loss: 0.027747
Epoch 50/100, Training Loss: 0.011233, Testing Loss: 0.018569
Epoch 60/100, Training Loss: 0.008928, Testing Loss: 0.011583
Epoch 70/100, Training Loss: 0.005509, Testing Loss: 0.008267
Epoch 80/100, Training Loss: 0.002805, Testing Loss: 0.003730
Epoch 90/100, Training Loss: 0.001658, Testing Loss: 0.002147
Epoch 100/100, Training Loss: 0.001370, Testing Loss: 0.002087
  → Prediksi untuk Kalimantan Tengah...
Epoch 10/100, Training Loss: 0.027224, Testing Loss: 0.030861
Epoch 20/100, Training Loss: 0.026556, Testing Loss: 0.030333
Epoch 30/100, Training Loss: 0.013403, Testing Loss: 0.020407
Epoch 40/100, Training Loss: 0.010589, Testing Loss: 0.014305
Epoch 50/100, Training Loss: 0.005881, Testing Loss: 0.004748
Epoch 60/100, Training Loss: 0.003190, Testing Loss: 0.003271
Epoch 70/100, Training Loss: 0.001644, Testing Loss: 0.002219
Epoch 80/100, Training Loss: 0.001137, Testing Loss: 0.001843
Epoch 90/100, Training Loss: 0.001082, Testing Loss: 0.001322
Epoch 100/100, Training Loss: 0.001116, Testing Loss: 0.001573
  → Prediksi untuk Kalimantan Timur...
Epoch 10/100, Training Loss: 0.025249, Testing Loss: 0.019343
Epoch 20/100, Training Loss: 0.022358, Testing Loss: 0.019402
Epoch 30/100, Training Loss: 0.021581, Testing Loss: 0.018898
Epoch 40/100, Training Loss: 0.013623, Testing Loss: 0.011800
Epoch 50/100, Training Loss: 0.009503, Testing Loss: 0.010552
Epoch 60/100, Training Loss: 0.005983, Testing Loss: 0.006551
Epoch 70/100, Training Loss: 0.002880, Testing Loss: 0.003186
Epoch 80/100, Training Loss: 0.001479, Testing Loss: 0.002131
Epoch 90/100, Training Loss: 0.001259, Testing Loss: 0.001527
Epoch 100/100, Training Loss: 0.001148, Testing Loss: 0.001533
  → Prediksi untuk Kalimantan Utara...
Epoch 10/100, Training Loss: 0.040089, Testing Loss: 0.030985
Epoch 20/100, Training Loss: 0.028382, Testing Loss: 0.030609
Epoch 30/100, Training Loss: 0.027564, Testing Loss: 0.030874
Epoch 40/100, Training Loss: 0.020858, Testing Loss: 0.019692
Epoch 50/100, Training Loss: 0.012225, Testing Loss: 0.019769
Epoch 60/100, Training Loss: 0.007393, Testing Loss: 0.008454
Epoch 70/100, Training Loss: 0.004190, Testing Loss: 0.006143
Epoch 80/100, Training Loss: 0.002131, Testing Loss: 0.004837
Epoch 90/100, Training Loss: 0.001682, Testing Loss: 0.003194
Epoch 100/100, Training Loss: 0.001526, Testing Loss: 0.002719
  → Prediksi untuk Kepulauan Bangka Belitung...
Epoch 10/100, Training Loss: 0.029026, Testing Loss: 0.088376
Epoch 20/100, Training Loss: 0.030115, Testing Loss: 0.073914
Epoch 30/100, Training Loss: 0.027982, Testing Loss: 0.072921
Epoch 40/100, Training Loss: 0.025451, Testing Loss: 0.061982
Epoch 50/100, Training Loss: 0.013558, Testing Loss: 0.039348
Epoch 60/100, Training Loss: 0.009960, Testing Loss: 0.029410
Epoch 70/100, Training Loss: 0.006777, Testing Loss: 0.020028
Epoch 80/100, Training Loss: 0.004653, Testing Loss: 0.013823
Epoch 90/100, Training Loss: 0.003125, Testing Loss: 0.008117
Epoch 100/100, Training Loss: 0.002075, Testing Loss: 0.005378
  → Prediksi untuk Kepulauan Riau...
Epoch 10/100, Training Loss: 0.053676, Testing Loss: 0.026522
Epoch 20/100, Training Loss: 0.040028, Testing Loss: 0.035543
Epoch 30/100, Training Loss: 0.037959, Testing Loss: 0.033284
Epoch 40/100, Training Loss: 0.037290, Testing Loss: 0.030750
Epoch 50/100, Training Loss: 0.030955, Testing Loss: 0.019623
Epoch 60/100, Training Loss: 0.018835, Testing Loss: 0.022140
Epoch 70/100, Training Loss: 0.013174, Testing Loss: 0.011964
Epoch 80/100, Training Loss: 0.010831, Testing Loss: 0.011165
Epoch 90/100, Training Loss: 0.009105, Testing Loss: 0.008104
Epoch 100/100, Training Loss: 0.007873, Testing Loss: 0.006368
  → Prediksi untuk Lampung...
Epoch 10/100, Training Loss: 0.033091, Testing Loss: 0.084474
Epoch 20/100, Training Loss: 0.032402, Testing Loss: 0.079502
Epoch 30/100, Training Loss: 0.022474, Testing Loss: 0.047387
Epoch 40/100, Training Loss: 0.014650, Testing Loss: 0.035159
Epoch 50/100, Training Loss: 0.009655, Testing Loss: 0.024371
Epoch 60/100, Training Loss: 0.005684, Testing Loss: 0.014422
Epoch 70/100, Training Loss: 0.003644, Testing Loss: 0.008605
Epoch 80/100, Training Loss: 0.002212, Testing Loss: 0.005653
Epoch 90/100, Training Loss: 0.001721, Testing Loss: 0.005778
Epoch 100/100, Training Loss: 0.001854, Testing Loss: 0.005439
  → Prediksi untuk Maluku Utara...
Epoch 10/100, Training Loss: 0.043418, Testing Loss: 0.018237
Epoch 20/100, Training Loss: 0.031885, Testing Loss: 0.028279
Epoch 30/100, Training Loss: 0.029767, Testing Loss: 0.021150
Epoch 40/100, Training Loss: 0.018975, Testing Loss: 0.008971
Epoch 50/100, Training Loss: 0.012224, Testing Loss: 0.009592
Epoch 60/100, Training Loss: 0.007829, Testing Loss: 0.007257
Epoch 70/100, Training Loss: 0.004247, Testing Loss: 0.004940
Epoch 80/100, Training Loss: 0.002326, Testing Loss: 0.003638
Epoch 90/100, Training Loss: 0.001746, Testing Loss: 0.004184
Epoch 100/100, Training Loss: 0.001706, Testing Loss: 0.003680
  → Prediksi untuk Maluku...
Epoch 10/100, Training Loss: 0.033651, Testing Loss: 0.038140
Epoch 20/100, Training Loss: 0.032504, Testing Loss: 0.037351
Epoch 30/100, Training Loss: 0.026597, Testing Loss: 0.029629
Epoch 40/100, Training Loss: 0.011633, Testing Loss: 0.014388
Epoch 50/100, Training Loss: 0.005631, Testing Loss: 0.006578
Epoch 60/100, Training Loss: 0.002813, Testing Loss: 0.003575
Epoch 70/100, Training Loss: 0.002245, Testing Loss: 0.003354
Epoch 80/100, Training Loss: 0.002481, Testing Loss: 0.002757
Epoch 90/100, Training Loss: 0.002111, Testing Loss: 0.002743
Epoch 100/100, Training Loss: 0.001979, Testing Loss: 0.002313
  → Prediksi untuk Nusa Tenggara Barat...
Epoch 10/100, Training Loss: 0.057307, Testing Loss: 0.055317
Epoch 20/100, Training Loss: 0.037836, Testing Loss: 0.054939
Epoch 30/100, Training Loss: 0.033287, Testing Loss: 0.052568
Epoch 40/100, Training Loss: 0.029879, Testing Loss: 0.046894
Epoch 50/100, Training Loss: 0.014387, Testing Loss: 0.027811
Epoch 60/100, Training Loss: 0.011383, Testing Loss: 0.017137
Epoch 70/100, Training Loss: 0.008406, Testing Loss: 0.011950
Epoch 80/100, Training Loss: 0.005560, Testing Loss: 0.009214
Epoch 90/100, Training Loss: 0.003681, Testing Loss: 0.006967
Epoch 100/100, Training Loss: 0.002498, Testing Loss: 0.004947
  → Prediksi untuk Nusa Tenggara Timur...
Epoch 10/100, Training Loss: 0.055959, Testing Loss: 0.163983
Epoch 20/100, Training Loss: 0.061149, Testing Loss: 0.112503
Epoch 30/100, Training Loss: 0.052410, Testing Loss: 0.105088
Epoch 40/100, Training Loss: 0.038693, Testing Loss: 0.073490
Epoch 50/100, Training Loss: 0.017210, Testing Loss: 0.029969
Epoch 60/100, Training Loss: 0.011693, Testing Loss: 0.030613
Epoch 70/100, Training Loss: 0.008380, Testing Loss: 0.019528
Epoch 80/100, Training Loss: 0.005859, Testing Loss: 0.011778
Epoch 90/100, Training Loss: 0.004178, Testing Loss: 0.009461
Epoch 100/100, Training Loss: 0.003517, Testing Loss: 0.007590
  → Prediksi untuk Papua Barat...
Epoch 10/100, Training Loss: 0.038273, Testing Loss: 0.032163
Epoch 20/100, Training Loss: 0.022463, Testing Loss: 0.006050
Epoch 30/100, Training Loss: 0.021451, Testing Loss: 0.006268
Epoch 40/100, Training Loss: 0.021174, Testing Loss: 0.007343
Epoch 50/100, Training Loss: 0.019613, Testing Loss: 0.005797
Epoch 60/100, Training Loss: 0.009723, Testing Loss: 0.006646
Epoch 70/100, Training Loss: 0.007089, Testing Loss: 0.004734
Epoch 80/100, Training Loss: 0.005496, Testing Loss: 0.004422
Epoch 90/100, Training Loss: 0.004570, Testing Loss: 0.004289
Epoch 100/100, Training Loss: 0.003888, Testing Loss: 0.003860
  → Prediksi untuk Papua...
Epoch 10/100, Training Loss: 0.039279, Testing Loss: 0.035631
Epoch 20/100, Training Loss: 0.035852, Testing Loss: 0.034603
Epoch 30/100, Training Loss: 0.023966, Testing Loss: 0.023889
Epoch 40/100, Training Loss: 0.015321, Testing Loss: 0.019640
Epoch 50/100, Training Loss: 0.009500, Testing Loss: 0.012901
Epoch 60/100, Training Loss: 0.005093, Testing Loss: 0.008308
Epoch 70/100, Training Loss: 0.002876, Testing Loss: 0.004614
Epoch 80/100, Training Loss: 0.002629, Testing Loss: 0.003864
Epoch 90/100, Training Loss: 0.002321, Testing Loss: 0.003469
Epoch 100/100, Training Loss: 0.002072, Testing Loss: 0.003495
  → Prediksi untuk Riau...
Epoch 10/100, Training Loss: 0.050991, Testing Loss: 0.098597
Epoch 20/100, Training Loss: 0.037098, Testing Loss: 0.102546
Epoch 30/100, Training Loss: 0.034202, Testing Loss: 0.096960
Epoch 40/100, Training Loss: 0.015573, Testing Loss: 0.037004
Epoch 50/100, Training Loss: 0.012443, Testing Loss: 0.029801
Epoch 60/100, Training Loss: 0.009848, Testing Loss: 0.022079
Epoch 70/100, Training Loss: 0.006789, Testing Loss: 0.014018
Epoch 80/100, Training Loss: 0.004571, Testing Loss: 0.009450
Epoch 90/100, Training Loss: 0.003460, Testing Loss: 0.007207
Epoch 100/100, Training Loss: 0.002512, Testing Loss: 0.004616
  → Prediksi untuk Sulawesi Barat...
Epoch 10/100, Training Loss: 0.035088, Testing Loss: 0.026776
Epoch 20/100, Training Loss: 0.027328, Testing Loss: 0.026336
Epoch 30/100, Training Loss: 0.026411, Testing Loss: 0.026062
Epoch 40/100, Training Loss: 0.025081, Testing Loss: 0.024558
Epoch 50/100, Training Loss: 0.013368, Testing Loss: 0.015152
Epoch 60/100, Training Loss: 0.009647, Testing Loss: 0.012846
Epoch 70/100, Training Loss: 0.007052, Testing Loss: 0.009797
Epoch 80/100, Training Loss: 0.004492, Testing Loss: 0.005789
Epoch 90/100, Training Loss: 0.002589, Testing Loss: 0.004019
Epoch 100/100, Training Loss: 0.001945, Testing Loss: 0.002936
  → Prediksi untuk Sulawesi Selatan...
Epoch 10/100, Training Loss: 0.032681, Testing Loss: 0.037004
Epoch 20/100, Training Loss: 0.028273, Testing Loss: 0.036563
Epoch 30/100, Training Loss: 0.026869, Testing Loss: 0.034148
Epoch 40/100, Training Loss: 0.014952, Testing Loss: 0.019265
Epoch 50/100, Training Loss: 0.010715, Testing Loss: 0.018026
Epoch 60/100, Training Loss: 0.007985, Testing Loss: 0.011339
Epoch 70/100, Training Loss: 0.005155, Testing Loss: 0.008529
Epoch 80/100, Training Loss: 0.002905, Testing Loss: 0.004985
Epoch 90/100, Training Loss: 0.002132, Testing Loss: 0.003587
Epoch 100/100, Training Loss: 0.001490, Testing Loss: 0.003352
  → Prediksi untuk Sulawesi Tengah...
Epoch 10/100, Training Loss: 0.055623, Testing Loss: 0.040096
Epoch 20/100, Training Loss: 0.028701, Testing Loss: 0.031219
Epoch 30/100, Training Loss: 0.025858, Testing Loss: 0.029692
Epoch 40/100, Training Loss: 0.024938, Testing Loss: 0.027894
Epoch 50/100, Training Loss: 0.018527, Testing Loss: 0.019241
Epoch 60/100, Training Loss: 0.012229, Testing Loss: 0.018451
Epoch 70/100, Training Loss: 0.007741, Testing Loss: 0.009790
Epoch 80/100, Training Loss: 0.005364, Testing Loss: 0.009075
Epoch 90/100, Training Loss: 0.004079, Testing Loss: 0.006001
Epoch 100/100, Training Loss: 0.002694, Testing Loss: 0.004255
  → Prediksi untuk Sulawesi Tenggara...
Epoch 10/100, Training Loss: 0.035181, Testing Loss: 0.042341
Epoch 20/100, Training Loss: 0.030295, Testing Loss: 0.041116
Epoch 30/100, Training Loss: 0.029182, Testing Loss: 0.040533
Epoch 40/100, Training Loss: 0.024175, Testing Loss: 0.030344
Epoch 50/100, Training Loss: 0.012935, Testing Loss: 0.022047
Epoch 60/100, Training Loss: 0.008755, Testing Loss: 0.013577
Epoch 70/100, Training Loss: 0.005110, Testing Loss: 0.008220
Epoch 80/100, Training Loss: 0.002455, Testing Loss: 0.004441
Epoch 90/100, Training Loss: 0.001532, Testing Loss: 0.003406
Epoch 100/100, Training Loss: 0.001397, Testing Loss: 0.003269
  → Prediksi untuk Sulawesi Utara...
Epoch 10/100, Training Loss: 0.041812, Testing Loss: 0.051347
Epoch 20/100, Training Loss: 0.028747, Testing Loss: 0.034223
Epoch 30/100, Training Loss: 0.027750, Testing Loss: 0.035251
Epoch 40/100, Training Loss: 0.025374, Testing Loss: 0.029588

FileNotFoundError: [Errno 2] No such file or directory: 'submission_lstm_more_fix_layer.csv'

In [68]:
submission_df = pd.DataFrame(all_predictions)
submission_df.to_csv('../submission_lstm_more_fix_layer.csv', index=False)