In [21]:
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
import os
import pandas as pd

# Path ke folder yang berisi file-file DataFrame
folder_path = '../comodity-price-prediction-penyisihan-arkavidia-9/Harga Bahan Pangan/train'

# Dictionary untuk menyimpan semua DataFrame dengan nama file sebagai key
df_dict = {}

# Loop melalui semua file dalam folder
for file_name in os.listdir(folder_path):
    # Pastikan file yang dibaca adalah file yang diinginkan (misalnya, CSV)
    if file_name.endswith('.csv'):
        # Buat path lengkap ke file
        file_path = os.path.join(folder_path, file_name)
        
        # Baca file dan simpan ke dictionary dengan nama file sebagai key
        df = pd.read_csv(file_path)
        df_dict[file_name] = df  # Gunakan nama file sebagai key

In [23]:
df_bawang_merah = df_dict['Bawang Merah.csv']
df_bawang_putih = df_dict['Bawang Putih Bonggol.csv']
df_beras_medium = df_dict['Beras Medium.csv']
df_beras_premium = df_dict['Beras Premium.csv']
df_cabai_merah_keriting = df_dict['Cabai Merah Keriting.csv']
df_cabai_rawit_merah = df_dict['Cabai Rawit Merah.csv']
df_daging_ayam = df_dict['Daging Ayam Ras.csv']
df_daging_sapi = df_dict['Daging Sapi Murni.csv']
df_gula = df_dict['Gula Konsumsi.csv']
df_minyak_goreng_curah = df_dict['Minyak Goreng Curah.csv']
df_minyak_goreng_kemasan = df_dict['Minyak Goreng Kemasan Sederhana.csv']
df_telur_ayam = df_dict['Telur Ayam Ras.csv']
df_tepung_terigu = df_dict['Tepung Terigu (Curah).csv']

In [24]:
import pandas as pd

# List semua dataframe
df_list = [
    df_bawang_merah, df_bawang_putih, df_beras_medium, df_beras_premium, df_cabai_merah_keriting,
    df_cabai_rawit_merah, df_daging_ayam, df_daging_sapi, df_gula, df_minyak_goreng_curah,
    df_minyak_goreng_kemasan, df_telur_ayam, df_tepung_terigu
]

# Loop setiap dataframe dan lakukan interpolasi
for i in range(len(df_list)):
    df = df_list[i]  # Ambil dataframe

    # Pisahkan kolom tanggal (asumsi ada kolom 'date' atau 'tanggal')
    date_cols = df.select_dtypes(include=['datetime64', 'object'])  # Deteksi kolom tanggal
    num_cols = df.select_dtypes(include=['number'])  # Ambil hanya kolom numerik

    # Interpolasi hanya untuk kolom numerik
    df_num_imputed = num_cols.interpolate(method='linear', limit_direction='both')

    # Gabungkan kembali kolom tanggal dengan hasil interpolasi
    df_list[i] = pd.concat([date_cols.reset_index(drop=True), df_num_imputed.reset_index(drop=True)], axis=1)

In [25]:
df_dict = {
    'Bawang Merah': df_list[0],
    'Bawang Putih Bonggol': df_list[1],
    'Beras Medium': df_list[2],
    'Beras Premium': df_list[3],
    'Cabai Merah Keriting': df_list[4],
    'Cabai Rawit Merah': df_list[5],
    'Daging Ayam Ras': df_list[6],
    'Daging Sapi Murni': df_list[7],
    'Gula Konsumsi': df_list[8],
    'Minyak Goreng Curah': df_list[9],
    'Minyak Goreng Kemasan Sederhana': df_list[10],
    'Telur Ayam Ras': df_list[11],
    'Tepung Terigu (Curah)': df_list[12]
}

In [26]:
df_PCA_global = pd.read_csv('PCA_Dataset/PCA_Exchange.csv')
df_PCA_exchange = pd.read_csv('PCA_Dataset/PCA_global_commo.csv')

In [27]:
df_PCA_exchange.head(5)

,Crude Oil WTI Futures,Natural Gas Futures,Newcastle Coal Futures,Palm Oil Futures,US Sugar 11 Futures,US Wheat Futures
0,-1.310918,-0.084197,-1.321539,1.831232,-1.668793,0.514505
1,-1.310918,-0.084197,-1.321539,1.831232,-1.668793,0.514505
2,-1.310918,-0.084197,-1.321539,1.831232,-1.668793,0.514505
3,-1.162784,-0.087038,-0.963294,1.803851,-1.699332,0.514505
4,-1.037087,-0.009913,-0.854299,2.057301,-1.821628,0.503778

In [28]:
df_PCA_global.head(5)

     MYRUSD    SGDUSD    THBUSD    USDIDR
0  4.419041  0.376185  3.378026 -4.079549
1  4.419041  0.376185  3.378026 -4.079549
2  4.419041  0.376185  3.378026 -4.079549
3  4.367445 -0.014675  3.198768 -3.815928
4  4.204347 -0.128121  3.279147 -3.543750

In [29]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

# Dictionary untuk menyimpan model dan prediksi
models = {}
predictions = []
mape_scores = []
predict_start = "2024-10-01"
predict_end = "2024-12-31"

# Buat daftar tanggal untuk prediksi
future_dates = pd.date_range(start=predict_start, end=predict_end)

# Loop setiap komoditas dalam df_dict
for komoditas, df_komoditas in df_dict.items():
    print(f"\n🚀 Mengolah komoditas: {komoditas}")

    # Drop kolom "Date" jika ada
    if "Date" in df_komoditas.columns:
        df_komoditas = df_komoditas.drop(columns=["Date"])

    # Loop setiap provinsi dalam df_komoditas
    for provinsi in df_komoditas.columns:
        print(f"  → Menggabungkan data untuk provinsi: {provinsi}...")

        # Ambil hanya data provinsi tersebut
        df_prov = df_komoditas[[provinsi]].rename(columns={provinsi: 'y'})

        # Gabungkan dengan PCA Global dan PCA Exchange
        df_merged = pd.concat([df_prov, df_PCA_global, df_PCA_exchange], axis=1)

        # Pisahkan fitur (X) dan target harga (y)
        X = df_merged.iloc[:, 1:]  # Semua kolom kecuali harga komoditas
        y = df_merged.iloc[:, 0]   # Kolom pertama sebagai target

        # Pisahkan training & testing
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

        # Inisialisasi dan latih model XGBoost
        model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
        model.fit(X_train, y_train)

        # Simpan model
        models[(komoditas, provinsi)] = model

        # Evaluasi model
        y_pred = model.predict(X_test)
        mae = mean_absolute_error(y_test, y_pred)
        mape = mean_absolute_percentage_error(y_test, y_pred)
        mape_scores.append(mape)  # Simpan MAPE
        print(f"    → MAE untuk {komoditas} - {provinsi}: {mae:.4f}")
        print(f"    → MAPE untuk {komoditas} - {provinsi}: {mape:.4f}")

        # Mulai prediksi ke masa depan dengan iterasi (mirip LSTM)
        last_known_data = X.iloc[-1, :].values.reshape(1, -1)  # Ambil data terakhir
        future_preds = []

        for _ in range(len(future_dates)):
            next_pred = model.predict(last_known_data)[0]  # Prediksi harga hari ini
            future_preds.append(next_pred)

            # Update last_known_data → gantikan harga sebelumnya dengan prediksi baru
            last_known_data = np.roll(last_known_data, -1)  # Geser ke kiri
            last_known_data[0, -1] = next_pred  # Masukkan prediksi ke fitur terakhir

        # Simpan hasil prediksi ke dalam list
        for date, pred in zip(future_dates, future_preds):
            predictions.append({
                'id': f"{komoditas}/{provinsi}/{date.strftime('%Y-%m-%d')}",
                'price': pred  # Harga dibulatkan 4 desimal
            })

# Simpan hasil prediksi ke CSV
submission_df = pd.DataFrame(predictions)
submission_df.to_csv('submission_xgboost_iterative.csv', index=False)
print("\n✅ Hasil prediksi disimpan dalam 'submission_xgboost_iterative.csv'")

🚀 Mengolah komoditas: Bawang Merah
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Bawang Merah - Aceh: 11408.2818
    → MAPE untuk Bawang Merah - Aceh: 0.2678
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Bawang Merah - Bali: 7599.4743
    → MAPE untuk Bawang Merah - Bali: 0.2176
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Bawang Merah - Banten: 12226.0398
    → MAPE untuk Bawang Merah - Banten: 0.3181
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Bawang Merah - Bengkulu: 10966.3447
    → MAPE untuk Bawang Merah - Bengkulu: 0.2785
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Bawang Merah - DI Yogyakarta: 12616.3313
    → MAPE untuk Bawang Merah - DI Yogyakarta: 0.3893
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Bawang Merah - DKI Jakarta: 14897.9394
    → MAPE untuk Bawang Merah - DKI Jakarta: 0.3164
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Bawang Merah - Gorontalo: 11534.2740
    → MAPE untuk Bawang Merah - Gorontalo: 0.3013
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Bawang Merah - Jambi: 9692.1898
    → MAPE untuk Bawang Merah - Jambi: 0.2941
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Bawang Merah - Jawa Barat: 13067.6348
    → MAPE untuk Bawang Merah - Jawa Barat: 0.3732
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Bawang Merah - Jawa Tengah: 12144.8633
    → MAPE untuk Bawang Merah - Jawa Tengah: 0.3604
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Bawang Merah - Jawa Timur: 12900.2650
    → MAPE untuk Bawang Merah - Jawa Timur: 0.4149
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Bawang Merah - Kalimantan Barat: 5757.4514
    → MAPE untuk Bawang Merah - Kalimantan Barat: 0.1616
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Bawang Merah - Kalimantan Selatan: 11664.5090
    → MAPE untuk Bawang Merah - Kalimantan Selatan: 0.3443
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Bawang Merah - Kalimantan Tengah: 8462.3595
    → MAPE untuk Bawang Merah - Kalimantan Tengah: 0.2361
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Bawang Merah - Kalimantan Timur: 7248.5075
    → MAPE untuk Bawang Merah - Kalimantan Timur: 0.1792
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Bawang Merah - Kalimantan Utara: 8103.8323
    → MAPE untuk Bawang Merah - Kalimantan Utara: 0.1824
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...
    → MAE untuk Bawang Merah - Kepulauan Bangka Belitung: 13025.4532
    → MAPE untuk Bawang Merah - Kepulauan Bangka Belitung: 0.3101
  → Menggabungkan data untuk provinsi: Kepulauan Riau...
    → MAE untuk Bawang Merah - Kepulauan Riau: 1991.6364
    → MAPE untuk Bawang Merah - Kepulauan Riau: 0.0517
  → Menggabungkan data untuk provinsi: Lampung...
    → MAE untuk Bawang Merah - Lampung: 13982.2011
    → MAPE untuk Bawang Merah - Lampung: 0.4154
  → Menggabungkan data untuk provinsi: Maluku Utara...
    → MAE untuk Bawang Merah - Maluku Utara: 6842.4103
    → MAPE untuk Bawang Merah - Maluku Utara: 0.1167
  → Menggabungkan data untuk provinsi: Maluku...
    → MAE untuk Bawang Merah - Maluku: 6964.0603
    → MAPE untuk Bawang Merah - Maluku: 0.1609
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...
    → MAE untuk Bawang Merah - Nusa Tenggara Barat: 10149.2766
    → MAPE untuk Bawang Merah - Nusa Tenggara Barat: 0.4011
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...
    → MAE untuk Bawang Merah - Nusa Tenggara Timur: 9412.4295
    → MAPE untuk Bawang Merah - Nusa Tenggara Timur: 0.3625
  → Menggabungkan data untuk provinsi: Papua Barat...
    → MAE untuk Bawang Merah - Papua Barat: 4048.8703
    → MAPE untuk Bawang Merah - Papua Barat: 0.0746
  → Menggabungkan data untuk provinsi: Papua...
    → MAE untuk Bawang Merah - Papua: 6390.9339
    → MAPE untuk Bawang Merah - Papua: 0.1127
  → Menggabungkan data untuk provinsi: Riau...
    → MAE untuk Bawang Merah - Riau: 8920.7124
    → MAPE untuk Bawang Merah - Riau: 0.2537
  → Menggabungkan data untuk provinsi: Sulawesi Barat...
    → MAE untuk Bawang Merah - Sulawesi Barat: 9433.5297
    → MAPE untuk Bawang Merah - Sulawesi Barat: 0.2764
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...
    → MAE untuk Bawang Merah - Sulawesi Selatan: 7843.4416
    → MAPE untuk Bawang Merah - Sulawesi Selatan: 0.2523
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...
    → MAE untuk Bawang Merah - Sulawesi Tengah: 9205.9299
    → MAPE untuk Bawang Merah - Sulawesi Tengah: 0.2268
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...
    → MAE untuk Bawang Merah - Sulawesi Tenggara: 8876.0836
    → MAPE untuk Bawang Merah - Sulawesi Tenggara: 0.2398
  → Menggabungkan data untuk provinsi: Sulawesi Utara...
    → MAE untuk Bawang Merah - Sulawesi Utara: 8518.9383
    → MAPE untuk Bawang Merah - Sulawesi Utara: 0.1985
  → Menggabungkan data untuk provinsi: Sumatera Barat...
    → MAE untuk Bawang Merah - Sumatera Barat: 10126.5380
    → MAPE untuk Bawang Merah - Sumatera Barat: 0.3140
  → Menggabungkan data untuk provinsi: Sumatera Selatan...
    → MAE untuk Bawang Merah - Sumatera Selatan: 11846.1536
    → MAPE untuk Bawang Merah - Sumatera Selatan: 0.3175
  → Menggabungkan data untuk provinsi: Sumatera Utara...
    → MAE untuk Bawang Merah - Sumatera Utara: 8931.4815
    → MAPE untuk Bawang Merah - Sumatera Utara: 0.2263

🚀 Mengolah komoditas: Bawang Putih Bonggol
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Bawang Putih Bonggol - Aceh: 4306.2187
    → MAPE untuk Bawang Putih Bonggol - Aceh: 0.1079
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Bawang Putih Bonggol - Bali: 3622.6128
    → MAPE untuk Bawang Putih Bonggol - Bali: 0.1009
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Bawang Putih Bonggol - Banten: 5496.3634
    → MAPE untuk Bawang Putih Bonggol - Banten: 0.1392
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Bawang Putih Bonggol - Bengkulu: 5941.5563
    → MAPE untuk Bawang Putih Bonggol - Bengkulu: 0.1458
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Bawang Putih Bonggol - DI Yogyakarta: 2530.1944
    → MAPE untuk Bawang Putih Bonggol - DI Yogyakarta: 0.0683
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Bawang Putih Bonggol - DKI Jakarta: 4305.1671
    → MAPE untuk Bawang Putih Bonggol - DKI Jakarta: 0.1011
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Bawang Putih Bonggol - Gorontalo: 6861.3980
    → MAPE untuk Bawang Putih Bonggol - Gorontalo: 0.1410
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Bawang Putih Bonggol - Jambi: 5169.2456
    → MAPE untuk Bawang Putih Bonggol - Jambi: 0.1365
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Bawang Putih Bonggol - Jawa Barat: 4979.1543
    → MAPE untuk Bawang Putih Bonggol - Jawa Barat: 0.1263
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Bawang Putih Bonggol - Jawa Tengah: 4801.7951
    → MAPE untuk Bawang Putih Bonggol - Jawa Tengah: 0.1304
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Bawang Putih Bonggol - Jawa Timur: 3714.0082
    → MAPE untuk Bawang Putih Bonggol - Jawa Timur: 0.1037
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Barat: 4160.9628
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Barat: 0.1058
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Selatan: 4416.3670
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Selatan: 0.1129
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Tengah: 5000.4783
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Tengah: 0.1205
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Timur: 5164.6554
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Timur: 0.1192
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Utara: 4011.4088
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Utara: 0.0884
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...
    → MAE untuk Bawang Putih Bonggol - Kepulauan Bangka Belitung: 5368.8798
    → MAPE untuk Bawang Putih Bonggol - Kepulauan Bangka Belitung: 0.1308
  → Menggabungkan data untuk provinsi: Kepulauan Riau...
    → MAE untuk Bawang Putih Bonggol - Kepulauan Riau: 2307.3122
    → MAPE untuk Bawang Putih Bonggol - Kepulauan Riau: 0.0629
  → Menggabungkan data untuk provinsi: Lampung...
    → MAE untuk Bawang Putih Bonggol - Lampung: 4999.8320
    → MAPE untuk Bawang Putih Bonggol - Lampung: 0.1304
  → Menggabungkan data untuk provinsi: Maluku Utara...
    → MAE untuk Bawang Putih Bonggol - Maluku Utara: 9029.9243
    → MAPE untuk Bawang Putih Bonggol - Maluku Utara: 0.1512
  → Menggabungkan data untuk provinsi: Maluku...
    → MAE untuk Bawang Putih Bonggol - Maluku: 3742.1630
    → MAPE untuk Bawang Putih Bonggol - Maluku: 0.0780
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...
    → MAE untuk Bawang Putih Bonggol - Nusa Tenggara Barat: 5442.1804
    → MAPE untuk Bawang Putih Bonggol - Nusa Tenggara Barat: 0.1369
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...
    → MAE untuk Bawang Putih Bonggol - Nusa Tenggara Timur: 3836.2384
    → MAPE untuk Bawang Putih Bonggol - Nusa Tenggara Timur: 0.0880
  → Menggabungkan data untuk provinsi: Papua Barat...
    → MAE untuk Bawang Putih Bonggol - Papua Barat: 4136.3749
    → MAPE untuk Bawang Putih Bonggol - Papua Barat: 0.0743
  → Menggabungkan data untuk provinsi: Papua...
    → MAE untuk Bawang Putih Bonggol - Papua: 2837.5687
    → MAPE untuk Bawang Putih Bonggol - Papua: 0.0516
  → Menggabungkan data untuk provinsi: Riau...
    → MAE untuk Bawang Putih Bonggol - Riau: 3875.1095
    → MAPE untuk Bawang Putih Bonggol - Riau: 0.1001
  → Menggabungkan data untuk provinsi: Sulawesi Barat...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Barat: 5404.0678
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Barat: 0.1302
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Selatan: 4344.4176
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Selatan: 0.1067
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Tengah: 6557.4753
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Tengah: 0.1389
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Tenggara: 4922.9220
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Tenggara: 0.1040
  → Menggabungkan data untuk provinsi: Sulawesi Utara...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Utara: 6935.1439
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Utara: 0.1354
  → Menggabungkan data untuk provinsi: Sumatera Barat...
    → MAE untuk Bawang Putih Bonggol - Sumatera Barat: 4510.5402
    → MAPE untuk Bawang Putih Bonggol - Sumatera Barat: 0.1155
  → Menggabungkan data untuk provinsi: Sumatera Selatan...
    → MAE untuk Bawang Putih Bonggol - Sumatera Selatan: 4252.1726
    → MAPE untuk Bawang Putih Bonggol - Sumatera Selatan: 0.1070
  → Menggabungkan data untuk provinsi: Sumatera Utara...
    → MAE untuk Bawang Putih Bonggol - Sumatera Utara: 3804.6804
    → MAPE untuk Bawang Putih Bonggol - Sumatera Utara: 0.0971

🚀 Mengolah komoditas: Beras Medium
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Beras Medium - Aceh: 564.6979
    → MAPE untuk Beras Medium - Aceh: 0.0423
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Beras Medium - Bali: 1261.9883
    → MAPE untuk Beras Medium - Bali: 0.0912
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Beras Medium - Banten: 785.5698
    → MAPE untuk Beras Medium - Banten: 0.0618
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Beras Medium - Bengkulu: 760.6800
    → MAPE untuk Beras Medium - Bengkulu: 0.0557
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Beras Medium - DI Yogyakarta: 1331.1880
    → MAPE untuk Beras Medium - DI Yogyakarta: 0.1021
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Beras Medium - DKI Jakarta: 1197.1144
    → MAPE untuk Beras Medium - DKI Jakarta: 0.0850
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Beras Medium - Gorontalo: 666.3469
    → MAPE untuk Beras Medium - Gorontalo: 0.0481
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Beras Medium - Jambi: 831.3697
    → MAPE untuk Beras Medium - Jambi: 0.0639
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Beras Medium - Jawa Barat: 760.6686
    → MAPE untuk Beras Medium - Jawa Barat: 0.0593
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Beras Medium - Jawa Tengah: 888.5105
    → MAPE untuk Beras Medium - Jawa Tengah: 0.0681
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Beras Medium - Jawa Timur: 662.2607
    → MAPE untuk Beras Medium - Jawa Timur: 0.0530
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Beras Medium - Kalimantan Barat: 746.9145
    → MAPE untuk Beras Medium - Kalimantan Barat: 0.0503
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Beras Medium - Kalimantan Selatan: 340.6576
    → MAPE untuk Beras Medium - Kalimantan Selatan: 0.0263
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Beras Medium - Kalimantan Tengah: 641.9937
    → MAPE untuk Beras Medium - Kalimantan Tengah: 0.0449
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Beras Medium - Kalimantan Timur: 1043.4730
    → MAPE untuk Beras Medium - Kalimantan Timur: 0.0660
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Beras Medium - Kalimantan Utara: 573.6103
    → MAPE untuk Beras Medium - Kalimantan Utara: 0.0372
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...
    → MAE untuk Beras Medium - Kepulauan Bangka Belitung: 979.3177
    → MAPE untuk Beras Medium - Kepulauan Bangka Belitung: 0.0681
  → Menggabungkan data untuk provinsi: Kepulauan Riau...
    → MAE untuk Beras Medium - Kepulauan Riau: 635.3699
    → MAPE untuk Beras Medium - Kepulauan Riau: 0.0451
  → Menggabungkan data untuk provinsi: Lampung...
    → MAE untuk Beras Medium - Lampung: 682.7850
    → MAPE untuk Beras Medium - Lampung: 0.0532
  → Menggabungkan data untuk provinsi: Maluku Utara...
    → MAE untuk Beras Medium - Maluku Utara: 1108.0633
    → MAPE untuk Beras Medium - Maluku Utara: 0.0702
  → Menggabungkan data untuk provinsi: Maluku...
    → MAE untuk Beras Medium - Maluku: 459.6587
    → MAPE untuk Beras Medium - Maluku: 0.0313
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...
    → MAE untuk Beras Medium - Nusa Tenggara Barat: 873.4485
    → MAPE untuk Beras Medium - Nusa Tenggara Barat: 0.0678
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...
    → MAE untuk Beras Medium - Nusa Tenggara Timur: 648.2447
    → MAPE untuk Beras Medium - Nusa Tenggara Timur: 0.0475
  → Menggabungkan data untuk provinsi: Papua Barat...
    → MAE untuk Beras Medium - Papua Barat: 610.7624
    → MAPE untuk Beras Medium - Papua Barat: 0.0380
  → Menggabungkan data untuk provinsi: Papua...
    → MAE untuk Beras Medium - Papua: 711.4531
    → MAPE untuk Beras Medium - Papua: 0.0459
  → Menggabungkan data untuk provinsi: Riau...
    → MAE untuk Beras Medium - Riau: 650.2556
    → MAPE untuk Beras Medium - Riau: 0.0470
  → Menggabungkan data untuk provinsi: Sulawesi Barat...
    → MAE untuk Beras Medium - Sulawesi Barat: 701.8194
    → MAPE untuk Beras Medium - Sulawesi Barat: 0.0533
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...
    → MAE untuk Beras Medium - Sulawesi Selatan: 476.2816
    → MAPE untuk Beras Medium - Sulawesi Selatan: 0.0376
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...
    → MAE untuk Beras Medium - Sulawesi Tengah: 903.9203
    → MAPE untuk Beras Medium - Sulawesi Tengah: 0.0665
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...
    → MAE untuk Beras Medium - Sulawesi Tenggara: 399.8535
    → MAPE untuk Beras Medium - Sulawesi Tenggara: 0.0299
  → Menggabungkan data untuk provinsi: Sulawesi Utara...
    → MAE untuk Beras Medium - Sulawesi Utara: 1293.6242
    → MAPE untuk Beras Medium - Sulawesi Utara: 0.0936
  → Menggabungkan data untuk provinsi: Sumatera Barat...
    → MAE untuk Beras Medium - Sumatera Barat: 472.5949
    → MAPE untuk Beras Medium - Sumatera Barat: 0.0314
  → Menggabungkan data untuk provinsi: Sumatera Selatan...
    → MAE untuk Beras Medium - Sumatera Selatan: 788.9370
    → MAPE untuk Beras Medium - Sumatera Selatan: 0.0638
  → Menggabungkan data untuk provinsi: Sumatera Utara...
    → MAE untuk Beras Medium - Sumatera Utara: 1295.0407
    → MAPE untuk Beras Medium - Sumatera Utara: 0.0926

🚀 Mengolah komoditas: Beras Premium
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Beras Premium - Aceh: 502.3449
    → MAPE untuk Beras Premium - Aceh: 0.0345
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Beras Premium - Bali: 700.4424
    → MAPE untuk Beras Premium - Bali: 0.0457
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Beras Premium - Banten: 640.4359
    → MAPE untuk Beras Premium - Banten: 0.0433
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Beras Premium - Bengkulu: 929.3670
    → MAPE untuk Beras Premium - Bengkulu: 0.0601
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Beras Premium - DI Yogyakarta: 848.3388
    → MAPE untuk Beras Premium - DI Yogyakarta: 0.0586
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Beras Premium - DKI Jakarta: 1140.1478
    → MAPE untuk Beras Premium - DKI Jakarta: 0.0699
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Beras Premium - Gorontalo: 978.9948
    → MAPE untuk Beras Premium - Gorontalo: 0.0633
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Beras Premium - Jambi: 730.6097
    → MAPE untuk Beras Premium - Jambi: 0.0495
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Beras Premium - Jawa Barat: 797.4833
    → MAPE untuk Beras Premium - Jawa Barat: 0.0538
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Beras Premium - Jawa Tengah: 745.6767
    → MAPE untuk Beras Premium - Jawa Tengah: 0.0501
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Beras Premium - Jawa Timur: 707.6074
    → MAPE untuk Beras Premium - Jawa Timur: 0.0482
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Beras Premium - Kalimantan Barat: 987.6644
    → MAPE untuk Beras Premium - Kalimantan Barat: 0.0572
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Beras Premium - Kalimantan Selatan: 814.9596
    → MAPE untuk Beras Premium - Kalimantan Selatan: 0.0496
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Beras Premium - Kalimantan Tengah: 930.7231
    → MAPE untuk Beras Premium - Kalimantan Tengah: 0.0530
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Beras Premium - Kalimantan Timur: 1128.6019
    → MAPE untuk Beras Premium - Kalimantan Timur: 0.0645
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Beras Premium - Kalimantan Utara: 1206.6121
    → MAPE untuk Beras Premium - Kalimantan Utara: 0.0693

In [30]:
avg_mape = np.mean(mape_scores)
print(f"\n📊 Rata-rata MAPE keseluruhan: {avg_mape:.4f}")

📊 Rata-rata MAPE keseluruhan: 0.1058

In [45]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

# Parameter sliding window
WINDOW_SIZE = 5

# Dictionary untuk menyimpan model dan prediksi
models = {}
predictions = []
mape_scores = []
predict_start = "2024-10-01"
predict_end = "2024-12-31"

# Buat daftar tanggal untuk prediksi
future_dates = pd.date_range(start=predict_start, end=predict_end)

# Fungsi untuk membuat dataset dengan sliding window
def create_windowed_data(df, target_col, window_size):
    X, y = [], []
    for i in range(len(df) - window_size):
        X.append(df.iloc[i:i+window_size].values.flatten())
        y.append(df.iloc[i + window_size][target_col])
    return np.array(X), np.array(y)

# Loop setiap komoditas dalam df_dict
for komoditas, df_komoditas in df_dict.items():
    print(f"\n🚀 Mengolah komoditas: {komoditas}")

    if "Date" in df_komoditas.columns:
        df_komoditas = df_komoditas.drop(columns=["Date"])

    for provinsi in df_komoditas.columns:
        print(f"  → Menggabungkan data untuk provinsi: {provinsi}...")
        
        df_prov = df_komoditas[[provinsi]].rename(columns={provinsi: 'y'})
        df_merged = pd.concat([df_prov, df_PCA_global, df_PCA_exchange], axis=1)
        
        # Buat data dengan windowing
        X, y = create_windowed_data(df_merged, 'y', WINDOW_SIZE)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
        
        # Inisialisasi dan latih model XGBoost
        model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
        model.fit(X_train, y_train)
        
        # Simpan model
        models[(komoditas, provinsi)] = model
        
        # Evaluasi model
        y_pred = model.predict(X_test)
        mae = mean_absolute_error(y_test, y_pred)
        mape = mean_absolute_percentage_error(y_test, y_pred)
        mape_scores.append(mape)
        print(f"    → MAE untuk {komoditas} - {provinsi}: {mae:.4f}")
        print(f"    → MAPE untuk {komoditas} - {provinsi}: {mape:.4f}")
        
        # Mulai prediksi ke masa depan dengan iterasi mirip LSTM
        last_known_data = X[-1].reshape(1, -1)
        future_preds = []

        for _ in range(len(future_dates)):
            next_pred = model.predict(last_known_data)[0]
            future_preds.append(next_pred)
            
            # Update sliding window dengan prediksi baru
            last_known_data = np.roll(last_known_data, -1)
            last_known_data[0, -1] = next_pred

        # Simpan hasil prediksi
        for date, pred in zip(future_dates, future_preds):
            predictions.append({
                'id': f"{komoditas}/{provinsi}/{date.strftime('%Y-%m-%d')}",
                'price': pred
            })

# Simpan hasil prediksi ke CSV
submission_df = pd.DataFrame(predictions)
submission_df.to_csv('submission_xgboost_lstm.csv', index=False)
print("\n✅ Hasil prediksi disimpan dalam 'submission_xgboost_lstm.csv'")

🚀 Mengolah komoditas: Bawang Merah
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Bawang Merah - Aceh: 1545.1187
    → MAPE untuk Bawang Merah - Aceh: 0.0349
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Bawang Merah - Bali: 1015.7060
    → MAPE untuk Bawang Merah - Bali: 0.0309
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Bawang Merah - Banten: 1671.7198
    → MAPE untuk Bawang Merah - Banten: 0.0472
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Bawang Merah - Bengkulu: 1294.0853
    → MAPE untuk Bawang Merah - Bengkulu: 0.0311
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Bawang Merah - DI Yogyakarta: 1669.4027
    → MAPE untuk Bawang Merah - DI Yogyakarta: 0.0496
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Bawang Merah - DKI Jakarta: 3998.1191
    → MAPE untuk Bawang Merah - DKI Jakarta: 0.0844
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Bawang Merah - Gorontalo: 2017.0882
    → MAPE untuk Bawang Merah - Gorontalo: 0.0538
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Bawang Merah - Jambi: 1262.9969
    → MAPE untuk Bawang Merah - Jambi: 0.0395
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Bawang Merah - Jawa Barat: 1088.1147
    → MAPE untuk Bawang Merah - Jawa Barat: 0.0295
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Bawang Merah - Jawa Tengah: 1337.3712
    → MAPE untuk Bawang Merah - Jawa Tengah: 0.0374
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Bawang Merah - Jawa Timur: 997.8466
    → MAPE untuk Bawang Merah - Jawa Timur: 0.0276
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Bawang Merah - Kalimantan Barat: 747.3042
    → MAPE untuk Bawang Merah - Kalimantan Barat: 0.0203
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Bawang Merah - Kalimantan Selatan: 1316.7687
    → MAPE untuk Bawang Merah - Kalimantan Selatan: 0.0334
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Bawang Merah - Kalimantan Tengah: 1846.2843
    → MAPE untuk Bawang Merah - Kalimantan Tengah: 0.0439
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Bawang Merah - Kalimantan Timur: 1881.5658
    → MAPE untuk Bawang Merah - Kalimantan Timur: 0.0421
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Bawang Merah - Kalimantan Utara: 1905.1644
    → MAPE untuk Bawang Merah - Kalimantan Utara: 0.0400
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...
    → MAE untuk Bawang Merah - Kepulauan Bangka Belitung: 1918.4454
    → MAPE untuk Bawang Merah - Kepulauan Bangka Belitung: 0.0419
  → Menggabungkan data untuk provinsi: Kepulauan Riau...
    → MAE untuk Bawang Merah - Kepulauan Riau: 882.6341
    → MAPE untuk Bawang Merah - Kepulauan Riau: 0.0235
  → Menggabungkan data untuk provinsi: Lampung...
    → MAE untuk Bawang Merah - Lampung: 1259.5292
    → MAPE untuk Bawang Merah - Lampung: 0.0306
  → Menggabungkan data untuk provinsi: Maluku Utara...
    → MAE untuk Bawang Merah - Maluku Utara: 1634.0468
    → MAPE untuk Bawang Merah - Maluku Utara: 0.0296
  → Menggabungkan data untuk provinsi: Maluku...
    → MAE untuk Bawang Merah - Maluku: 2018.1442
    → MAPE untuk Bawang Merah - Maluku: 0.0463
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...
    → MAE untuk Bawang Merah - Nusa Tenggara Barat: 1319.9093
    → MAPE untuk Bawang Merah - Nusa Tenggara Barat: 0.0520
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...
    → MAE untuk Bawang Merah - Nusa Tenggara Timur: 2354.8944
    → MAPE untuk Bawang Merah - Nusa Tenggara Timur: 0.0976
  → Menggabungkan data untuk provinsi: Papua Barat...
    → MAE untuk Bawang Merah - Papua Barat: 2102.7846
    → MAPE untuk Bawang Merah - Papua Barat: 0.0395
  → Menggabungkan data untuk provinsi: Papua...
    → MAE untuk Bawang Merah - Papua: 1834.3432
    → MAPE untuk Bawang Merah - Papua: 0.0324
  → Menggabungkan data untuk provinsi: Riau...
    → MAE untuk Bawang Merah - Riau: 2132.0508
    → MAPE untuk Bawang Merah - Riau: 0.0569
  → Menggabungkan data untuk provinsi: Sulawesi Barat...
    → MAE untuk Bawang Merah - Sulawesi Barat: 1826.4892
    → MAPE untuk Bawang Merah - Sulawesi Barat: 0.0460
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...
    → MAE untuk Bawang Merah - Sulawesi Selatan: 1422.2427
    → MAPE untuk Bawang Merah - Sulawesi Selatan: 0.0421
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...
    → MAE untuk Bawang Merah - Sulawesi Tengah: 1845.4990
    → MAPE untuk Bawang Merah - Sulawesi Tengah: 0.0473
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...
    → MAE untuk Bawang Merah - Sulawesi Tenggara: 1841.8778
    → MAPE untuk Bawang Merah - Sulawesi Tenggara: 0.0544
  → Menggabungkan data untuk provinsi: Sulawesi Utara...
    → MAE untuk Bawang Merah - Sulawesi Utara: 1889.0238
    → MAPE untuk Bawang Merah - Sulawesi Utara: 0.0426
  → Menggabungkan data untuk provinsi: Sumatera Barat...
    → MAE untuk Bawang Merah - Sumatera Barat: 1584.3821
    → MAPE untuk Bawang Merah - Sumatera Barat: 0.0437
  → Menggabungkan data untuk provinsi: Sumatera Selatan...
    → MAE untuk Bawang Merah - Sumatera Selatan: 1253.2737
    → MAPE untuk Bawang Merah - Sumatera Selatan: 0.0291
  → Menggabungkan data untuk provinsi: Sumatera Utara...
    → MAE untuk Bawang Merah - Sumatera Utara: 742.6310
    → MAPE untuk Bawang Merah - Sumatera Utara: 0.0208

🚀 Mengolah komoditas: Bawang Putih Bonggol
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Bawang Putih Bonggol - Aceh: 514.5213
    → MAPE untuk Bawang Putih Bonggol - Aceh: 0.0125
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Bawang Putih Bonggol - Bali: 643.8544
    → MAPE untuk Bawang Putih Bonggol - Bali: 0.0176
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Bawang Putih Bonggol - Banten: 2116.6403
    → MAPE untuk Bawang Putih Bonggol - Banten: 0.0528
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Bawang Putih Bonggol - Bengkulu: 2879.5485
    → MAPE untuk Bawang Putih Bonggol - Bengkulu: 0.0678
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Bawang Putih Bonggol - DI Yogyakarta: 1305.8607
    → MAPE untuk Bawang Putih Bonggol - DI Yogyakarta: 0.0350
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Bawang Putih Bonggol - DKI Jakarta: 2542.9822
    → MAPE untuk Bawang Putih Bonggol - DKI Jakarta: 0.0582
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Bawang Putih Bonggol - Gorontalo: 2681.5986
    → MAPE untuk Bawang Putih Bonggol - Gorontalo: 0.0533
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Bawang Putih Bonggol - Jambi: 872.5608
    → MAPE untuk Bawang Putih Bonggol - Jambi: 0.0224
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Bawang Putih Bonggol - Jawa Barat: 1654.3022
    → MAPE untuk Bawang Putih Bonggol - Jawa Barat: 0.0410
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Bawang Putih Bonggol - Jawa Tengah: 1487.6624
    → MAPE untuk Bawang Putih Bonggol - Jawa Tengah: 0.0394
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Bawang Putih Bonggol - Jawa Timur: 370.1592
    → MAPE untuk Bawang Putih Bonggol - Jawa Timur: 0.0102
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Barat: 1390.1224
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Barat: 0.0335
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Selatan: 610.8599
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Selatan: 0.0155
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Tengah: 1714.8743
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Tengah: 0.0397
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Timur: 1735.8291
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Timur: 0.0386
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Utara: 3479.5488
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Utara: 0.0765
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...
    → MAE untuk Bawang Putih Bonggol - Kepulauan Bangka Belitung: 2187.0286
    → MAPE untuk Bawang Putih Bonggol - Kepulauan Bangka Belitung: 0.0517
  → Menggabungkan data untuk provinsi: Kepulauan Riau...
    → MAE untuk Bawang Putih Bonggol - Kepulauan Riau: 1814.3235
    → MAPE untuk Bawang Putih Bonggol - Kepulauan Riau: 0.0492
  → Menggabungkan data untuk provinsi: Lampung...
    → MAE untuk Bawang Putih Bonggol - Lampung: 2085.9876
    → MAPE untuk Bawang Putih Bonggol - Lampung: 0.0524
  → Menggabungkan data untuk provinsi: Maluku Utara...
    → MAE untuk Bawang Putih Bonggol - Maluku Utara: 5932.7586
    → MAPE untuk Bawang Putih Bonggol - Maluku Utara: 0.0978
  → Menggabungkan data untuk provinsi: Maluku...
    → MAE untuk Bawang Putih Bonggol - Maluku: 2015.3071
    → MAPE untuk Bawang Putih Bonggol - Maluku: 0.0409
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...
    → MAE untuk Bawang Putih Bonggol - Nusa Tenggara Barat: 1416.0149
    → MAPE untuk Bawang Putih Bonggol - Nusa Tenggara Barat: 0.0341
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...
    → MAE untuk Bawang Putih Bonggol - Nusa Tenggara Timur: 2510.5578
    → MAPE untuk Bawang Putih Bonggol - Nusa Tenggara Timur: 0.0553
  → Menggabungkan data untuk provinsi: Papua Barat...
    → MAE untuk Bawang Putih Bonggol - Papua Barat: 2800.1804
    → MAPE untuk Bawang Putih Bonggol - Papua Barat: 0.0500
  → Menggabungkan data untuk provinsi: Papua...
    → MAE untuk Bawang Putih Bonggol - Papua: 2121.4232
    → MAPE untuk Bawang Putih Bonggol - Papua: 0.0385
  → Menggabungkan data untuk provinsi: Riau...
    → MAE untuk Bawang Putih Bonggol - Riau: 493.2893
    → MAPE untuk Bawang Putih Bonggol - Riau: 0.0126
  → Menggabungkan data untuk provinsi: Sulawesi Barat...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Barat: 1058.7271
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Barat: 0.0251
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Selatan: 894.1914
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Selatan: 0.0215
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Tengah: 3319.7516
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Tengah: 0.0679
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Tenggara: 2632.7282
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Tenggara: 0.0531
  → Menggabungkan data untuk provinsi: Sulawesi Utara...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Utara: 3828.0909
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Utara: 0.0723
  → Menggabungkan data untuk provinsi: Sumatera Barat...
    → MAE untuk Bawang Putih Bonggol - Sumatera Barat: 678.0846
    → MAPE untuk Bawang Putih Bonggol - Sumatera Barat: 0.0170
  → Menggabungkan data untuk provinsi: Sumatera Selatan...
    → MAE untuk Bawang Putih Bonggol - Sumatera Selatan: 1722.2375
    → MAPE untuk Bawang Putih Bonggol - Sumatera Selatan: 0.0406
  → Menggabungkan data untuk provinsi: Sumatera Utara...
    → MAE untuk Bawang Putih Bonggol - Sumatera Utara: 830.9695
    → MAPE untuk Bawang Putih Bonggol - Sumatera Utara: 0.0207

🚀 Mengolah komoditas: Beras Medium
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Beras Medium - Aceh: 129.6447
    → MAPE untuk Beras Medium - Aceh: 0.0097
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Beras Medium - Bali: 151.1407
    → MAPE untuk Beras Medium - Bali: 0.0108
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Beras Medium - Banten: 224.4402
    → MAPE untuk Beras Medium - Banten: 0.0173
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Beras Medium - Bengkulu: 80.4325
    → MAPE untuk Beras Medium - Bengkulu: 0.0059
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Beras Medium - DI Yogyakarta: 156.4068
    → MAPE untuk Beras Medium - DI Yogyakarta: 0.0116
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Beras Medium - DKI Jakarta: 259.4091
    → MAPE untuk Beras Medium - DKI Jakarta: 0.0186
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Beras Medium - Gorontalo: 342.6833
    → MAPE untuk Beras Medium - Gorontalo: 0.0238
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Beras Medium - Jambi: 421.1762
    → MAPE untuk Beras Medium - Jambi: 0.0324
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Beras Medium - Jawa Barat: 158.5494
    → MAPE untuk Beras Medium - Jawa Barat: 0.0119
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Beras Medium - Jawa Tengah: 243.3112
    → MAPE untuk Beras Medium - Jawa Tengah: 0.0181
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Beras Medium - Jawa Timur: 180.3289
    → MAPE untuk Beras Medium - Jawa Timur: 0.0145
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Beras Medium - Kalimantan Barat: 173.4565
    → MAPE untuk Beras Medium - Kalimantan Barat: 0.0116
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Beras Medium - Kalimantan Selatan: 206.9985
    → MAPE untuk Beras Medium - Kalimantan Selatan: 0.0160
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Beras Medium - Kalimantan Tengah: 320.6888
    → MAPE untuk Beras Medium - Kalimantan Tengah: 0.0226
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Beras Medium - Kalimantan Timur: 227.3274
    → MAPE untuk Beras Medium - Kalimantan Timur: 0.0142
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Beras Medium - Kalimantan Utara: 195.1558
    → MAPE untuk Beras Medium - Kalimantan Utara: 0.0127
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...
    → MAE untuk Beras Medium - Kepulauan Bangka Belitung: 147.4573
    → MAPE untuk Beras Medium - Kepulauan Bangka Belitung: 0.0103
  → Menggabungkan data untuk provinsi: Kepulauan Riau...
    → MAE untuk Beras Medium - Kepulauan Riau: 410.3981
    → MAPE untuk Beras Medium - Kepulauan Riau: 0.0291
  → Menggabungkan data untuk provinsi: Lampung...
    → MAE untuk Beras Medium - Lampung: 111.3924
    → MAPE untuk Beras Medium - Lampung: 0.0085
  → Menggabungkan data untuk provinsi: Maluku Utara...
    → MAE untuk Beras Medium - Maluku Utara: 1076.2588
    → MAPE untuk Beras Medium - Maluku Utara: 0.0682
  → Menggabungkan data untuk provinsi: Maluku...
    → MAE untuk Beras Medium - Maluku: 337.4614
    → MAPE untuk Beras Medium - Maluku: 0.0230
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...
    → MAE untuk Beras Medium - Nusa Tenggara Barat: 175.3548
    → MAPE untuk Beras Medium - Nusa Tenggara Barat: 0.0135
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...
    → MAE untuk Beras Medium - Nusa Tenggara Timur: 118.2881
    → MAPE untuk Beras Medium - Nusa Tenggara Timur: 0.0085
  → Menggabungkan data untuk provinsi: Papua Barat...
    → MAE untuk Beras Medium - Papua Barat: 562.9455
    → MAPE untuk Beras Medium - Papua Barat: 0.0351
  → Menggabungkan data untuk provinsi: Papua...
    → MAE untuk Beras Medium - Papua: 348.7438
    → MAPE untuk Beras Medium - Papua: 0.0226
  → Menggabungkan data untuk provinsi: Riau...
    → MAE untuk Beras Medium - Riau: 494.5311
    → MAPE untuk Beras Medium - Riau: 0.0356
  → Menggabungkan data untuk provinsi: Sulawesi Barat...
    → MAE untuk Beras Medium - Sulawesi Barat: 301.5414
    → MAPE untuk Beras Medium - Sulawesi Barat: 0.0227
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...
    → MAE untuk Beras Medium - Sulawesi Selatan: 110.8266
    → MAPE untuk Beras Medium - Sulawesi Selatan: 0.0086
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...
    → MAE untuk Beras Medium - Sulawesi Tengah: 452.8249
    → MAPE untuk Beras Medium - Sulawesi Tengah: 0.0333
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...
    → MAE untuk Beras Medium - Sulawesi Tenggara: 225.7111
    → MAPE untuk Beras Medium - Sulawesi Tenggara: 0.0166
  → Menggabungkan data untuk provinsi: Sulawesi Utara...
    → MAE untuk Beras Medium - Sulawesi Utara: 215.4934
    → MAPE untuk Beras Medium - Sulawesi Utara: 0.0156
  → Menggabungkan data untuk provinsi: Sumatera Barat...
    → MAE untuk Beras Medium - Sumatera Barat: 118.2375
    → MAPE untuk Beras Medium - Sumatera Barat: 0.0079
  → Menggabungkan data untuk provinsi: Sumatera Selatan...
    → MAE untuk Beras Medium - Sumatera Selatan: 216.0271
    → MAPE untuk Beras Medium - Sumatera Selatan: 0.0175
  → Menggabungkan data untuk provinsi: Sumatera Utara...
    → MAE untuk Beras Medium - Sumatera Utara: 121.4746
    → MAPE untuk Beras Medium - Sumatera Utara: 0.0087

🚀 Mengolah komoditas: Beras Premium
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Beras Premium - Aceh: 119.6009
    → MAPE untuk Beras Premium - Aceh: 0.0082
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Beras Premium - Bali: 111.5667
    → MAPE untuk Beras Premium - Bali: 0.0072
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Beras Premium - Banten: 242.0636
    → MAPE untuk Beras Premium - Banten: 0.0162
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Beras Premium - Bengkulu: 185.7641
    → MAPE untuk Beras Premium - Bengkulu: 0.0120
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Beras Premium - DI Yogyakarta: 225.2616
    → MAPE untuk Beras Premium - DI Yogyakarta: 0.0151
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Beras Premium - DKI Jakarta: 233.3306
    → MAPE untuk Beras Premium - DKI Jakarta: 0.0145
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Beras Premium - Gorontalo: 458.1389
    → MAPE untuk Beras Premium - Gorontalo: 0.0288
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Beras Premium - Jambi: 163.0066
    → MAPE untuk Beras Premium - Jambi: 0.0111
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Beras Premium - Jawa Barat: 280.8298
    → MAPE untuk Beras Premium - Jawa Barat: 0.0187
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Beras Premium - Jawa Tengah: 250.7696
    → MAPE untuk Beras Premium - Jawa Tengah: 0.0166
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Beras Premium - Jawa Timur: 409.1975
    → MAPE untuk Beras Premium - Jawa Timur: 0.0279
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Beras Premium - Kalimantan Barat: 87.5445
    → MAPE untuk Beras Premium - Kalimantan Barat: 0.0051
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Beras Premium - Kalimantan Selatan: 263.1918
    → MAPE untuk Beras Premium - Kalimantan Selatan: 0.0159
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Beras Premium - Kalimantan Tengah: 156.9882
    → MAPE untuk Beras Premium - Kalimantan Tengah: 0.0090
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Beras Premium - Kalimantan Timur: 144.9122
    → MAPE untuk Beras Premium - Kalimantan Timur: 0.0083
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Beras Premium - Kalimantan Utara: 545.5065
    → MAPE untuk Beras Premium - Kalimantan Utara: 0.0313
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

In [46]:
avg_mape = np.mean(mape_scores)
print(f"\n📊 Rata-rata MAPE keseluruhan: {avg_mape:.4f}")

📊 Rata-rata MAPE keseluruhan: 0.0269

🚀 Mengolah komoditas: Bawang Merah
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Bawang Merah - Aceh: 3948.3149
    → MAPE untuk Bawang Merah - Aceh: 0.0903
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Bawang Merah - Bali: 1363.0883
    → MAPE untuk Bawang Merah - Bali: 0.0448
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Bawang Merah - Banten: 2113.3640
    → MAPE untuk Bawang Merah - Banten: 0.0560
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Bawang Merah - Bengkulu: 2725.0368
    → MAPE untuk Bawang Merah - Bengkulu: 0.0795
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Bawang Merah - DI Yogyakarta: 2406.2238
    → MAPE untuk Bawang Merah - DI Yogyakarta: 0.0870
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Bawang Merah - DKI Jakarta: 3893.3062
    → MAPE untuk Bawang Merah - DKI Jakarta: 0.0935
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Bawang Merah - Gorontalo: 3546.2201
    → MAPE untuk Bawang Merah - Gorontalo: 0.0950
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Bawang Merah - Jambi: 1760.4479
    → MAPE untuk Bawang Merah - Jambi: 0.0539
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Bawang Merah - Jawa Barat: 2334.7028
    → MAPE untuk Bawang Merah - Jawa Barat: 0.0750
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Bawang Merah - Jawa Tengah: 2984.6331
    → MAPE untuk Bawang Merah - Jawa Tengah: 0.0949
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Bawang Merah - Jawa Timur: 2105.2515
    → MAPE untuk Bawang Merah - Jawa Timur: 0.0715
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Bawang Merah - Kalimantan Barat: 1148.8049
    → MAPE untuk Bawang Merah - Kalimantan Barat: 0.0320
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Bawang Merah - Kalimantan Selatan: 3217.9131
    → MAPE untuk Bawang Merah - Kalimantan Selatan: 0.0891
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Bawang Merah - Kalimantan Tengah: 2837.9381
    → MAPE untuk Bawang Merah - Kalimantan Tengah: 0.0730
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Bawang Merah - Kalimantan Timur: 3580.1235
    → MAPE untuk Bawang Merah - Kalimantan Timur: 0.0852
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Bawang Merah - Kalimantan Utara: 2490.3578
    → MAPE untuk Bawang Merah - Kalimantan Utara: 0.0548
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...
    → MAE untuk Bawang Merah - Kepulauan Bangka Belitung: 3749.8517
    → MAPE untuk Bawang Merah - Kepulauan Bangka Belitung: 0.1021
  → Menggabungkan data untuk provinsi: Kepulauan Riau...
    → MAE untuk Bawang Merah - Kepulauan Riau: 878.3682
    → MAPE untuk Bawang Merah - Kepulauan Riau: 0.0231
  → Menggabungkan data untuk provinsi: Lampung...
    → MAE untuk Bawang Merah - Lampung: 2607.8001
    → MAPE untuk Bawang Merah - Lampung: 0.0758
  → Menggabungkan data untuk provinsi: Maluku Utara...
    → MAE untuk Bawang Merah - Maluku Utara: 1980.7868
    → MAPE untuk Bawang Merah - Maluku Utara: 0.0352
  → Menggabungkan data untuk provinsi: Maluku...
    → MAE untuk Bawang Merah - Maluku: 2985.6451
    → MAPE untuk Bawang Merah - Maluku: 0.0669
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...
    → MAE untuk Bawang Merah - Nusa Tenggara Barat: 1940.9906
    → MAPE untuk Bawang Merah - Nusa Tenggara Barat: 0.0704
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...
    → MAE untuk Bawang Merah - Nusa Tenggara Timur: 2267.2920
    → MAPE untuk Bawang Merah - Nusa Tenggara Timur: 0.0963
  → Menggabungkan data untuk provinsi: Papua Barat...
    → MAE untuk Bawang Merah - Papua Barat: 2935.4629
    → MAPE untuk Bawang Merah - Papua Barat: 0.0553
  → Menggabungkan data untuk provinsi: Papua...
    → MAE untuk Bawang Merah - Papua: 2124.0901
    → MAPE untuk Bawang Merah - Papua: 0.0376
  → Menggabungkan data untuk provinsi: Riau...
    → MAE untuk Bawang Merah - Riau: 1816.2583
    → MAPE untuk Bawang Merah - Riau: 0.0585
  → Menggabungkan data untuk provinsi: Sulawesi Barat...
    → MAE untuk Bawang Merah - Sulawesi Barat: 3187.6220
    → MAPE untuk Bawang Merah - Sulawesi Barat: 0.0889
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...
    → MAE untuk Bawang Merah - Sulawesi Selatan: 2493.6720
    → MAPE untuk Bawang Merah - Sulawesi Selatan: 0.0727
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...
    → MAE untuk Bawang Merah - Sulawesi Tengah: 3210.2169
    → MAPE untuk Bawang Merah - Sulawesi Tengah: 0.0751
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...
    → MAE untuk Bawang Merah - Sulawesi Tenggara: 3100.4594
    → MAPE untuk Bawang Merah - Sulawesi Tenggara: 0.0834
  → Menggabungkan data untuk provinsi: Sulawesi Utara...
    → MAE untuk Bawang Merah - Sulawesi Utara: 3683.4462
    → MAPE untuk Bawang Merah - Sulawesi Utara: 0.0911
  → Menggabungkan data untuk provinsi: Sumatera Barat...
    → MAE untuk Bawang Merah - Sumatera Barat: 2099.9492
    → MAPE untuk Bawang Merah - Sumatera Barat: 0.0711
  → Menggabungkan data untuk provinsi: Sumatera Selatan...
    → MAE untuk Bawang Merah - Sumatera Selatan: 2376.9009
    → MAPE untuk Bawang Merah - Sumatera Selatan: 0.0736
  → Menggabungkan data untuk provinsi: Sumatera Utara...
    → MAE untuk Bawang Merah - Sumatera Utara: 3137.8569
    → MAPE untuk Bawang Merah - Sumatera Utara: 0.0758

🚀 Mengolah komoditas: Bawang Putih Bonggol
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Bawang Putih Bonggol - Aceh: 458.2718
    → MAPE untuk Bawang Putih Bonggol - Aceh: 0.0114
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Bawang Putih Bonggol - Bali: 1517.2580
    → MAPE untuk Bawang Putih Bonggol - Bali: 0.0423
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Bawang Putih Bonggol - Banten: 824.9390
    → MAPE untuk Bawang Putih Bonggol - Banten: 0.0207
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Bawang Putih Bonggol - Bengkulu: 1105.1198
    → MAPE untuk Bawang Putih Bonggol - Bengkulu: 0.0271
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Bawang Putih Bonggol - DI Yogyakarta: 569.1711
    → MAPE untuk Bawang Putih Bonggol - DI Yogyakarta: 0.0156
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Bawang Putih Bonggol - DKI Jakarta: 1819.0930
    → MAPE untuk Bawang Putih Bonggol - DKI Jakarta: 0.0421
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Bawang Putih Bonggol - Gorontalo: 2362.8307
    → MAPE untuk Bawang Putih Bonggol - Gorontalo: 0.0505
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Bawang Putih Bonggol - Jambi: 497.2632
    → MAPE untuk Bawang Putih Bonggol - Jambi: 0.0129
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Bawang Putih Bonggol - Jawa Barat: 843.6051
    → MAPE untuk Bawang Putih Bonggol - Jawa Barat: 0.0208
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Bawang Putih Bonggol - Jawa Tengah: 2851.7698
    → MAPE untuk Bawang Putih Bonggol - Jawa Tengah: 0.0746
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Bawang Putih Bonggol - Jawa Timur: 616.0660
    → MAPE untuk Bawang Putih Bonggol - Jawa Timur: 0.0174
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Barat: 1643.3079
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Barat: 0.0408
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Selatan: 1102.1733
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Selatan: 0.0285
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Tengah: 1113.4057
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Tengah: 0.0258
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Timur: 1250.9450
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Timur: 0.0279
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Bawang Putih Bonggol - Kalimantan Utara: 1623.6165
    → MAPE untuk Bawang Putih Bonggol - Kalimantan Utara: 0.0353
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...
    → MAE untuk Bawang Putih Bonggol - Kepulauan Bangka Belitung: 830.2193
    → MAPE untuk Bawang Putih Bonggol - Kepulauan Bangka Belitung: 0.0202
  → Menggabungkan data untuk provinsi: Kepulauan Riau...
    → MAE untuk Bawang Putih Bonggol - Kepulauan Riau: 683.1393
    → MAPE untuk Bawang Putih Bonggol - Kepulauan Riau: 0.0187
  → Menggabungkan data untuk provinsi: Lampung...
    → MAE untuk Bawang Putih Bonggol - Lampung: 1042.8819
    → MAPE untuk Bawang Putih Bonggol - Lampung: 0.0263
  → Menggabungkan data untuk provinsi: Maluku Utara...
    → MAE untuk Bawang Putih Bonggol - Maluku Utara: 6990.8746
    → MAPE untuk Bawang Putih Bonggol - Maluku Utara: 0.1149
  → Menggabungkan data untuk provinsi: Maluku...
    → MAE untuk Bawang Putih Bonggol - Maluku: 1831.0426
    → MAPE untuk Bawang Putih Bonggol - Maluku: 0.0368
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...
    → MAE untuk Bawang Putih Bonggol - Nusa Tenggara Barat: 975.2676
    → MAPE untuk Bawang Putih Bonggol - Nusa Tenggara Barat: 0.0241
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...
    → MAE untuk Bawang Putih Bonggol - Nusa Tenggara Timur: 1430.0148
    → MAPE untuk Bawang Putih Bonggol - Nusa Tenggara Timur: 0.0326
  → Menggabungkan data untuk provinsi: Papua Barat...
    → MAE untuk Bawang Putih Bonggol - Papua Barat: 3723.7872
    → MAPE untuk Bawang Putih Bonggol - Papua Barat: 0.0658
  → Menggabungkan data untuk provinsi: Papua...
    → MAE untuk Bawang Putih Bonggol - Papua: 2190.7755
    → MAPE untuk Bawang Putih Bonggol - Papua: 0.0398
  → Menggabungkan data untuk provinsi: Riau...
    → MAE untuk Bawang Putih Bonggol - Riau: 654.8192
    → MAPE untuk Bawang Putih Bonggol - Riau: 0.0168
  → Menggabungkan data untuk provinsi: Sulawesi Barat...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Barat: 1384.3817
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Barat: 0.0327
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Selatan: 368.8664
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Selatan: 0.0090
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Tengah: 2341.7221
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Tengah: 0.0481
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Tenggara: 2271.6909
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Tenggara: 0.0465
  → Menggabungkan data untuk provinsi: Sulawesi Utara...
    → MAE untuk Bawang Putih Bonggol - Sulawesi Utara: 1807.1598
    → MAPE untuk Bawang Putih Bonggol - Sulawesi Utara: 0.0357
  → Menggabungkan data untuk provinsi: Sumatera Barat...
    → MAE untuk Bawang Putih Bonggol - Sumatera Barat: 372.1086
    → MAPE untuk Bawang Putih Bonggol - Sumatera Barat: 0.0095
  → Menggabungkan data untuk provinsi: Sumatera Selatan...
    → MAE untuk Bawang Putih Bonggol - Sumatera Selatan: 1130.1721
    → MAPE untuk Bawang Putih Bonggol - Sumatera Selatan: 0.0287
  → Menggabungkan data untuk provinsi: Sumatera Utara...
    → MAE untuk Bawang Putih Bonggol - Sumatera Utara: 494.4547
    → MAPE untuk Bawang Putih Bonggol - Sumatera Utara: 0.0125

🚀 Mengolah komoditas: Beras Medium
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Beras Medium - Aceh: 127.5069
    → MAPE untuk Beras Medium - Aceh: 0.0095
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Beras Medium - Bali: 165.6834
    → MAPE untuk Beras Medium - Bali: 0.0120
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Beras Medium - Banten: 176.9694
    → MAPE untuk Beras Medium - Banten: 0.0141
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Beras Medium - Bengkulu: 69.3143
    → MAPE untuk Beras Medium - Bengkulu: 0.0051
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Beras Medium - DI Yogyakarta: 115.5427
    → MAPE untuk Beras Medium - DI Yogyakarta: 0.0089
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Beras Medium - DKI Jakarta: 523.2592
    → MAPE untuk Beras Medium - DKI Jakarta: 0.0379
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Beras Medium - Gorontalo: 442.1285
    → MAPE untuk Beras Medium - Gorontalo: 0.0321
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Beras Medium - Jambi: 413.0138
    → MAPE untuk Beras Medium - Jambi: 0.0317
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Beras Medium - Jawa Barat: 92.5127
    → MAPE untuk Beras Medium - Jawa Barat: 0.0072
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Beras Medium - Jawa Tengah: 130.1840
    → MAPE untuk Beras Medium - Jawa Tengah: 0.0100
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Beras Medium - Jawa Timur: 103.7829
    → MAPE untuk Beras Medium - Jawa Timur: 0.0084
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Beras Medium - Kalimantan Barat: 260.2747
    → MAPE untuk Beras Medium - Kalimantan Barat: 0.0175
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Beras Medium - Kalimantan Selatan: 212.9969
    → MAPE untuk Beras Medium - Kalimantan Selatan: 0.0164
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Beras Medium - Kalimantan Tengah: 262.2022
    → MAPE untuk Beras Medium - Kalimantan Tengah: 0.0185
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Beras Medium - Kalimantan Timur: 151.2856
    → MAPE untuk Beras Medium - Kalimantan Timur: 0.0095
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Beras Medium - Kalimantan Utara: 270.6104
    → MAPE untuk Beras Medium - Kalimantan Utara: 0.0176
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...
    → MAE untuk Beras Medium - Kepulauan Bangka Belitung: 356.7050
    → MAPE untuk Beras Medium - Kepulauan Bangka Belitung: 0.0251
  → Menggabungkan data untuk provinsi: Kepulauan Riau...
    → MAE untuk Beras Medium - Kepulauan Riau: 282.4762
    → MAPE untuk Beras Medium - Kepulauan Riau: 0.0200
  → Menggabungkan data untuk provinsi: Lampung...
    → MAE untuk Beras Medium - Lampung: 89.5026
    → MAPE untuk Beras Medium - Lampung: 0.0070
  → Menggabungkan data untuk provinsi: Maluku Utara...
    → MAE untuk Beras Medium - Maluku Utara: 978.9301
    → MAPE untuk Beras Medium - Maluku Utara: 0.0619
  → Menggabungkan data untuk provinsi: Maluku...
    → MAE untuk Beras Medium - Maluku: 516.2418
    → MAPE untuk Beras Medium - Maluku: 0.0352
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...
    → MAE untuk Beras Medium - Nusa Tenggara Barat: 195.1513
    → MAPE untuk Beras Medium - Nusa Tenggara Barat: 0.0152
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...
    → MAE untuk Beras Medium - Nusa Tenggara Timur: 302.3951
    → MAPE untuk Beras Medium - Nusa Tenggara Timur: 0.0224
  → Menggabungkan data untuk provinsi: Papua Barat...
    → MAE untuk Beras Medium - Papua Barat: 345.4175
    → MAPE untuk Beras Medium - Papua Barat: 0.0220
  → Menggabungkan data untuk provinsi: Papua...
    → MAE untuk Beras Medium - Papua: 424.0346
    → MAPE untuk Beras Medium - Papua: 0.0273
  → Menggabungkan data untuk provinsi: Riau...
    → MAE untuk Beras Medium - Riau: 515.0834
    → MAPE untuk Beras Medium - Riau: 0.0371
  → Menggabungkan data untuk provinsi: Sulawesi Barat...
    → MAE untuk Beras Medium - Sulawesi Barat: 325.6225
    → MAPE untuk Beras Medium - Sulawesi Barat: 0.0248
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...
    → MAE untuk Beras Medium - Sulawesi Selatan: 65.7497
    → MAPE untuk Beras Medium - Sulawesi Selatan: 0.0052
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...
    → MAE untuk Beras Medium - Sulawesi Tengah: 424.7767
    → MAPE untuk Beras Medium - Sulawesi Tengah: 0.0316
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...
    → MAE untuk Beras Medium - Sulawesi Tenggara: 305.5895
    → MAPE untuk Beras Medium - Sulawesi Tenggara: 0.0234
  → Menggabungkan data untuk provinsi: Sulawesi Utara...
    → MAE untuk Beras Medium - Sulawesi Utara: 126.4893
    → MAPE untuk Beras Medium - Sulawesi Utara: 0.0095
  → Menggabungkan data untuk provinsi: Sumatera Barat...
    → MAE untuk Beras Medium - Sumatera Barat: 131.1042
    → MAPE untuk Beras Medium - Sumatera Barat: 0.0087
  → Menggabungkan data untuk provinsi: Sumatera Selatan...
    → MAE untuk Beras Medium - Sumatera Selatan: 125.0315
    → MAPE untuk Beras Medium - Sumatera Selatan: 0.0102
  → Menggabungkan data untuk provinsi: Sumatera Utara...
    → MAE untuk Beras Medium - Sumatera Utara: 80.1383
    → MAPE untuk Beras Medium - Sumatera Utara: 0.0057

🚀 Mengolah komoditas: Beras Premium
  → Menggabungkan data untuk provinsi: Aceh...
    → MAE untuk Beras Premium - Aceh: 121.7766
    → MAPE untuk Beras Premium - Aceh: 0.0084
  → Menggabungkan data untuk provinsi: Bali...
    → MAE untuk Beras Premium - Bali: 100.7470
    → MAPE untuk Beras Premium - Bali: 0.0066
  → Menggabungkan data untuk provinsi: Banten...
    → MAE untuk Beras Premium - Banten: 217.1946
    → MAPE untuk Beras Premium - Banten: 0.0148
  → Menggabungkan data untuk provinsi: Bengkulu...
    → MAE untuk Beras Premium - Bengkulu: 106.1249
    → MAPE untuk Beras Premium - Bengkulu: 0.0069
  → Menggabungkan data untuk provinsi: DI Yogyakarta...
    → MAE untuk Beras Premium - DI Yogyakarta: 156.5043
    → MAPE untuk Beras Premium - DI Yogyakarta: 0.0107
  → Menggabungkan data untuk provinsi: DKI Jakarta...
    → MAE untuk Beras Premium - DKI Jakarta: 379.0701
    → MAPE untuk Beras Premium - DKI Jakarta: 0.0239
  → Menggabungkan data untuk provinsi: Gorontalo...
    → MAE untuk Beras Premium - Gorontalo: 1439.6602
    → MAPE untuk Beras Premium - Gorontalo: 0.0943
  → Menggabungkan data untuk provinsi: Jambi...
    → MAE untuk Beras Premium - Jambi: 170.6029
    → MAPE untuk Beras Premium - Jambi: 0.0116
  → Menggabungkan data untuk provinsi: Jawa Barat...
    → MAE untuk Beras Premium - Jawa Barat: 421.0832
    → MAPE untuk Beras Premium - Jawa Barat: 0.0284
  → Menggabungkan data untuk provinsi: Jawa Tengah...
    → MAE untuk Beras Premium - Jawa Tengah: 157.9029
    → MAPE untuk Beras Premium - Jawa Tengah: 0.0106
  → Menggabungkan data untuk provinsi: Jawa Timur...
    → MAE untuk Beras Premium - Jawa Timur: 308.9443
    → MAPE untuk Beras Premium - Jawa Timur: 0.0211
  → Menggabungkan data untuk provinsi: Kalimantan Barat...
    → MAE untuk Beras Premium - Kalimantan Barat: 125.1831
    → MAPE untuk Beras Premium - Kalimantan Barat: 0.0073
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...
    → MAE untuk Beras Premium - Kalimantan Selatan: 283.7900
    → MAPE untuk Beras Premium - Kalimantan Selatan: 0.0172
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...
    → MAE untuk Beras Premium - Kalimantan Tengah: 177.7645
    → MAPE untuk Beras Premium - Kalimantan Tengah: 0.0102
  → Menggabungkan data untuk provinsi: Kalimantan Timur...
    → MAE untuk Beras Premium - Kalimantan Timur: 136.7693
    → MAPE untuk Beras Premium - Kalimantan Timur: 0.0078
  → Menggabungkan data untuk provinsi: Kalimantan Utara...
    → MAE untuk Beras Premium - Kalimantan Utara: 400.9370
    → MAPE untuk Beras Premium - Kalimantan Utara: 0.0230
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

🚀 Mengolah komoditas: Bawang Merah
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Aceh: 0.0267
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Bali: 0.0364
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Banten: 0.0534
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Bengkulu: 0.0201
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - DI Yogyakarta: 0.0564
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - DKI Jakarta: 0.0472
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Gorontalo: 0.0437
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Jambi: 0.0282
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Jawa Barat: 0.0354
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Jawa Tengah: 0.0462
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Jawa Timur: 0.0524
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Kalimantan Barat: 0.0369
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Kalimantan Selatan: 0.0409
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Kalimantan Tengah: 0.0209
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Kalimantan Timur: 0.0375
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Kalimantan Utara: 0.0232
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Kepulauan Bangka Belitung: 0.0441
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Kepulauan Riau: 0.0267
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Lampung: 0.0541
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Maluku Utara: 0.0322
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Maluku: 0.0315
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Nusa Tenggara Barat: 0.0598
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Nusa Tenggara Timur: 0.0288
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Papua Barat: 0.0548
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Papua: 0.0226
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Riau: 0.0299
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Sulawesi Barat: 0.0316
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Sulawesi Selatan: 0.0360
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Sulawesi Tengah: 0.0413
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Sulawesi Tenggara: 0.0222
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Sulawesi Utara: 0.0239
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Sumatera Barat: 0.0452
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Sumatera Selatan: 0.0523
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Merah - Sumatera Utara: 0.0223

🚀 Mengolah komoditas: Bawang Putih Bonggol
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Aceh: 0.0095
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Bali: 0.0279
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Banten: 0.0190
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Bengkulu: 0.0199
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - DI Yogyakarta: 0.0126
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - DKI Jakarta: 0.0233
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Gorontalo: 0.0360
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Jambi: 0.0158
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Jawa Barat: 0.0245
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Jawa Tengah: 0.0176
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Jawa Timur: 0.0120
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Kalimantan Barat: 0.0287
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Kalimantan Selatan: 0.0266
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Kalimantan Tengah: 0.0232
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Kalimantan Timur: 0.0276
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Kalimantan Utara: 0.0249
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Kepulauan Bangka Belitung: 0.0188
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Kepulauan Riau: 0.0186
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Lampung: 0.0251
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Maluku Utara: 0.0374
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Maluku: 0.0333
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Nusa Tenggara Barat: 0.0245
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Nusa Tenggara Timur: 0.0301
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Papua Barat: 0.0222
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Papua: 0.0359
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Riau: 0.0165
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Sulawesi Barat: 0.0184
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Sulawesi Selatan: 0.0118
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Sulawesi Tengah: 0.0200
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Sulawesi Tenggara: 0.0243
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Sulawesi Utara: 0.0340
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Sumatera Barat: 0.0119
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Sumatera Selatan: 0.0220
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Bawang Putih Bonggol - Sumatera Utara: 0.0128

🚀 Mengolah komoditas: Beras Medium
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Aceh: 0.0111
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Bali: 0.0151
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Banten: 0.0140
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Bengkulu: 0.0047
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - DI Yogyakarta: 0.0077
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - DKI Jakarta: 0.0150
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Gorontalo: 0.0096
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Jambi: 0.0089
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Jawa Barat: 0.0080
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Jawa Tengah: 0.0137
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Jawa Timur: 0.0060
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Kalimantan Barat: 0.0109
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Kalimantan Selatan: 0.0102
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Kalimantan Tengah: 0.0154
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Kalimantan Timur: 0.0077
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Kalimantan Utara: 0.0152
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Kepulauan Bangka Belitung: 0.0143
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Kepulauan Riau: 0.0197
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Lampung: 0.0041
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Maluku Utara: 0.0095
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Maluku: 0.0228
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Nusa Tenggara Barat: 0.0154
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Nusa Tenggara Timur: 0.0106
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Papua Barat: 0.0094
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Papua: 0.0080
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Riau: 0.0209
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Sulawesi Barat: 0.0158
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Sulawesi Selatan: 0.0048
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Sulawesi Tengah: 0.0121
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Sulawesi Tenggara: 0.0083
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Sulawesi Utara: 0.0097
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Sumatera Barat: 0.0080
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Sumatera Selatan: 0.0161
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Medium - Sumatera Utara: 0.0051

🚀 Mengolah komoditas: Beras Premium
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Aceh: 0.0060
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Bali: 0.0082
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Banten: 0.0101
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Bengkulu: 0.0079
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - DI Yogyakarta: 0.0133
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - DKI Jakarta: 0.0153
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Gorontalo: 0.0108
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Jambi: 0.0084
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Jawa Barat: 0.0084
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Jawa Tengah: 0.0139
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Jawa Timur: 0.0208
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Kalimantan Barat: 0.0085
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Kalimantan Selatan: 0.0094
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Kalimantan Tengah: 0.0078
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Kalimantan Timur: 0.0094
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Kalimantan Utara: 0.0128
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Kepulauan Bangka Belitung: 0.0066
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Kepulauan Riau: 0.0215
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Lampung: 0.0052
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Maluku Utara: 0.0067
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Maluku: 0.0115
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Nusa Tenggara Barat: 0.0136
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Nusa Tenggara Timur: 0.0060
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Papua Barat: 0.0184
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Papua: 0.0103
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Riau: 0.0076
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Sulawesi Barat: 0.0068
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Sulawesi Selatan: 0.0044
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Sulawesi Tengah: 0.0060
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Sulawesi Tenggara: 0.0084
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Sulawesi Utara: 0.0136
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Sumatera Barat: 0.0077
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Sumatera Selatan: 0.0115
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Beras Premium - Sumatera Utara: 0.0031

🚀 Mengolah komoditas: Cabai Merah Keriting
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Aceh: 0.0797
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Bali: 0.0620
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Banten: 0.0817
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Bengkulu: 0.0845
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - DI Yogyakarta: 0.0982
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - DKI Jakarta: 0.0700
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Gorontalo: 0.0914
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Jambi: 0.0955
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Jawa Barat: 0.0545
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Jawa Tengah: 0.0713
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Jawa Timur: 0.0827
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Kalimantan Barat: 0.0372
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Kalimantan Selatan: 0.0617
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Kalimantan Tengah: 0.0432
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Kalimantan Timur: 0.0797
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Kalimantan Utara: 0.0279
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Kepulauan Bangka Belitung: 0.0846
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Kepulauan Riau: 0.0601
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Lampung: 0.0752
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Maluku Utara: 0.0586
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Maluku: 0.0698
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Nusa Tenggara Barat: 0.0724
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Nusa Tenggara Timur: 0.0335
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Papua Barat: 0.0432
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Papua: 0.0434
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Riau: 0.0468
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Sulawesi Barat: 0.0641
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Sulawesi Selatan: 0.0606
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Sulawesi Tengah: 0.0514
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Sulawesi Tenggara: 0.0604
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Sulawesi Utara: 0.0720
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Sumatera Barat: 0.0816
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Sumatera Selatan: 0.0801
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Merah Keriting - Sumatera Utara: 0.0896

🚀 Mengolah komoditas: Cabai Rawit Merah
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Aceh: 0.0436
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Bali: 0.0983
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Banten: 0.0680
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Bengkulu: 0.0591
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - DI Yogyakarta: 0.0996
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - DKI Jakarta: 0.0675
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Gorontalo: 0.0994
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Jambi: 0.0543
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Jawa Barat: 0.0650
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Jawa Tengah: 0.0770
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Jawa Timur: 0.1030
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Kalimantan Barat: 0.0446
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Kalimantan Selatan: 0.0622
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Kalimantan Tengah: 0.0511
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Kalimantan Timur: 0.0579
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Kalimantan Utara: 0.0505
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Kepulauan Bangka Belitung: 0.0710
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Kepulauan Riau: 0.0441
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Lampung: 0.0570
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Maluku Utara: 0.0757
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Maluku: 0.1022
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Nusa Tenggara Barat: 0.0761
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Nusa Tenggara Timur: 0.0446
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Papua Barat: 0.0625
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Papua: 0.0583
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Riau: 0.0789
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Sulawesi Barat: 0.0518
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Sulawesi Selatan: 0.0614
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Sulawesi Tengah: 0.0697
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Sulawesi Tenggara: 0.0493
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Sulawesi Utara: 0.0926
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Sumatera Barat: 0.0608
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Sumatera Selatan: 0.0706
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Cabai Rawit Merah - Sumatera Utara: 0.0728

🚀 Mengolah komoditas: Daging Ayam Ras
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Aceh: 0.0115
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Bali: 0.0119
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Banten: 0.0158
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Bengkulu: 0.0431
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - DI Yogyakarta: 0.0225
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - DKI Jakarta: 0.0173
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Gorontalo: 0.0180
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Jambi: 0.0302
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Jawa Barat: 0.0165
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Jawa Tengah: 0.0157
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Jawa Timur: 0.0170
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Kalimantan Barat: 0.0170
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Kalimantan Selatan: 0.0342
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Kalimantan Tengah: 0.0184
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Kalimantan Timur: 0.0332
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Kalimantan Utara: 0.0183
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Kepulauan Bangka Belitung: 0.0201
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Kepulauan Riau: 0.0158
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Lampung: 0.0142
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Maluku Utara: 0.0153
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Maluku: 0.0122
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Nusa Tenggara Barat: 0.0121
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Nusa Tenggara Timur: 0.0124
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Papua Barat: 0.0220
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Papua: 0.0149
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Riau: 0.0291
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Sulawesi Barat: 0.0147
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Sulawesi Selatan: 0.0175
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Sulawesi Tengah: 0.0223
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Sulawesi Tenggara: 0.0274
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Sulawesi Utara: 0.0134
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Sumatera Barat: 0.0222
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Sumatera Selatan: 0.0201
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Ayam Ras - Sumatera Utara: 0.0161

🚀 Mengolah komoditas: Daging Sapi Murni
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Aceh: 0.0088
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Bali: 0.0062
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Banten: 0.0071
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Bengkulu: 0.0118
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - DI Yogyakarta: 0.0065
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - DKI Jakarta: 0.0097
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Gorontalo: 0.0031
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Jambi: 0.0034
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Jawa Barat: 0.0067
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Jawa Tengah: 0.0039
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Jawa Timur: 0.0066
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Kalimantan Barat: 0.0039
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Kalimantan Selatan: 0.0072
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Kalimantan Tengah: 0.0049
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Kalimantan Timur: 0.0074
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Kalimantan Utara: 0.0071
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Kepulauan Bangka Belitung: 0.0051
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Kepulauan Riau: 0.0146
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Lampung: 0.0037
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Maluku Utara: 0.0139
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Maluku: 0.0225
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Nusa Tenggara Barat: 0.0047
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Nusa Tenggara Timur: 0.0079
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Papua Barat: 0.0191
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Papua: 0.0099
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Riau: 0.0051
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Sulawesi Barat: 0.0062
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Sulawesi Selatan: 0.0037
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Sulawesi Tengah: 0.0069
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Sulawesi Tenggara: 0.0065
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Sulawesi Utara: 0.0045
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Sumatera Barat: 0.0050
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Sumatera Selatan: 0.0056
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Daging Sapi Murni - Sumatera Utara: 0.0095

🚀 Mengolah komoditas: Gula Konsumsi
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Aceh: 0.0052
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Bali: 0.0076
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Banten: 0.0079
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Bengkulu: 0.0061
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - DI Yogyakarta: 0.0084
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - DKI Jakarta: 0.0116
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Gorontalo: 0.0140
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Jambi: 0.0075
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Jawa Barat: 0.0034
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Jawa Tengah: 0.0074
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Jawa Timur: 0.0070
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Kalimantan Barat: 0.0048
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Kalimantan Selatan: 0.0125
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Kalimantan Tengah: 0.0049
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Kalimantan Timur: 0.0117
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Kalimantan Utara: 0.0083
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Kepulauan Bangka Belitung: 0.0085
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Kepulauan Riau: 0.0145
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Lampung: 0.0030
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Maluku Utara: 0.0058
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Maluku: 0.0085
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Nusa Tenggara Barat: 0.0055
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Nusa Tenggara Timur: 0.0070
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Papua Barat: 0.0098
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Papua: 0.0044
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Riau: 0.0062
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Sulawesi Barat: 0.0054
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Sulawesi Selatan: 0.0040
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Sulawesi Tengah: 0.0074
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Sulawesi Tenggara: 0.0086
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Sulawesi Utara: 0.0085
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Sumatera Barat: 0.0046
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Sumatera Selatan: 0.0031
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Gula Konsumsi - Sumatera Utara: 0.0044

🚀 Mengolah komoditas: Minyak Goreng Curah
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Aceh: 0.0084
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Bali: 0.0089
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Banten: 0.0117
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Bengkulu: 0.0160
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - DI Yogyakarta: 0.0121
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - DKI Jakarta: 0.0092
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Gorontalo: 0.0242
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Jambi: 0.0039
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Jawa Barat: 0.0058
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Jawa Tengah: 0.0077
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Jawa Timur: 0.0067
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Kalimantan Barat: 0.0108
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Kalimantan Selatan: 0.0104
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Kalimantan Tengah: 0.0065
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Kalimantan Timur: 0.0197
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Kalimantan Utara: 0.0148
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Kepulauan Bangka Belitung: 0.0118
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Kepulauan Riau: 0.0164
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Lampung: 0.0128
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Maluku Utara: 0.0313
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Maluku: 0.0261
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Nusa Tenggara Barat: 0.0107
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Nusa Tenggara Timur: 0.0199
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Papua Barat: 0.0351
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Papua: 0.0229
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Riau: 0.0073
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Sulawesi Barat: 0.0115
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Sulawesi Selatan: 0.0066
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Sulawesi Tengah: 0.0172
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Sulawesi Tenggara: 0.0154
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Sulawesi Utara: 0.0159
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Sumatera Barat: 0.0064
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Sumatera Selatan: 0.0071
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Curah - Sumatera Utara: 0.0089

🚀 Mengolah komoditas: Minyak Goreng Kemasan Sederhana
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Aceh: 0.0092
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Bali: 0.0090
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Banten: 0.0169
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Bengkulu: 0.0078
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - DI Yogyakarta: 0.0097
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - DKI Jakarta: 0.0063
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Gorontalo: 0.0083
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Jambi: 0.0054
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Jawa Barat: 0.0092
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Jawa Tengah: 0.0068
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Jawa Timur: 0.0106
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Kalimantan Barat: 0.0080
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Kalimantan Selatan: 0.0161
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Kalimantan Tengah: 0.0065
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Kalimantan Timur: 0.0150
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Kalimantan Utara: 0.0100
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Kepulauan Bangka Belitung: 0.0151
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Kepulauan Riau: 0.0146
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Lampung: 0.0076
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Maluku Utara: 0.0168
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Maluku: 0.0181
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Nusa Tenggara Barat: 0.0151
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Nusa Tenggara Timur: 0.0096
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Papua Barat: 0.0390
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Papua: 0.0151
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Riau: 0.0107
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Sulawesi Barat: 0.0149
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Sulawesi Selatan: 0.0063
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Sulawesi Tengah: 0.0121
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Sulawesi Tenggara: 0.0082
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Sulawesi Utara: 0.0087
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Sumatera Barat: 0.0090
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Sumatera Selatan: 0.0059
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Minyak Goreng Kemasan Sederhana - Sumatera Utara: 0.0110

🚀 Mengolah komoditas: Telur Ayam Ras
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Aceh: 0.0113
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Bali: 0.0196
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Banten: 0.0227
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Bengkulu: 0.0147
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - DI Yogyakarta: 0.0173
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - DKI Jakarta: 0.0222
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Gorontalo: 0.0152
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Jambi: 0.0087
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Jawa Barat: 0.0128
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Jawa Tengah: 0.0164
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Jawa Timur: 0.0155
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Kalimantan Barat: 0.0139
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Kalimantan Selatan: 0.0092
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Kalimantan Tengah: 0.0091
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Kalimantan Timur: 0.0273
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Kalimantan Utara: 0.0201
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Kepulauan Bangka Belitung: 0.0133
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Kepulauan Riau: 0.0147
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Lampung: 0.0116
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Maluku Utara: 0.0174
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Maluku: 0.0225
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Nusa Tenggara Barat: 0.0122
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Nusa Tenggara Timur: 0.0120
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Papua Barat: 0.0215
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Papua: 0.0135
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Riau: 0.0133
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Sulawesi Barat: 0.0159
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Sulawesi Selatan: 0.0105
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Sulawesi Tengah: 0.0152
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Sulawesi Tenggara: 0.0175
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Sulawesi Utara: 0.0176
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Sumatera Barat: 0.0086
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Sumatera Selatan: 0.0130
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Telur Ayam Ras - Sumatera Utara: 0.0082

🚀 Mengolah komoditas: Tepung Terigu (Curah)
  → Menggabungkan data untuk provinsi: Aceh...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Aceh: 0.0057
  → Menggabungkan data untuk provinsi: Bali...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Bali: 0.0115
  → Menggabungkan data untuk provinsi: Banten...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Banten: 0.0077
  → Menggabungkan data untuk provinsi: Bengkulu...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Bengkulu: 0.0074
  → Menggabungkan data untuk provinsi: DI Yogyakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - DI Yogyakarta: 0.0168
  → Menggabungkan data untuk provinsi: DKI Jakarta...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - DKI Jakarta: 0.0123
  → Menggabungkan data untuk provinsi: Gorontalo...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Gorontalo: 0.0179
  → Menggabungkan data untuk provinsi: Jambi...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Jambi: 0.0050
  → Menggabungkan data untuk provinsi: Jawa Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Jawa Barat: 0.0076
  → Menggabungkan data untuk provinsi: Jawa Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Jawa Tengah: 0.0097
  → Menggabungkan data untuk provinsi: Jawa Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Jawa Timur: 0.0098
  → Menggabungkan data untuk provinsi: Kalimantan Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Kalimantan Barat: 0.0082
  → Menggabungkan data untuk provinsi: Kalimantan Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Kalimantan Selatan: 0.0151
  → Menggabungkan data untuk provinsi: Kalimantan Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Kalimantan Tengah: 0.0061
  → Menggabungkan data untuk provinsi: Kalimantan Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Kalimantan Timur: 0.0368
  → Menggabungkan data untuk provinsi: Kalimantan Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Kalimantan Utara: 0.0158
  → Menggabungkan data untuk provinsi: Kepulauan Bangka Belitung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Kepulauan Bangka Belitung: 0.0087
  → Menggabungkan data untuk provinsi: Kepulauan Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Kepulauan Riau: 0.0227
  → Menggabungkan data untuk provinsi: Lampung...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Lampung: 0.0063
  → Menggabungkan data untuk provinsi: Maluku Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Maluku Utara: 0.0096
  → Menggabungkan data untuk provinsi: Maluku...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Maluku: 0.0156
  → Menggabungkan data untuk provinsi: Nusa Tenggara Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Nusa Tenggara Barat: 0.0127
  → Menggabungkan data untuk provinsi: Nusa Tenggara Timur...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Nusa Tenggara Timur: 0.0140
  → Menggabungkan data untuk provinsi: Papua Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Papua Barat: 0.0236
  → Menggabungkan data untuk provinsi: Papua...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Papua: 0.0111
  → Menggabungkan data untuk provinsi: Riau...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Riau: 0.0112
  → Menggabungkan data untuk provinsi: Sulawesi Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Sulawesi Barat: 0.0101
  → Menggabungkan data untuk provinsi: Sulawesi Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Sulawesi Selatan: 0.0110
  → Menggabungkan data untuk provinsi: Sulawesi Tengah...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Sulawesi Tengah: 0.0116
  → Menggabungkan data untuk provinsi: Sulawesi Tenggara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Sulawesi Tenggara: 0.0101
  → Menggabungkan data untuk provinsi: Sulawesi Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Sulawesi Utara: 0.0083
  → Menggabungkan data untuk provinsi: Sumatera Barat...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Sumatera Barat: 0.0129
  → Menggabungkan data untuk provinsi: Sumatera Selatan...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Sumatera Selatan: 0.0096
  → Menggabungkan data untuk provinsi: Sumatera Utara...

/tmp/ipykernel_249124/3800958647.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_prov["MA7"] = df_prov["y"].rolling(window=7, min_periods=1).mean().shift(1).fillna(method='bfill')

    → Best MAPE untuk Tepung Terigu (Curah) - Sumatera Utara: 0.0095

✅ Hasil prediksi disimpan dalam 'submission_xgboost_ma_rolling.csv'

In [42]:
avg_mape = np.mean(mape_scores)avg_mape = np.mean(mape_scores)
print(f"\n📊 Rata-rata MAPE keseluruhan: {avg_mape:.4f}")
print(f"\n📊 Rata-rata MAPE keseluruhan: {avg_mape:.4f}")

📊 Rata-rata MAPE keseluruhan: nan

/home/sirius/Documents/DS/myenv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/sirius/Documents/DS/myenv/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

🚀 Mengolah komoditas: Bawang Merah
  → Menggabungkan data untuk provinsi: Aceh...

ValueError: Cannot have number of folds=6 greater than the number of samples=0.

In [57]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error
from sklearn.preprocessing import StandardScaler


SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Dictionary untuk menyimpan model dan prediksi
models = {}
predictions = []
mape_scores = []
predict_start = "2024-10-01"
predict_end = "2024-12-31"

# Buat daftar tanggal untuk prediksi
future_dates = pd.date_range(start=predict_start, end=predict_end)

# Definisikan model LSTM
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(LSTMModel, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        
        out, _ = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :])
        return out

# Fungsi untuk melatih model LSTM
def train_lstm(model, train_loader, val_loader, criterion, optimizer, num_epochs=100):
    model.train()
    for epoch in range(num_epochs):
        # Training
        model.train()
        train_loss = 0
        for inputs, targets in train_loader:
            inputs, targets = inputs.to(device), targets.to(device)
            
            # Forward pass
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            
            # Backward pass dan optimasi
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
        
        # Validation
        model.eval()
        val_loss = 0
        val_mape = 0
        with torch.no_grad():
            for inputs, targets in val_loader:
                inputs, targets = inputs.to(device), targets.to(device)
                outputs = model(inputs)
                val_loss += criterion(outputs, targets).item()
                
                # Hitung MAPE
                y_pred = scaler_y.inverse_transform(outputs.cpu().numpy())
                y_true = scaler_y.inverse_transform(targets.cpu().numpy())
                val_mape += mean_absolute_percentage_error(y_true, y_pred)
        
        # Hitung rata-rata loss dan MAPE
        train_loss /= len(train_loader)
        val_loss /= len(val_loader)
        val_mape /= len(val_loader)
        
        # Tampilkan hasil setiap epoch
        print(f'Epoch [{epoch+1}/{num_epochs}], Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}, Val MAPE: {val_mape:.4f}')

# Loop setiap komoditas dalam df_dict
for komoditas, df_komoditas in df_dict.items():
    print(f"\n🚀 Mengolah komoditas: {komoditas}")

    # Drop kolom "Date" jika ada
    if "Date" in df_komoditas.columns:
        df_komoditas = df_komoditas.drop(columns=["Date"])

    # Loop setiap provinsi dalam df_komoditas
    for provinsi in df_komoditas.columns:
        print(f"  → Menggabungkan data untuk provinsi: {provinsi}...")

        # Ambil hanya data provinsi tersebut
        df_prov = df_komoditas[[provinsi]].rename(columns={provinsi: 'y'})

        # Gabungkan dengan PCA Global dan PCA Exchange
        df_merged = pd.concat([df_prov, df_PCA_global, df_PCA_exchange], axis=1)

        # Pisahkan fitur (X) dan target harga (y)
        X = df_merged.iloc[:, 1:].values  # Semua kolom kecuali harga komoditas
        y = df_merged.iloc[:, 0].values   # Kolom pertama sebagai target

        # Normalisasi data
        scaler_X = StandardScaler()
        scaler_y = StandardScaler()
        X = scaler_X.fit_transform(X)
        y = scaler_y.fit_transform(y.reshape(-1, 1))

        # Pisahkan training & testing
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

        # Konversi ke PyTorch tensors
        X_train = torch.FloatTensor(X_train).unsqueeze(1)
        y_train = torch.FloatTensor(y_train)
        X_test = torch.FloatTensor(X_test).unsqueeze(1)
        y_test = torch.FloatTensor(y_test)

        # Buat DataLoader
        train_data = TensorDataset(X_train, y_train)
        train_loader = DataLoader(train_data, batch_size=32, shuffle=False)
        val_data = TensorDataset(X_test, y_test)
        val_loader = DataLoader(val_data, batch_size=32, shuffle=False)

        # Inisialisasi model LSTM
        input_size = X_train.shape[2]
        hidden_size = 50
        num_layers = 2
        output_size = 1
        model = LSTMModel(input_size, hidden_size, num_layers, output_size).to(device)

        # Definisikan loss function dan optimizer
        criterion = nn.HuberLoss()
        optimizer = optim.Adam(model.parameters(), lr=0.01)

        # Latih model
        train_lstm(model, train_loader, val_loader, criterion, optimizer, num_epochs=100)

        # Simpan model
        models[(komoditas, provinsi)] = model

        # Evaluasi model
        model.eval()
        with torch.no_grad():
            y_pred = model(X_test.to(device))
            y_pred = scaler_y.inverse_transform(y_pred.cpu().numpy())
            y_test_actual = scaler_y.inverse_transform(y_test.numpy())
            
            mae = mean_absolute_error(y_test_actual, y_pred)
            mape = mean_absolute_percentage_error(y_test_actual, y_pred)
            mape_scores.append(mape)  # Simpan MAPE
            print(f"    → MAE untuk {komoditas} - {provinsi}: {mae:.4f}")
            print(f"    → MAPE untuk {komoditas} - {provinsi}: {mape:.4f}")

        # Mulai prediksi ke masa depan dengan iterasi (mirip LSTM)
        last_known_data = X[-1, :].reshape(1, 1, -1)  # Ambil data terakhir
        last_known_data = torch.FloatTensor(last_known_data).to(device)
        future_preds = []

        for _ in range(len(future_dates)):
            with torch.no_grad():
                next_pred = model(last_known_data).cpu().numpy()[0][0]
                next_pred = scaler_y.inverse_transform(np.array([[next_pred]]))[0][0]
                future_preds.append(next_pred)

                # Update last_known_data → gantikan harga sebelumnya dengan prediksi baru
                last_known_data = torch.roll(last_known_data, -1, dims=2)
                
                # Konversi nilai prediksi ke tensor dan pastikan berada di perangkat yang sama
                next_pred_scaled = scaler_y.transform(np.array([[next_pred]]))[0][0]
                next_pred_tensor = torch.tensor([next_pred_scaled], dtype=torch.float32).to(device)
                
                last_known_data[0, 0, -1] = next_pred_tensor

        # Simpan hasil prediksi ke dalam list
        for date, pred in zip(future_dates, future_preds):
            predictions.append({
                'id': f"{komoditas}/{provinsi}/{date.strftime('%Y-%m-%d')}",
                'price': pred  
            })

# Hitung rata-rata MAPE
avg_mape = np.mean(mape_scores)
print(f"\n📊 Rata-rata MAPE untuk semua model: {avg_mape:.4f}")

# Simpan hasil prediksi ke CSV
submission_df = pd.DataFrame(predictions)
submission_df.to_csv('submission_lstm_pytorch.csv', index=False)
print("\n✅ Hasil prediksi disimpan dalam 'submission_lstm_pytorch.csv'")

🚀 Mengolah komoditas: Bawang Merah
  → Menggabungkan data untuk provinsi: Aceh...
Epoch [1/100], Train Loss: 0.2746, Val Loss: 0.8691, Val MAPE: 0.2617
Epoch [2/100], Train Loss: 0.2314, Val Loss: 0.8989, Val MAPE: 0.2686
Epoch [3/100], Train Loss: 0.1477, Val Loss: 0.8883, Val MAPE: 0.2866
Epoch [4/100], Train Loss: 0.1927, Val Loss: 0.8313, Val MAPE: 0.2695
Epoch [5/100], Train Loss: 0.2460, Val Loss: 0.8088, Val MAPE: 0.2382
Epoch [6/100], Train Loss: 0.1892, Val Loss: 0.8650, Val MAPE: 0.2519
Epoch [7/100], Train Loss: 0.1271, Val Loss: 0.9495, Val MAPE: 0.2963
Epoch [8/100], Train Loss: 0.1710, Val Loss: 0.8973, Val MAPE: 0.2757
Epoch [9/100], Train Loss: 0.1512, Val Loss: 0.9135, Val MAPE: 0.2842
Epoch [10/100], Train Loss: 0.1486, Val Loss: 0.8720, Val MAPE: 0.2825
Epoch [11/100], Train Loss: 0.1880, Val Loss: 0.8892, Val MAPE: 0.2744
Epoch [12/100], Train Loss: 0.0941, Val Loss: 1.0180, Val MAPE: 0.2935
Epoch [13/100], Train Loss: 0.1198, Val Loss: 0.9942, Val MAPE: 0.2998
Epoch [14/100], Train Loss: 0.0692, Val Loss: 0.9203, Val MAPE: 0.2826
Epoch [15/100], Train Loss: 0.1476, Val Loss: 0.9052, Val MAPE: 0.2867
Epoch [16/100], Train Loss: 0.1193, Val Loss: 0.9196, Val MAPE: 0.2877
Epoch [17/100], Train Loss: 0.0612, Val Loss: 0.9473, Val MAPE: 0.2946
Epoch [18/100], Train Loss: 0.0522, Val Loss: 0.9175, Val MAPE: 0.2845
Epoch [19/100], Train Loss: 0.1353, Val Loss: 0.8783, Val MAPE: 0.2835
Epoch [20/100], Train Loss: 0.0853, Val Loss: 0.9402, Val MAPE: 0.2887
Epoch [21/100], Train Loss: 0.0607, Val Loss: 0.9346, Val MAPE: 0.2946
Epoch [22/100], Train Loss: 0.1134, Val Loss: 0.9049, Val MAPE: 0.2790
Epoch [23/100], Train Loss: 0.1367, Val Loss: 0.9002, Val MAPE: 0.2858
Epoch [24/100], Train Loss: 0.1313, Val Loss: 0.8918, Val MAPE: 0.2702
Epoch [25/100], Train Loss: 0.1223, Val Loss: 0.9213, Val MAPE: 0.2933
Epoch [26/100], Train Loss: 0.1029, Val Loss: 0.9105, Val MAPE: 0.2835
Epoch [27/100], Train Loss: 0.0622, Val Loss: 0.9246, Val MAPE: 0.2894
Epoch [28/100], Train Loss: 0.0512, Val Loss: 0.9035, Val MAPE: 0.2880
Epoch [29/100], Train Loss: 0.1206, Val Loss: 0.9000, Val MAPE: 0.2887
Epoch [30/100], Train Loss: 0.0718, Val Loss: 0.8395, Val MAPE: 0.2749
Epoch [31/100], Train Loss: 0.0633, Val Loss: 0.8523, Val MAPE: 0.2736
Epoch [32/100], Train Loss: 0.0738, Val Loss: 0.8539, Val MAPE: 0.2758
Epoch [33/100], Train Loss: 0.1233, Val Loss: 0.8573, Val MAPE: 0.2793
Epoch [34/100], Train Loss: 0.1024, Val Loss: 0.8327, Val MAPE: 0.2738
Epoch [35/100], Train Loss: 0.0658, Val Loss: 0.8130, Val MAPE: 0.2662
Epoch [36/100], Train Loss: 0.0340, Val Loss: 0.7997, Val MAPE: 0.2698
Epoch [37/100], Train Loss: 0.0376, Val Loss: 0.8605, Val MAPE: 0.2830
Epoch [38/100], Train Loss: 0.0688, Val Loss: 0.7920, Val MAPE: 0.2519
Epoch [39/100], Train Loss: 0.1006, Val Loss: 0.8156, Val MAPE: 0.2762
Epoch [40/100], Train Loss: 0.0444, Val Loss: 0.8101, Val MAPE: 0.2649
Epoch [41/100], Train Loss: 0.0302, Val Loss: 0.8001, Val MAPE: 0.2631
Epoch [42/100], Train Loss: 0.0378, Val Loss: 0.8121, Val MAPE: 0.2723
Epoch [43/100], Train Loss: 0.0592, Val Loss: 0.8025, Val MAPE: 0.2587
Epoch [44/100], Train Loss: 0.0664, Val Loss: 0.8200, Val MAPE: 0.2785
Epoch [45/100], Train Loss: 0.0748, Val Loss: 0.7689, Val MAPE: 0.2474
Epoch [46/100], Train Loss: 0.0627, Val Loss: 0.8469, Val MAPE: 0.2846
Epoch [47/100], Train Loss: 0.0545, Val Loss: 0.8232, Val MAPE: 0.2689
Epoch [48/100], Train Loss: 0.0666, Val Loss: 0.8213, Val MAPE: 0.2780
Epoch [49/100], Train Loss: 0.0401, Val Loss: 0.7768, Val MAPE: 0.2612
Epoch [50/100], Train Loss: 0.0315, Val Loss: 0.8130, Val MAPE: 0.2787
Epoch [51/100], Train Loss: 0.0338, Val Loss: 0.7886, Val MAPE: 0.2649
Epoch [52/100], Train Loss: 0.0421, Val Loss: 0.7789, Val MAPE: 0.2708
Epoch [53/100], Train Loss: 0.0303, Val Loss: 0.7765, Val MAPE: 0.2646
Epoch [54/100], Train Loss: 0.0271, Val Loss: 0.7641, Val MAPE: 0.2662
Epoch [55/100], Train Loss: 0.0276, Val Loss: 0.7766, Val MAPE: 0.2673
Epoch [56/100], Train Loss: 0.0345, Val Loss: 0.7524, Val MAPE: 0.2641
Epoch [57/100], Train Loss: 0.0266, Val Loss: 0.7707, Val MAPE: 0.2673
Epoch [58/100], Train Loss: 0.0237, Val Loss: 0.7484, Val MAPE: 0.2629
Epoch [59/100], Train Loss: 0.0245, Val Loss: 0.7772, Val MAPE: 0.2689
Epoch [60/100], Train Loss: 0.0291, Val Loss: 0.7344, Val MAPE: 0.2590
Epoch [61/100], Train Loss: 0.0252, Val Loss: 0.7736, Val MAPE: 0.2671
Epoch [62/100], Train Loss: 0.0239, Val Loss: 0.7424, Val MAPE: 0.2615
Epoch [63/100], Train Loss: 0.0254, Val Loss: 0.7782, Val MAPE: 0.2696
Epoch [64/100], Train Loss: 0.0304, Val Loss: 0.7402, Val MAPE: 0.2617
Epoch [65/100], Train Loss: 0.0257, Val Loss: 0.7784, Val MAPE: 0.2709
Epoch [66/100], Train Loss: 0.0258, Val Loss: 0.7455, Val MAPE: 0.2637
Epoch [67/100], Train Loss: 0.0255, Val Loss: 0.7807, Val MAPE: 0.2713
Epoch [68/100], Train Loss: 0.0313, Val Loss: 0.7384, Val MAPE: 0.2626
Epoch [69/100], Train Loss: 0.0245, Val Loss: 0.7759, Val MAPE: 0.2696
Epoch [70/100], Train Loss: 0.0242, Val Loss: 0.7553, Val MAPE: 0.2677
Epoch [71/100], Train Loss: 0.0235, Val Loss: 0.7751, Val MAPE: 0.2709
Epoch [72/100], Train Loss: 0.0301, Val Loss: 0.7555, Val MAPE: 0.2682
Epoch [73/100], Train Loss: 0.0254, Val Loss: 0.7851, Val MAPE: 0.2737
Epoch [74/100], Train Loss: 0.0236, Val Loss: 0.7818, Val MAPE: 0.2747
Epoch [75/100], Train Loss: 0.0206, Val Loss: 0.7729, Val MAPE: 0.2719
Epoch [76/100], Train Loss: 0.0275, Val Loss: 0.7533, Val MAPE: 0.2670
Epoch [77/100], Train Loss: 0.0338, Val Loss: 0.7746, Val MAPE: 0.2633
Epoch [78/100], Train Loss: 0.0344, Val Loss: 0.7865, Val MAPE: 0.2763
Epoch [79/100], Train Loss: 0.0253, Val Loss: 0.7581, Val MAPE: 0.2599
Epoch [80/100], Train Loss: 0.0247, Val Loss: 0.8328, Val MAPE: 0.2893
Epoch [81/100], Train Loss: 0.0294, Val Loss: 0.7826, Val MAPE: 0.2673
Epoch [82/100], Train Loss: 0.0336, Val Loss: 0.7612, Val MAPE: 0.2665
Epoch [83/100], Train Loss: 0.0522, Val Loss: 0.7760, Val MAPE: 0.2685
Epoch [84/100], Train Loss: 0.0896, Val Loss: 0.7921, Val MAPE: 0.2742
Epoch [85/100], Train Loss: 0.0260, Val Loss: 0.8362, Val MAPE: 0.2892
Epoch [86/100], Train Loss: 0.0297, Val Loss: 0.7674, Val MAPE: 0.2688
Epoch [87/100], Train Loss: 0.0384, Val Loss: 0.8219, Val MAPE: 0.2883
Epoch [88/100], Train Loss: 0.0328, Val Loss: 0.7882, Val MAPE: 0.2719
Epoch [89/100], Train Loss: 0.0314, Val Loss: 0.7915, Val MAPE: 0.2778
Epoch [90/100], Train Loss: 0.0247, Val Loss: 0.8239, Val MAPE: 0.2841
Epoch [91/100], Train Loss: 0.0259, Val Loss: 0.7523, Val MAPE: 0.2712
Epoch [92/100], Train Loss: 0.0201, Val Loss: 0.7647, Val MAPE: 0.2711
Epoch [93/100], Train Loss: 0.0194, Val Loss: 0.7965, Val MAPE: 0.2821
Epoch [94/100], Train Loss: 0.0177, Val Loss: 0.7770, Val MAPE: 0.2700
Epoch [95/100], Train Loss: 0.0179, Val Loss: 0.7985, Val MAPE: 0.2829
Epoch [96/100], Train Loss: 0.0178, Val Loss: 0.7964, Val MAPE: 0.2747
Epoch [97/100], Train Loss: 0.0175, Val Loss: 0.7581, Val MAPE: 0.2667
Epoch [98/100], Train Loss: 0.0154, Val Loss: 0.8155, Val MAPE: 0.2836
Epoch [99/100], Train Loss: 0.0141, Val Loss: 0.7798, Val MAPE: 0.2731
Epoch [100/100], Train Loss: 0.0125, Val Loss: 0.8100, Val MAPE: 0.2831
    → MAE untuk Bawang Merah - Aceh: 10673.0820
    → MAPE untuk Bawang Merah - Aceh: 0.2824
  → Menggabungkan data untuk provinsi: Bali...
Epoch [1/100], Train Loss: 0.3300, Val Loss: 0.5998, Val MAPE: 0.2167
Epoch [2/100], Train Loss: 0.2975, Val Loss: 0.7397, Val MAPE: 0.2597
Epoch [3/100], Train Loss: 0.2270, Val Loss: 0.6684, Val MAPE: 0.2521
Epoch [4/100], Train Loss: 0.2417, Val Loss: 0.5774, Val MAPE: 0.2226
Epoch [5/100], Train Loss: 0.3004, Val Loss: 0.5668, Val MAPE: 0.2115
Epoch [6/100], Train Loss: 0.2418, Val Loss: 0.7931, Val MAPE: 0.2866
Epoch [7/100], Train Loss: 0.1778, Val Loss: 0.6754, Val MAPE: 0.2575
Epoch [8/100], Train Loss: 0.2560, Val Loss: 0.6615, Val MAPE: 0.2508
Epoch [9/100], Train Loss: 0.2100, Val Loss: 0.7615, Val MAPE: 0.2810
Epoch [10/100], Train Loss: 0.2220, Val Loss: 0.7565, Val MAPE: 0.2760
Epoch [11/100], Train Loss: 0.1554, Val Loss: 0.8722, Val MAPE: 0.3102
Epoch [12/100], Train Loss: 0.1473, Val Loss: 0.6651, Val MAPE: 0.2472
Epoch [13/100], Train Loss: 0.1518, Val Loss: 0.8054, Val MAPE: 0.2951
Epoch [14/100], Train Loss: 0.1809, Val Loss: 0.7583, Val MAPE: 0.2801
Epoch [15/100], Train Loss: 0.1545, Val Loss: 0.7693, Val MAPE: 0.2819
Epoch [16/100], Train Loss: 0.1720, Val Loss: 0.7495, Val MAPE: 0.2772
Epoch [17/100], Train Loss: 0.1331, Val Loss: 0.8296, Val MAPE: 0.3006
Epoch [18/100], Train Loss: 0.1691, Val Loss: 0.7034, Val MAPE: 0.2588
Epoch [19/100], Train Loss: 0.1218, Val Loss: 0.8012, Val MAPE: 0.2929
Epoch [20/100], Train Loss: 0.1755, Val Loss: 0.6909, Val MAPE: 0.2632
Epoch [21/100], Train Loss: 0.1197, Val Loss: 0.7596, Val MAPE: 0.2878
Epoch [22/100], Train Loss: 0.0997, Val Loss: 0.7319, Val MAPE: 0.2791
Epoch [23/100], Train Loss: 0.1178, Val Loss: 0.7702, Val MAPE: 0.2924
Epoch [24/100], Train Loss: 0.1720, Val Loss: 0.6777, Val MAPE: 0.2530
Epoch [25/100], Train Loss: 0.1753, Val Loss: 0.7481, Val MAPE: 0.2811
Epoch [26/100], Train Loss: 0.1502, Val Loss: 0.7675, Val MAPE: 0.2867
Epoch [27/100], Train Loss: 0.1440, Val Loss: 0.7527, Val MAPE: 0.2834
Epoch [28/100], Train Loss: 0.1384, Val Loss: 0.7034, Val MAPE: 0.2692
Epoch [29/100], Train Loss: 0.1683, Val Loss: 0.7935, Val MAPE: 0.2907
Epoch [30/100], Train Loss: 0.1829, Val Loss: 0.8101, Val MAPE: 0.2968
Epoch [31/100], Train Loss: 0.1443, Val Loss: 0.7634, Val MAPE: 0.2834
Epoch [32/100], Train Loss: 0.1387, Val Loss: 0.8200, Val MAPE: 0.3010
Epoch [33/100], Train Loss: 0.1170, Val Loss: 0.7499, Val MAPE: 0.2791
Epoch [34/100], Train Loss: 0.0925, Val Loss: 0.8387, Val MAPE: 0.3080
Epoch [35/100], Train Loss: 0.0720, Val Loss: 0.8094, Val MAPE: 0.2995
Epoch [36/100], Train Loss: 0.1264, Val Loss: 0.7301, Val MAPE: 0.2764
Epoch [37/100], Train Loss: 0.1241, Val Loss: 0.7594, Val MAPE: 0.2855
Epoch [38/100], Train Loss: 0.1608, Val Loss: 0.7623, Val MAPE: 0.2894
Epoch [39/100], Train Loss: 0.1184, Val Loss: 0.7743, Val MAPE: 0.2930
Epoch [40/100], Train Loss: 0.0875, Val Loss: 0.7429, Val MAPE: 0.2796
Epoch [41/100], Train Loss: 0.0641, Val Loss: 0.7941, Val MAPE: 0.3002
Epoch [42/100], Train Loss: 0.0643, Val Loss: 0.8100, Val MAPE: 0.2995
Epoch [43/100], Train Loss: 0.1227, Val Loss: 0.8090, Val MAPE: 0.3030
Epoch [44/100], Train Loss: 0.0576, Val Loss: 0.8266, Val MAPE: 0.3047
Epoch [45/100], Train Loss: 0.0559, Val Loss: 0.8198, Val MAPE: 0.3048
Epoch [46/100], Train Loss: 0.0525, Val Loss: 0.8525, Val MAPE: 0.3132
Epoch [47/100], Train Loss: 0.0798, Val Loss: 0.8036, Val MAPE: 0.2979
Epoch [48/100], Train Loss: 0.0735, Val Loss: 0.8382, Val MAPE: 0.3071
Epoch [49/100], Train Loss: 0.1137, Val Loss: 0.8242, Val MAPE: 0.3066
Epoch [50/100], Train Loss: 0.0523, Val Loss: 0.8676, Val MAPE: 0.3132
Epoch [51/100], Train Loss: 0.0485, Val Loss: 0.8547, Val MAPE: 0.3107
Epoch [52/100], Train Loss: 0.0403, Val Loss: 0.8804, Val MAPE: 0.3186
Epoch [53/100], Train Loss: 0.0398, Val Loss: 0.9163, Val MAPE: 0.3293
Epoch [54/100], Train Loss: 0.0448, Val Loss: 0.8931, Val MAPE: 0.3208
Epoch [55/100], Train Loss: 0.0708, Val Loss: 0.8822, Val MAPE: 0.3176
Epoch [56/100], Train Loss: 0.0505, Val Loss: 0.9229, Val MAPE: 0.3266
Epoch [57/100], Train Loss: 0.0697, Val Loss: 0.8265, Val MAPE: 0.3010
Epoch [58/100], Train Loss: 0.0718, Val Loss: 0.8001, Val MAPE: 0.2873
Epoch [59/100], Train Loss: 0.0994, Val Loss: 0.9005, Val MAPE: 0.3220
Epoch [60/100], Train Loss: 0.0399, Val Loss: 0.8786, Val MAPE: 0.3137
Epoch [61/100], Train Loss: 0.0343, Val Loss: 0.9353, Val MAPE: 0.3312
Epoch [62/100], Train Loss: 0.0308, Val Loss: 0.9192, Val MAPE: 0.3274
Epoch [63/100], Train Loss: 0.0308, Val Loss: 0.9709, Val MAPE: 0.3395
Epoch [64/100], Train Loss: 0.0305, Val Loss: 0.9239, Val MAPE: 0.3266
Epoch [65/100], Train Loss: 0.0361, Val Loss: 0.9212, Val MAPE: 0.3247
Epoch [66/100], Train Loss: 0.0492, Val Loss: 0.8350, Val MAPE: 0.3000
Epoch [67/100], Train Loss: 0.0558, Val Loss: 0.7555, Val MAPE: 0.2714
Epoch [68/100], Train Loss: 0.0611, Val Loss: 0.8600, Val MAPE: 0.3094
Epoch [69/100], Train Loss: 0.0434, Val Loss: 0.8488, Val MAPE: 0.3033
Epoch [70/100], Train Loss: 0.0537, Val Loss: 0.9034, Val MAPE: 0.3229
Epoch [71/100], Train Loss: 0.0397, Val Loss: 0.8690, Val MAPE: 0.3091
Epoch [72/100], Train Loss: 0.0431, Val Loss: 0.9204, Val MAPE: 0.3273
Epoch [73/100], Train Loss: 0.0327, Val Loss: 0.8824, Val MAPE: 0.3140
Epoch [74/100], Train Loss: 0.0325, Val Loss: 0.9379, Val MAPE: 0.3299
Epoch [75/100], Train Loss: 0.0284, Val Loss: 0.9000, Val MAPE: 0.3185
Epoch [76/100], Train Loss: 0.0265, Val Loss: 0.9133, Val MAPE: 0.3232
Epoch [77/100], Train Loss: 0.0273, Val Loss: 0.9056, Val MAPE: 0.3207
Epoch [78/100], Train Loss: 0.0261, Val Loss: 0.9158, Val MAPE: 0.3242
Epoch [79/100], Train Loss: 0.0278, Val Loss: 0.9085, Val MAPE: 0.3213
Epoch [80/100], Train Loss: 0.0254, Val Loss: 0.9193, Val MAPE: 0.3259
Epoch [81/100], Train Loss: 0.0279, Val Loss: 0.9131, Val MAPE: 0.3227
Epoch [82/100], Train Loss: 0.0272, Val Loss: 0.9226, Val MAPE: 0.3259
Epoch [83/100], Train Loss: 0.0300, Val Loss: 0.9017, Val MAPE: 0.3196
Epoch [84/100], Train Loss: 0.0253, Val Loss: 0.9342, Val MAPE: 0.3289
Epoch [85/100], Train Loss: 0.0257, Val Loss: 0.8892, Val MAPE: 0.3166
Epoch [86/100], Train Loss: 0.0264, Val Loss: 0.9425, Val MAPE: 0.3306
Epoch [87/100], Train Loss: 0.0299, Val Loss: 0.8733, Val MAPE: 0.3108
Epoch [88/100], Train Loss: 0.0292, Val Loss: 0.9090, Val MAPE: 0.3218
Epoch [89/100], Train Loss: 0.0334, Val Loss: 0.9044, Val MAPE: 0.3193
Epoch [90/100], Train Loss: 0.0368, Val Loss: 0.8988, Val MAPE: 0.3205
Epoch [91/100], Train Loss: 0.0505, Val Loss: 0.9040, Val MAPE: 0.3157
Epoch [92/100], Train Loss: 0.0485, Val Loss: 0.9022, Val MAPE: 0.3232
Epoch [93/100], Train Loss: 0.0556, Val Loss: 0.8647, Val MAPE: 0.3049
Epoch [94/100], Train Loss: 0.0760, Val Loss: 0.9129, Val MAPE: 0.3231
Epoch [95/100], Train Loss: 0.0325, Val Loss: 0.8663, Val MAPE: 0.3075
Epoch [96/100], Train Loss: 0.0223, Val Loss: 0.9154, Val MAPE: 0.3236
Epoch [97/100], Train Loss: 0.0189, Val Loss: 0.9159, Val MAPE: 0.3260
Epoch [98/100], Train Loss: 0.0181, Val Loss: 0.9556, Val MAPE: 0.3349
Epoch [99/100], Train Loss: 0.0188, Val Loss: 0.9254, Val MAPE: 0.3278
Epoch [100/100], Train Loss: 0.0189, Val Loss: 0.9660, Val MAPE: 0.3376
    → MAE untuk Bawang Merah - Bali: 9333.7051
    → MAPE untuk Bawang Merah - Bali: 0.3159
  → Menggabungkan data untuk provinsi: Banten...
Epoch [1/100], Train Loss: 0.3358, Val Loss: 0.6390, Val MAPE: 0.2795
Epoch [2/100], Train Loss: 0.3038, Val Loss: 0.7282, Val MAPE: 0.2763
Epoch [3/100], Train Loss: 0.2724, Val Loss: 0.9604, Val MAPE: 0.3357
Epoch [4/100], Train Loss: 0.2210, Val Loss: 1.0515, Val MAPE: 0.3615
Epoch [5/100], Train Loss: 0.2126, Val Loss: 1.0698, Val MAPE: 0.3662
Epoch [6/100], Train Loss: 0.1948, Val Loss: 0.9249, Val MAPE: 0.3388
Epoch [7/100], Train Loss: 0.2064, Val Loss: 0.9701, Val MAPE: 0.3477
Epoch [8/100], Train Loss: 0.2581, Val Loss: 1.0398, Val MAPE: 0.3707
Epoch [9/100], Train Loss: 0.2214, Val Loss: 0.9048, Val MAPE: 0.3336
Epoch [10/100], Train Loss: 0.1867, Val Loss: 0.9329, Val MAPE: 0.3377
Epoch [11/100], Train Loss: 0.1611, Val Loss: 0.8353, Val MAPE: 0.3135
Epoch [12/100], Train Loss: 0.1334, Val Loss: 0.8606, Val MAPE: 0.3133
Epoch [13/100], Train Loss: 0.1012, Val Loss: 0.8629, Val MAPE: 0.3238
Epoch [14/100], Train Loss: 0.1844, Val Loss: 0.7748, Val MAPE: 0.3068
Epoch [15/100], Train Loss: 0.2389, Val Loss: 0.7402, Val MAPE: 0.2743
Epoch [16/100], Train Loss: 0.1894, Val Loss: 0.9259, Val MAPE: 0.3400
Epoch [17/100], Train Loss: 0.1959, Val Loss: 0.7327, Val MAPE: 0.2756
Epoch [18/100], Train Loss: 0.1416, Val Loss: 0.8679, Val MAPE: 0.3194
Epoch [19/100], Train Loss: 0.1224, Val Loss: 0.8351, Val MAPE: 0.3124
Epoch [20/100], Train Loss: 0.1299, Val Loss: 0.8262, Val MAPE: 0.3125
Epoch [21/100], Train Loss: 0.1109, Val Loss: 0.7698, Val MAPE: 0.2962
Epoch [22/100], Train Loss: 0.1414, Val Loss: 0.8224, Val MAPE: 0.3101
Epoch [23/100], Train Loss: 0.0817, Val Loss: 0.7465, Val MAPE: 0.2875
Epoch [24/100], Train Loss: 0.1454, Val Loss: 0.8695, Val MAPE: 0.3197
Epoch [25/100], Train Loss: 0.1784, Val Loss: 0.8824, Val MAPE: 0.3269
Epoch [26/100], Train Loss: 0.1480, Val Loss: 0.8088, Val MAPE: 0.3060
Epoch [27/100], Train Loss: 0.1200, Val Loss: 0.8203, Val MAPE: 0.3107
Epoch [28/100], Train Loss: 0.0967, Val Loss: 0.7112, Val MAPE: 0.2692
Epoch [29/100], Train Loss: 0.0742, Val Loss: 0.9216, Val MAPE: 0.3411
Epoch [30/100], Train Loss: 0.0563, Val Loss: 0.7539, Val MAPE: 0.2864
Epoch [31/100], Train Loss: 0.1036, Val Loss: 0.8461, Val MAPE: 0.3174
Epoch [32/100], Train Loss: 0.0957, Val Loss: 0.8516, Val MAPE: 0.3153
Epoch [33/100], Train Loss: 0.1496, Val Loss: 0.8213, Val MAPE: 0.3092
Epoch [34/100], Train Loss: 0.0907, Val Loss: 0.8551, Val MAPE: 0.3231
Epoch [35/100], Train Loss: 0.0630, Val Loss: 0.7728, Val MAPE: 0.2921
Epoch [36/100], Train Loss: 0.0731, Val Loss: 0.8779, Val MAPE: 0.3293
Epoch [37/100], Train Loss: 0.0504, Val Loss: 0.7807, Val MAPE: 0.2943
Epoch [38/100], Train Loss: 0.0374, Val Loss: 0.8844, Val MAPE: 0.3300
Epoch [39/100], Train Loss: 0.0377, Val Loss: 0.7975, Val MAPE: 0.2994
Epoch [40/100], Train Loss: 0.0314, Val Loss: 0.8709, Val MAPE: 0.3254
Epoch [41/100], Train Loss: 0.0306, Val Loss: 0.8122, Val MAPE: 0.3040
Epoch [42/100], Train Loss: 0.0276, Val Loss: 0.8559, Val MAPE: 0.3209
Epoch [43/100], Train Loss: 0.0270, Val Loss: 0.8090, Val MAPE: 0.3027
Epoch [44/100], Train Loss: 0.0311, Val Loss: 0.8481, Val MAPE: 0.3194
Epoch [45/100], Train Loss: 0.0400, Val Loss: 0.8389, Val MAPE: 0.3113
Epoch [46/100], Train Loss: 0.0869, Val Loss: 0.8302, Val MAPE: 0.3125
Epoch [47/100], Train Loss: 0.0306, Val Loss: 0.8287, Val MAPE: 0.3103
Epoch [48/100], Train Loss: 0.0225, Val Loss: 0.8274, Val MAPE: 0.3093
Epoch [49/100], Train Loss: 0.0240, Val Loss: 0.7973, Val MAPE: 0.2999
Epoch [50/100], Train Loss: 0.0249, Val Loss: 0.9081, Val MAPE: 0.3362
Epoch [51/100], Train Loss: 0.0335, Val Loss: 0.7464, Val MAPE: 0.2825
Epoch [52/100], Train Loss: 0.0373, Val Loss: 0.8691, Val MAPE: 0.3228
Epoch [53/100], Train Loss: 0.0353, Val Loss: 0.8160, Val MAPE: 0.3094
Epoch [54/100], Train Loss: 0.0376, Val Loss: 0.8492, Val MAPE: 0.3166
Epoch [55/100], Train Loss: 0.0316, Val Loss: 0.8184, Val MAPE: 0.3091
Epoch [56/100], Train Loss: 0.0338, Val Loss: 0.8347, Val MAPE: 0.3117
Epoch [57/100], Train Loss: 0.0306, Val Loss: 0.8541, Val MAPE: 0.3213
Epoch [58/100], Train Loss: 0.0314, Val Loss: 0.8249, Val MAPE: 0.3075
Epoch [59/100], Train Loss: 0.0344, Val Loss: 0.8911, Val MAPE: 0.3346
Epoch [60/100], Train Loss: 0.0359, Val Loss: 0.8252, Val MAPE: 0.3067
Epoch [61/100], Train Loss: 0.0517, Val Loss: 0.9202, Val MAPE: 0.3449
Epoch [62/100], Train Loss: 0.0395, Val Loss: 0.8117, Val MAPE: 0.3023
Epoch [63/100], Train Loss: 0.0584, Val Loss: 0.9495, Val MAPE: 0.3549
Epoch [64/100], Train Loss: 0.0456, Val Loss: 0.8161, Val MAPE: 0.3045
Epoch [65/100], Train Loss: 0.0713, Val Loss: 0.9666, Val MAPE: 0.3608
Epoch [66/100], Train Loss: 0.0415, Val Loss: 0.8226, Val MAPE: 0.3074
Epoch [67/100], Train Loss: 0.0424, Val Loss: 0.9309, Val MAPE: 0.3480
Epoch [68/100], Train Loss: 0.0321, Val Loss: 0.8472, Val MAPE: 0.3158
Epoch [69/100], Train Loss: 0.0254, Val Loss: 0.9239, Val MAPE: 0.3442
Epoch [70/100], Train Loss: 0.0236, Val Loss: 0.8559, Val MAPE: 0.3189
Epoch [71/100], Train Loss: 0.0246, Val Loss: 0.9244, Val MAPE: 0.3449
Epoch [72/100], Train Loss: 0.0222, Val Loss: 0.8607, Val MAPE: 0.3205
Epoch [73/100], Train Loss: 0.0218, Val Loss: 0.9282, Val MAPE: 0.3459
Epoch [74/100], Train Loss: 0.0222, Val Loss: 0.8693, Val MAPE: 0.3233
Epoch [75/100], Train Loss: 0.0253, Val Loss: 0.9280, Val MAPE: 0.3466
Epoch [76/100], Train Loss: 0.0232, Val Loss: 0.8750, Val MAPE: 0.3252

KeyboardInterrupt: